### ISSUE TITLE
Refactor vispy canvas out of qt_viewer.py into own file

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#855] opened 2020-01-08 05:27 UTC
## 🚀 Feature
After #854 goes in I'd like to refactor the vispy code out of `qt_viewer` into its own file maybe inside the `_vispy` folder or maybe called `QtCanvas` and still in the `_qt` folder.

The goal is to simplify the `QtViewer` code and make the vispy code more separated from the rest of the code.

Curious what @jni @tlambert03 thinks, and how this relates to organization in #823?

**Comment by GenevieveBuckley** [comment] 2023-06-23 06:28
It looks like this has been addressed by https://github.com/napari/napari/pull/5432 @melonora can you confirm?

**Closed as completed by GenevieveBuckley** 2023-06-23 06:28 UTC
Labels: question, refactor

**Comment by melonora** [comment] 2023-06-23 08:42
@GenevieveBuckley I can confirm:)
