### ISSUE TITLE
Napari error : does not install plugin in GUI bundle app 

### ISSUE THREAD

**Issue by PMLLancao** [napari/napari#3097] opened 2021-07-29 03:00 UTC
## 🐛 Bug

I am using the bundle app without python in MAC OSX mojave.
I want to install plugins to use napari but it does not work..
Every time that I tried to install a plugin I received this error:

2021-07-28 22:57:36.775 napari[2163:247395] error: unrecognized arguments: --upgrade

## To Reproduce
Downloadind the app and install in mac.
Try to install plugin

2021-07-28 22:57:36.775 napari[2163:247395] error: unrecognized arguments: --upgrade
## Expected behavior

I want to be able to use plugins for segmentation and 3D

**Comment by tlambert03** [comment] 2021-07-29 14:49
this is a duplicate of https://github.com/napari/napari/issues/2965, 
it should have been fixed in https://github.com/napari/napari/pull/2980... but I just tested the recent and indeed it didn't work.  I'm going to close this issue, since we already have a dedicated (and open) issue for this.  please track progress at #2965

**Closed as completed by tlambert03** 2021-07-29 14:49 UTC
Labels: bug
