### ISSUE TITLE
Jupyter - Kernel dies when napari.Viewer() is called 

### ISSUE THREAD

**Issue by bill-connelly** [napari/napari#6681] opened 2024-02-22 02:49 UTC
### 🐛 Bug Report

I try to load napari and the kernel dies

### 💡 Steps to Reproduce

%gui qt
import napari
napari.Viewer()

and the kernel dies. The same thing happens if I use %gui qt5

If I don't include the magic, then I get the error message:
WARNING: could not connect to display 
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
And THEN the kernel dies.

### 🌎 Environment

napari --info gives:

apari --info
WARNING: pyqt5 already imported, cannot switch to pyside2
WARNING:vispy:pyqt5 already imported, cannot switch to pyside2
napari: 0.4.19
Platform: Linux-5.15.0-94-generic-x86_64-with-glibc2.35
System: Ubuntu 22.04.2 LTS
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.25.0
SciPy: 1.11.4
Dask: 2024.2.0
VisPy: 0.14.1
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.4
npe2: 0.7.4

### 💡 Additional Context

I dont have any virtual environment running. No Conda. Installed with:

python -m pip install "napari[all]"

When I run napari from the command line, it loads properly

**Comment by Czaki** [comment] 2024-02-22 08:53
Did you have `pyside2` in your environment (if it is in `pip list` output)?

**Comment by bill-connelly** [comment] 2024-02-22 09:26
PyQt5                         5.15.10
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.13.0
pyrsistent                    0.18.1
pyserial                      3.5
PySide2                       5.15.2.1


Though I have just found out that simply calling

%gui qt5

crashes the kernel.

I appreciate this means it's not Napari's problem, but does anyone have any idea why this happens?

**Comment by psobolewskiPhD** [comment] 2024-02-22 15:02
This issue is exactly why we recommend working with virtual environments, because these types of incompatibilities can be hard to solve and hard to troubleshoot.

**Comment by psobolewskiPhD** [comment] 2024-05-27 02:57
I'm going to close this. If the issue is reproduced in an env without conflicting Qt bindings, please re-open or make a new issue!
❤️

**Closed as completed by psobolewskiPhD** 2024-05-27 02:57 UTC
Labels: bug
