### ISSUE TITLE
Image pyramid resoution changes stop working if you switch from 2D -> 3D view -> 2D again

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#821] opened 2019-12-20 06:15 UTC
## 🐛 Bug

If you open a multi-resolution image in napari, the default 2D view will automatically load the different resolution levels as you zoom in and out. BUT if you switch the view to a 3D volume view, and then switch back to a 2D view, then the multiresolution levels don't work anymore when you zoom in and out with the mouse wheel.

cc @gazzar who found this out in the last 5 minutes of our napari hack day! 

Gary says he needs to catch the train now but will add links or add any other information I forgot.

## To Reproduce

1. Load a multiresolution image into napari.
2. Zoom in & out in the 2D mode and see the resolution levels changing automatically
3. Switch to the 3D volume view.
4. Switch back to the 2D image plane view.
5. Zoom in & out in the 2D mode and see that the resolution levels don't update automatically anymore :(

Gary says the code sample he used is in this gist: https://gist.github.com/gazzar/d06a1cafdba9888a47d905e2664d070f

## Expected behavior

We expected the resolution levels to update like they did when we first opened the image.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by GenevieveBuckley** [comment] 2019-12-20 06:21
@gazzar can you add this info in a comment below please?

> * Please copy and paste the information at napari info option in help menubar here:
> * Any other relevant information:

**Comment by gazzar** [comment] 2019-12-20 10:46
Thanks for creating this bug report for me @GenevieveBuckley 

napari info option:

napari: 0.2.7+1.g0ecabae.dirty 
Platform: Windows-10-10.0.17134-SP0 
Python: 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] 
PySide2: 5.14.0 
Qt: 5.14.0 
VisPy: 0.6.4 
NumPy: 1.17.4 
SciPy: 1.4.1 
scikit-image: 0.16.2 
Dask: 2.9.0 

GL version: '4.5.0 - Build 23.20.16.4973'
MAX_TEXTURE_SIZE: 16384 

Other relevant information:
The multiresolution image I used is a BigDataViewer dataset with 4 levels of pyramid representation. Unfortunately I'm not able to share the data I used.

**Comment by sofroniewn** [comment] 2019-12-20 16:37
Thanks for catching this! The 3D pyramid will only show the most zoomed out layer. It should still work again properly when switching back to 2D though. I'll have a look at where the problem is. Shouldn't be too hard to fix

**Comment by sofroniewn** [comment] 2020-05-02 23:22
This has now been fixed with our recent `multiscale` improvements - see this code to confirm it is no longer an issue

```python
    data = [np.random.random((5, 2**s, 2**s)) for s in range(13, 8, -1)]
    viewer.add_image(data)
```

If this example didn't fully capture the bug and a new minimal example is given we can reopen. Thanks all for flagging

**Closed as completed by sofroniewn** 2020-05-02 23:22 UTC
Labels: bug
