### ISSUE TITLE
Can't resize axis aligned ellipse.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#4262] opened 2022-03-15 11:20 UTC
## 🐛 Bug

When an ellipse is axis aligned in the shape layer, the middle edges of the bounding box handle do not allow resizing:

https://user-images.githubusercontent.com/335567/158365922-9f7e59a5-9eec-46cf-a714-e0e164edff3c.mov

There are other issues with handles if you programatically create ellipses with non-rectangular bounding boxes.

This may be related to other things like #4258

I'm also astonished about some of the documentation/comments that the internal representation need to be 4-corners (that might be unsound) as we need to support rotation. In particular as it looks like the tessellation code recompute center/angle and axis. So maybe revisiting internal repr could be a good idea as well ?

**Comment by andy-sweet** [comment] 2022-05-03 20:56
I think the main bug here should be closed by #4262. @Carreau or @2dx : can you confirm? Should we leave this open for the other related issues (e.g. ellipses created with non-rectangular bounding boxes) or create a separate issue for that?

**Comment by psobolewskiPhD** [comment] 2024-01-21 18:54
Can't reproduce on 0.4.18 or main, so I do think this was closed by #4291 
The non-rectangular bounding boxes has an issue already: https://github.com/napari/napari/issues/4289
Closing.

**Closed as completed by psobolewskiPhD** 2024-01-21 18:54 UTC
Labels: bug
