### ISSUE TITLE
QSocketNotifier warning when using viewer

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#627] opened 2019-10-25 22:54 UTC
## 🐛 Bug

Cross posting from imagesc

>whenever I use your amazing viewer inside my notebooks I get the following warning (see screenshot). Anything I can do to get rid of this? My conda is using a slightly older pyqt (5.9.7) version then recommended.
>
>WARNING: QSocketNotifier: Multiple socket notifiers for same socket 996 and type Read
>```
>viewer = napari.Viewer()
>viewer.add_image(array[:, :, 0, :, :, :], name=metadata['Channels'][0], scale=(1, 1, 1, scalef, 1, 1))
>viewer.add_image(array[:, :, 1, :, :, :], name=metadata['Channels'][1], scale=(1
>```

https://forum.image.sc/t/qsocketnotifier-warning-when-using-viewer/30721

I've seen this on some installs - we should look into it. Maybe @AhmetCanSolak has an idea

**Comment by jni** [comment] 2019-10-26 10:52
Searching the interwebs for that error message brings up some pretty obscure stuff. =(

@sofroniewn when you say you've seen it before: was it always on old versions of Qt as in Sebi's post, or did you see it even on newer Qt?

**Comment by sofroniewn** [comment] 2019-10-26 16:07
i'm not sure, it was during the training i did at sfn, it happened for some of the students, but not all. i'm not sure if there was a pattern

**Comment by AhmetCanSolak** [comment] 2019-10-28 18:50
would be happy to get more details to reproduce this

**Comment by MaximilianHoffmann** [comment] 2019-12-11 08:55
It happens for me. Environment:
```
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appdirs                   1.4.3                    pypi_0    pypi
arrow                     0.13.1                   py37_0
asciitree                 0.3.3                    pypi_0    pypi
attrs                     19.3.0                     py_0
av                        6.2.0            py37heb183d3_1    conda-forge
babel                     2.7.0                    pypi_0    pypi
backcall                  0.1.0                    py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
colorama                  0.4.1                    py37_0
cycler                    0.10.0                   py37_0
cython                    0.29.14          py37ha925a31_0
dask                      2.6.0                    pypi_0    pypi
decorator                 4.4.1                      py_0
defusedxml                0.6.0                      py_0
docutils                  0.15.2                   pypi_0    pypi
entrypoints               0.3                      py37_0
fasteners                 0.15                     pypi_0    pypi
ffmpeg                    4.1.3                h6538335_0    conda-forge
freetype                  2.9.1                ha9979f8_1
freetype-py               2.1.0.post1              pypi_0    pypi
fsspec                    0.5.2                    pypi_0    pypi
h5py                      2.8.0            py37hf7173ca_2
hdf5                      1.8.20               hac2f561_1
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.8                      pypi_0    pypi
imageio                   2.6.1                    py37_0
imagesize                 1.1.0                    pypi_0    pypi
importlib_metadata        0.23                     py37_0
intel-openmp              2019.4                      245
ipykernel                 5.1.1                    pypi_0    pypi
ipython                   7.9.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
jedi                      0.15.1                   py37_0
jinja2                    2.10.3                     py_0
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.2.0                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.6.1                    py37_0
kiwisolver                1.1.0            py37ha925a31_0
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  9.0.0           default_hf44288c_4    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
liblapacke                3.8.0                    14_mkl    conda-forge
libopencv                 4.1.2                    py37_2    conda-forge
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libtiff                   4.1.0                h56a325e_0
libwebp                   1.0.2                hfa6e2cd_4    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37he774522_0
matplotlib                3.1.2                    py37_1    conda-forge
matplotlib-base           3.1.2            py37h2981e6d_1    conda-forge
mistune                   0.8.4            py37he774522_0
mkl                       2019.4                      245
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
monotonic                 1.5                      pypi_0    pypi
more-itertools            7.2.0                    py37_0
msys2-conda-epoch         20160418                      1
napari                    0.2.3                    pypi_0    pypi
nb_conda                  2.2.1                    py37_0
nb_conda_kernels          2.2.2                    py37_0
nbconvert                 5.6.1                    py37_0
nbformat                  4.4.0                    py37_0
networkx                  2.4                      pypi_0    pypi
nidaqmx                   0.5.7                    pypi_0    pypi
notebook                  6.0.2                    py37_0
numcodecs                 0.6.3                    pypi_0    pypi
numpy                     1.17.4           py37h4320e6b_0
numpy-base                1.17.4           py37hc3f5095_0
numpydoc                  0.9.1                    pypi_0    pypi
olefile                   0.46                     py37_0
opencv                    4.1.2                    py37_2    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
packaging                 19.2                     pypi_0    pypi
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.5.1                      py_0
pickleshare               0.7.5                    py37_0
pillow                    6.2.1            py37hdc69c19_0
pip                       19.3.1                   py37_0
prometheus_client         0.7.1                      py_0
prompt_toolkit            2.0.10                     py_0
py-opencv                 4.1.2            py37h5ca1d4c_2    conda-forge
pycparser                 2.19                     pypi_0    pypi
pygments                  2.4.2                      py_0
pyopengl                  3.1.0                    pypi_0    pypi
pyparsing                 2.4.5                      py_0
pyqt                      5.12.3           py37h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.6           py37he774522_0
pyside2                   5.13.1                   pypi_0    pypi
python                    3.7.5                h8c8aaf0_0
python-dateutil           2.8.1                      py_0
pytools                   2019.1.1                 pypi_0    pypi
pytz                      2019.3                     py_0
pywavelets                1.1.1                    pypi_0    pypi
pywin32                   223              py37hfa6e2cd_1
pywinpty                  0.5.5                 py37_1000
pyzmq                     18.1.0           py37ha925a31_0
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtconsole                 4.6.0                      py_0
qtpy                      1.9.0                    pypi_0    pypi
requests                  2.22.0                   pypi_0    pypi
scikit-image              0.16.2                   pypi_0    pypi
scipy                     1.3.1            py37h29ff71c_0
send2trash                1.5.0                    py37_0
setuptools                42.0.1                   py37_0
shiboken2                 5.13.1                   pypi_0    pypi
sip                       4.19.8           py37h6538335_0
six                       1.13.0                   py37_0
snowballstemmer           2.0.0                    pypi_0    pypi
soundfile                 0.10.3.post1             pypi_0    pypi
sphinx                    2.2.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.1                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.1                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.2                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.2                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.3                    pypi_0    pypi
sqlite                    3.30.1               he774522_0
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.10.0                   pypi_0    pypi
tornado                   6.0.3            py37he774522_0
tqdm                      4.39.0                     py_0
traitlets                 4.3.3                    py37_0
urllib3                   1.25.6                   pypi_0    pypi
vc                        14.1                 h0510ff6_4
vispy                     0.6.1                    pypi_0    pypi
vs2015_runtime            14.16.27012          hf0eaf9b_0
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
wheel                     0.33.6                   py37_0
widgetsnbextension        3.5.1                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.2                   pypi_0    pypi
xz                        5.2.4                h2fa13f4_4
zarr                      2.3.2                    pypi_0    pypi
zeromq                    4.3.1                h33f27b4_3
zipp                      0.6.0                      py_0
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0`
```

**Comment by sofroniewn** [comment] 2019-12-15 23:04
I think this may now be fixed in the new `0.6.4` release of vispy - see this PR here https://github.com/vispy/vispy/pull/1789

If someone that has been having this error with napari check on both the `0.6.3` and `0.6.4` release of vispy and confirm this is now fixed then I will close this issue

**Comment by jni** [comment] 2019-12-17 03:20
@sofroniewn I was just about to post exactly the same thing. =D It will be so exciting to be rid of this!

**Comment by sofroniewn** [comment] 2019-12-17 05:19
@jni can you confirm that the vispy bump fixes this issue for napari. I expect it does, but it would be nice to be sure before closing this issue. I have created a napari PR to bump our version in #807

**Comment by jni** [comment] 2019-12-17 07:03
@sofroniewn I personally can't, since I've never seen it on my machines. But I'll let you know on napari hack day if anyone else encounters it and it gets fixed by the new release. =)

**Closed as completed** 2019-12-17 16:19 UTC
Labels: bug
