### ISSUE TITLE
Slow / unresponsive terminal

### ISSUE THREAD

**Issue by stefanv** [napari/napari#696] opened 2019-11-15 07:34 UTC
## 🐛 Bug

When running up Napari in `ipython --gui=qt`, the terminal button does not fire up a terminal.

When running Napari in a Jupyter notebook with `%gui qt`, the terminal appears but is very slow and sometimes entirely unresponsive.

## Environment

```
napari, 0.2.5+11.g8ce944a
Qt, 5.13.0
NumPy, 1.17.2
SciPy, 1.3.0
VisPy, 0.6.1
scikit-image, 0.17.dev0
```

```
Platform: Linux-4.19.0-5-amd64-x86_64-with-debian-bullseye-sid
Python:   3.7.5 (default, Oct 15 2019, 15:24:06)  [GCC 9.2.1 20191008]
Backend:  PyQt5
GL version:  '3.0 Mesa 18.2.8'
MAX_TEXTURE_SIZE: 16384
```

**Comment by jni** [comment] 2019-11-15 07:37
@stefanv the first issue is known but not documented. We need to give a better indication that this is expected. We tried but could not get a different IPython instance talking to the same kernel for IPython Terminal.

The second issue, though, is concerning...

**Comment by jni** [comment] 2019-11-15 07:37
Possibly worth providing IPython, ipykernel, QtConsole, and Jupyter Notebook version numbers...

**Comment by sofroniewn** [comment] 2019-11-15 17:04
@stefanv - for the terminal when connected to a jupyter notebook I found that I had to press shift-enter to execute any code - i.e. it behaves like a jupyter notebook cell. If anyone knew how to disable that so it executed on just enter that would be great

**Comment by jni** [comment] 2020-08-29 13:02
In the medium term, the IPython console in napari is going to become optional. Additionally, since we have not been able to reproduce this and there's been several IPython and ipykernel releases in the meantime, I'm going to close this. As always, feel free to reopen if you encounter this issue again.

**Closed as completed by jni** 2020-08-29 13:02 UTC
Labels: bug, performance
