### ISSUE TITLE
Labels Layer - Color in layer controls not the same as drawing color

### ISSUE THREAD

**Issue by Chris-N-K** [napari/napari#5998] opened 2023-06-23 11:17 UTC
## 🐛 Bug
For some values the colour displayed in the `Labels` layer controls and the drawing colour are not the same.
The values are 55, 122, 157, 160, 178, 256,.. They do not follow a particular order and there might be many more as I only tested till 256.

## To Reproduce

1. Add `Labels` layer
2. Change the label value one from the list
3. Draw label

## Expected behaviour
The colour in the controls and the drawn colour should be identical.

## Environment
napari: 0.4.17
Platform: Linux-5.14.0-1054-oem-x86_64-with-glibc2.35
System: Ubuntu 22.04.2 LTS
Python: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.3
SciPy: 1.10.1
Dask: 2023.5.0
VisPy: 0.11.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**This bug is in 0.4.18rc1 as well**
## Additional context

![colour_bug_screenshot](https://github.com/napari/napari/assets/56394171/1d13b912-dd9c-4366-a18c-da04f1dca96c)

**Comment by psobolewskiPhD** [comment] 2023-06-23 11:44
I can replicate this even in 0.4.18
This seems like a duplicate of https://github.com/napari/napari/issues/5507
but you provide really useful info because it replicates for me with those specific label numbers !!
<img width="1198" alt="image" src="https://github.com/napari/napari/assets/76622105/35e6e6ac-c43c-4792-9687-8cbe7d4f29d7">

**Comment by Czaki** [comment] 2023-07-07 22:26
Yeah. This mismatch change after the shuffle is expected because of bug in how it is implemented.

**Comment by jni** [comment] 2023-07-24 00:01
I verified with @brisvag last week that #3308 changes *which* labels are mismatched, but it does not eliminate the problem. See #6083 for an explanation and a proposed path to fixing this.

**Comment by Czaki** [comment] 2023-08-14 13:43
@jni What is the status of that?

**Comment by jni** [comment] 2023-08-14 14:47
The proposal in #6083 needs to be implemented before this is fixed. I can try to have a good crack at it this week but I'm not sure it's something that can be fixed for 0.4.19... Since this is a *very* long-standing issue, I don't think it's critical that it goes in 0.4.19.

**Closed as completed** 2023-10-11 14:48 UTC
Labels: bug
