### ISSUE TITLE
Antialiasing to reduce Moire effects 

### ISSUE THREAD

**Issue by royerloic** [napari/napari#225] opened 2019-04-20 20:01 UTC
## 🚀 Feature

Antialiasing for 2D rendering

![image](https://user-images.githubusercontent.com/1870994/56461729-714cff00-636c-11e9-8930-baeb725e3a95.png)

## Motivation

Modern graphics card are very very powerfull, 2D rendering is peanuts for them.
OpenGL has lots of cool features such as [MSAA](http://en.wikipedia.org/wiki/Multisample_anti-aliasing) that can be just turned on.
Vispy seems to support some antialiasing (not sure what kind).

Here is a discussion on this by the VISPY folks:

https://github.com/vispy/vispy/wiki/Tech.-Antialiasing

Some visuals in Vispy support it:

http://vispy.org/visuals.html

But in our case it seems that for example that the vectors layers for example is heavily aliased.

## Proposal:

- make sure that all visuals have `antialias=True` (particularly vectors layer)
- Try to use MSAA by turning it on at the OpenGL level

**Comment by sofroniewn** [comment] 2019-04-20 20:08
We are no longer using OpenGL lines in the vectors layer, but now using [mesh visuals](http://vispy.org/visuals.html#vispy.visuals.MeshVisual) due to problems with arbitrary line widths. I am not sure if they support an antialias mode

**Comment by royerloic** [comment] 2019-04-20 20:09
They should, antialias is not specific to old lines stuff...

**Comment by sofroniewn** [comment] 2019-04-20 20:10
That's great. I didn't see it exposed at a highlevel in vispy for meshes like it is for some line visuals, but we can dig in

**Comment by sofroniewn** [comment] 2020-08-07 02:42
This behaviour was fixed by using the mesh visual in #215 and i can no longer reproduce any moire effects. If anyone encounters additional aliasing problems they can either reopen this issue or create a new one with steps to reproduce

**Closed as completed by sofroniewn** 2020-08-07 02:42 UTC
Labels: bug
