### ISSUE TITLE
error when importing napari: FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by katierupp** [napari/napari#1112] opened 2020-04-05 03:54 UTC
Hello, I have successfully installed napari with pip, but when I run `import napari` in a Jupyter 
notebook or type `napari` in the command window, I receive the error shown at the 
end of this post. I get the following output when I run 

`import vispy
print(vispy.sys_info())`

```
Platform: Windows-10-10.0.18362-SP0
Python:   3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
NumPy:    1.18.2
Backend:  ipynb_webgl
pyqt4:    None
pyqt5:    None
pyside:   None
pyside2:  ('PySide2', '5.14.2', '5.14.2')
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  ''
MAX_TEXTURE_SIZE: ()
Extensions: ''
```

App info-gathering error:

```pytb
Traceback (most recent call last):
  File "C:\Users\Rupp\AppData\Roaming\Python\Python37\site-packages\vispy\util\config.py", line 438, in sys_info
    canvas.close()
  File "C:\Users\Rupp\AppData\Roaming\Python\Python37\site-packages\vispy\app\canvas.py", line 457, in close
    self._backend._vispy_close()
  File "C:\Users\Rupp\AppData\Roaming\Python\Python37\site-packages\vispy\app\backends\_ipynb_webgl.py", line 203, in _vispy_close
    raise NotImplementedError()
NotImplementedError`

I tried changing the backend  with `vispy.use('PyQt5')`, but the same error (shown at the end of the post) was produced in addition to these warnings: 

`WARNING: Could not load the Qt platform plugin "windows" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: direct2d, minimal, offscreen, windows.`


Now here is the error I got from importing Napari: 
---------------------------------------------------------------------------
`FileNotFoundError                         Traceback (most recent call last)
~\Downloads\tuthilllab\napari\napari\resources\build_icons.py in build_pyqt_resources(out_path, overwrite)
    170     try:
--> 171         check_call(['pyrcc5', '-o', out_path, qrc_path])
    172     except (FileNotFoundError, CalledProcessError):

~\Anaconda3\lib\subprocess.py in check_call(*popenargs, **kwargs)
    322     """
--> 323     retcode = call(*popenargs, **kwargs)
    324     if retcode:

~\Anaconda3\lib\subprocess.py in call(timeout, *popenargs, **kwargs)
    303     """
--> 304     with Popen(*popenargs, **kwargs) as p:
    305         try:

~\Anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    755                                 errread, errwrite,
--> 756                                 restore_signals, start_new_session)
    757         except:

~\Anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1154                                          os.fspath(cwd) if cwd is not None else None,
-> 1155                                          startupinfo)
   1156             finally:

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-5990be5a6c61> in <module>
      1 from skimage import data
----> 2 import napari
      3 viewer = napari.view_image(data.astronaut(), rgb=True)

~\Downloads\tuthilllab\napari\napari\__init__.py in <module>
     48 vispy_logger.setLevel(logging.WARNING)
     49 
---> 50 from .viewer import Viewer
     51 
     52 # Note that importing _viewer_key_bindings is needed as the Viewer gets

~\Downloads\tuthilllab\napari\napari\viewer.py in <module>
      4 from qtpy.QtWidgets import QApplication
      5 
----> 6 from ._qt.qt_update_ui import QtUpdateUI
      7 from ._qt.qt_main_window import Window
      8 from ._qt.qt_viewer import QtViewer

~\Downloads\tuthilllab\napari\napari\_qt\__init__.py in <module>
      3 from ..resources import import_resources
      4 
----> 5 import_resources()

~\Downloads\tuthilllab\napari\napari\resources\__init__.py in import_resources(version, overwrite)
    115     # regenerated.
    116     overwrite = overwrite or bool(environ.get('NAPARI_REBUILD_RESOURCES'))
--> 117     respath = build_pyqt_resources(fspath(target_file), overwrite=overwrite)
    118 
    119     # import the python resources file and add to sys.modules

~\Downloads\tuthilllab\napari\napari\resources\build_icons.py in build_pyqt_resources(out_path, overwrite)
    171         check_call(['pyrcc5', '-o', out_path, qrc_path])
    172     except (FileNotFoundError, CalledProcessError):
--> 173         check_call(['pyside2-rcc', '-o', out_path, qrc_path])
    174 
    175     # make sure we import from qtpy

~\Anaconda3\lib\subprocess.py in check_call(*popenargs, **kwargs)
    321     check_call(["ls", "-l"])
    322     """
--> 323     retcode = call(*popenargs, **kwargs)
    324     if retcode:
    325         cmd = kwargs.get("args")

~\Anaconda3\lib\subprocess.py in call(timeout, *popenargs, **kwargs)
    302     retcode = call(["ls", "-l"])
    303     """
--> 304     with Popen(*popenargs, **kwargs) as p:
    305         try:
    306             return p.wait(timeout=timeout)

~\Anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    754                                 c2pread, c2pwrite,
    755                                 errread, errwrite,
--> 756                                 restore_signals, start_new_session)
    757         except:
    758             # Cleanup if the child failed starting.

~\Anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1153                                          env,
   1154                                          os.fspath(cwd) if cwd is not None else None,
-> 1155                                          startupinfo)
   1156             finally:
   1157                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by tlambert03** [comment] 2020-04-05 14:37
Hi @katierupp, thanks for letting us know!  Looks like a failed installation, and I'd like to try to reproduce this locally... can you tell me exactly how you set up your environment and installed pip?    It's a little unclear cause it looks like you have both a global python interpreter but also conda?
please let use know:
- how did you install python (python.org?  anaconda? etc...)
- are you using a virtual environment, and if so, how did you create it, 
- exactly how did you install napari.  is this a fresh environment?  or something where you've already installed a lot of other packages?

**Comment by katierupp** [comment] 2020-04-05 16:34
Hi @tlambert03, thanks for the response! 

I installed python with Anaconda, and I was not using a virtual environment, so I was trying to install napari where there are a lot of other packages.

I tried napari by cloning the git repository, navigating to the directory, then calling `pip install -e .`. This is what was producing the error in my original post. However, I just tried using  `pip install -e . --ignore-installed` and I no longer get the error when I test by running `napari`, however I still get these warnings:  

`(base) C:\Users\Rupp\Downloads\napari>napari
WARNING: Could not load the Qt platform plugin "windows" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, windows.`

Let me know if you have any more questions about the installation.

**Comment by tlambert03** [comment] 2020-04-05 16:41
Thanks for the extra info.  First, I'd like to nail down if this is somehow a problem with your environment, or our installation process (for instance, if it's a problem with our install on certain machines).  Can you test whether it all works in a clean environment?

```cmd
conda create -y -n testenv python=3.7
conda activate testenv
pip install napari
# or to install a local cloned repo:  pip install -e .
napari
```

**Comment by katierupp** [comment] 2020-04-05 20:32
Yes, I ended up uninstalling and reinstalling Anaconda because I wasn't able to make a new environment. Now that I am able to, I was able to install napari, but when I call  `napari` I get this traceback: 

```pytb
(testenv) C:\Users\Rupp\Downloads\napari>napari

c:\users\rupp\downloads\napari\napari\__init__.py:38: UserWarning:
    napari was tested with QT library `>=5.12.3`.
    The version installed is 5.9.6. Please report any issues with this
    specific QT version at https://github.com/Napari/napari/issues.

  warn(message=warn_message)
Traceback (most recent call last):
  File "c:\users\rupp\downloads\napari\napari\resources\build_icons.py", line 171, in build_pyqt_resources
    check_call(['pyrcc5', '-o', out_path, qrc_path])
  File "C:\Users\Rupp\Anaconda3\envs\testenv\lib\subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Rupp\Anaconda3\envs\testenv\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Rupp\Anaconda3\envs\testenv\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Rupp\Anaconda3\envs\testenv\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rupp\Anaconda3\envs\testenv\Scripts\napari-script.py", line 11, in <module>
    load_entry_point('napari', 'console_scripts', 'napari')()
  File "C:\Users\Rupp\Anaconda3\envs\testenv\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Rupp\Anaconda3\envs\testenv\lib\site-packages\pkg_resources\__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "C:\Users\Rupp\Anaconda3\envs\testenv\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "C:\Users\Rupp\Anaconda3\envs\testenv\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\rupp\downloads\napari\napari\__init__.py", line 50, in <module>
    from .viewer import Viewer
  File "c:\users\rupp\downloads\napari\napari\viewer.py", line 6, in <module>
    from ._qt.qt_update_ui import QtUpdateUI
  File "c:\users\rupp\downloads\napari\napari\_qt\__init__.py", line 5, in <module>
    import_resources()
  File "c:\users\rupp\downloads\napari\napari\resources\__init__.py", line 117, in import_resources
    respath = build_pyqt_resources(fspath(target_file), overwrite=overwrite)
  File "c:\users\rupp\downloads\napari\napari\resources\build_icons.py", line 173, in build_pyqt_resources
    check_call(['pyside2-rcc', '-o', out_path, qrc_path])
  File "C:\Users\Rupp\Anaconda3\envs\testenv\lib\subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Rupp\Anaconda3\envs\testenv\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Rupp\Anaconda3\envs\testenv\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Rupp\Anaconda3\envs\testenv\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by tlambert03** [comment] 2020-04-05 20:53
that is _very_ strange.  it definitely points to something broken in your old environment, but it's also weird that in your new anaconda install, even when you create a fresh `testenv` environment, you're _still_ only getting Qt 5.9.6, instead of the current Qt 5.14.  I have to say that's the first time I've seen that.  sorry to keep making you try things, but I want to rule some things out:

1) are you on a standard windows 10 installation, with anaconda installed the standard way into your user account?  Can you think of anything that might be unusual about permissions or OS on your system?

2) can you send me the full list of what got installed in your testenv:
    ```
    conda activate testenv
    conda list
    ```
    and how did you retrieve the copy of napari in your downloads folder, git clone?  download zip? 
3) could you try _not_ installing the napari that's in your downloads folder, but install fresh from github into a new environment:
    ```
    conda create -y -n testenv2 python=3.7
    conda activate testenv2
    pip install git+https://github.com/napari/napari.git
    conda list  # send me the output from this if it doesn't work
    napari --info  # send me the output from this if it doesn't work
    napari
    ```
UPDATE: sorry... i updated this, don't `pip install napari` rather do `pip install git+https://github.com/napari/napari.git`

**Comment by katierupp** [comment] 2020-04-05 21:13
1. Yes, I just followed the installation instructions for installing Anaconda on Windows. I am not aware of anything unusual about the permissions. 

2.  I retrieved napari using git clone. 

For `conda list` in testenv : 
```
(testenv) C:\Users\Rupp>conda list

packages in environment at C:\Users\Rupp\Anaconda3\envs\testenv:

 Name                    Version                   Build  Channel
ca-certificates           2020.1.1                      0
certifi                   2019.11.28               py37_1
icu                       58.2                 ha66f8fd_1
jedi                      0.16.0                   pypi_0    pypi
jpeg                      9b                   hb83a4c4_2
libpng                    1.6.37               h2a8f88b_0
napari                    0.2.12+40.gca06948           dev_0    <develop>
openssl                   1.1.1f               he774522_0
parso                     0.6.2                    pypi_0    pypi
pip                       20.0.2                   py37_1
pyqt                      5.9.2            py37h6538335_2
python                    3.7.7           h60c2a47_0_cpython
qt                        5.9.7            vc14h73c81de_0
setuptools                46.1.3                   py37_0
sip                       4.19.8           py37h6538335_0
sqlite                    3.31.1               he774522_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wheel                     0.34.2                   py37_0
wincertstore              0.2                      py37_0
zlib                      1.2.11               h62dcd97_3
```

3. using `pip install git+https://github.com/napari/napari.git`, I still get the same error. 

For `conda list` in testenv2: 

```
(testenv2) C:\Users\Rupp>conda list
 packages in environment at C:\Users\Rupp\Anaconda3\envs\testenv2:

 Name                    Version                   Build  Channel
ca-certificates           2020.1.1                      0
certifi                   2019.11.28               py37_1
jedi                      0.16.0                   pypi_0    pypi
napari                    0.2.12+40.gca06948          pypi_0    pypi
openssl                   1.1.1f               he774522_0
parso                     0.6.2                    pypi_0    pypi
pip                       20.0.2                   py37_1
python                    3.7.7           h60c2a47_0_cpython
setuptools                46.1.3                   py37_0
sqlite                    3.31.1               he774522_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wheel                     0.34.2                   py37_0
wincertstore              0.2                      py37_0
```



`napari --info` in testenv2 gives the same error as before:

```pytb
(testenv2) C:\Users\Rupp>napari --info
Traceback (most recent call last):
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\site-packages\napari\resources\build_icons.py", line 171, in build_pyqt_resources
    check_call(['pyrcc5', '-o', out_path, qrc_path])
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Rupp\Anaconda3\envs\testenv2\Scripts\napari.exe\__main__.py", line 4, in <module>
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\site-packages\napari\__init__.py", line 50, in <module>
    from .viewer import Viewer
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\site-packages\napari\viewer.py", line 6, in <module>
    from ._qt.qt_update_ui import QtUpdateUI
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\site-packages\napari\_qt\__init__.py", line 5, in <module>
    import_resources()
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\site-packages\napari\resources\__init__.py", line 117, in import_resources
    respath = build_pyqt_resources(fspath(target_file), overwrite=overwrite)
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\site-packages\napari\resources\build_icons.py", line 173, in build_pyqt_resources
    check_call(['pyside2-rcc', '-o', out_path, qrc_path])
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\rupp\anaconda3\envs\testenv2\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by tlambert03** [comment] 2020-04-05 21:22
ok that was helpful.  it looks like, for some reason, your `pip install` is not installing _any_ of the dependencies, it's _only_ installing the requested package.  It's like you have [`--no-deps`](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-no-deps) set as a global pip setting somehow.  can you run `pip config list` or `pip config list -v` to see whether you have something set in pip?

For comparison, when I run the same code I mentioned on a Win10 install, I get the following output for `conda list`:

```
(testenv2) C:\Users\tjl10\python\napari>conda list
# packages in environment at C:\Users\tjl10\miniconda3\envs\testenv2:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
babel                     2.8.0                    pypi_0    pypi
backcall                  0.1.0                    pypi_0    pypi
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
chardet                   3.0.4                    pypi_0    pypi
colorama                  0.4.3                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
dask                      2.14.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
freetype-py               2.1.0.post1              pypi_0    pypi
fsspec                    0.7.1                    pypi_0    pypi
idna                      2.9                      pypi_0    pypi
imageio                   2.8.0                    pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        1.6.0                    pypi_0    pypi
ipykernel                 5.2.0                    pypi_0    pypi
ipython                   7.13.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.16.0                   pypi_0    pypi
jinja2                    2.11.1                   pypi_0    pypi
jupyter-client            5.3.4                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.2.1                    pypi_0    pypi
napari                    0.2.12+40.gca06948          pypi_0    pypi
networkx                  2.4                      pypi_0    pypi
numpy                     1.18.2                   pypi_0    pypi
numpydoc                  0.9.2                    pypi_0    pypi
openssl                   1.1.1f               hfa6e2cd_0    conda-forge
packaging                 20.3                     pypi_0    pypi
parso                     0.6.2                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    7.0.0                    pypi_0    pypi
pip                       20.0.2                     py_2    conda-forge
pluggy                    0.13.1                   pypi_0    pypi
prompt-toolkit            3.0.5                    pypi_0    pypi
pygments                  2.6.1                    pypi_0    pypi
pyopengl                  3.1.5                    pypi_0    pypi
pyparsing                 2.4.6                    pypi_0    pypi
pyside2                   5.14.2                   pypi_0    pypi
python                    3.7.6           h60c2a47_5_cpython    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pywin32                   227                      pypi_0    pypi
pyzmq                     19.0.0                   pypi_0    pypi
qtconsole                 4.7.2                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
requests                  2.23.0                   pypi_0    pypi
scikit-image              0.16.2                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
shiboken2                 5.14.2                   pypi_0    pypi
six                       1.14.0                   pypi_0    pypi
snowballstemmer           2.0.0                    pypi_0    pypi
sphinx                    3.0.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
toolz                     0.10.0                   pypi_0    pypi
tornado                   6.0.4                    pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
urllib3                   1.25.8                   pypi_0    pypi
vc                        14.1                 h869be7e_1    conda-forge
vispy                     0.6.4                    pypi_0    pypi
vs2015_runtime            14.16.27012          h30e32a0_1    conda-forge
wcwidth                   0.1.9                    pypi_0    pypi
wheel                     0.34.2                     py_1    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
zipp                      3.1.0                    pypi_0    pypi
```

**Comment by tlambert03** [comment] 2020-04-05 21:25
also, btw, for multi line code blocks in github comments, use three "```" marks on an empty line before and after your code block :)

**Comment by tlambert03** [comment] 2020-04-05 21:38
alternatively... do you have anything permanently set for your `PYTHONPATH` environment variable? such that pip thinks it's already installed?  `python -c "import sys; print(sys.path)"` might show it.
or you can try the `--ignore-dependencies` trick again to force it to reinstall stuff.

**Comment by katierupp** [comment] 2020-04-05 22:26
Interestingly, `pip config list` and `pip config list -v` did not output anything. It looks like it is possibly only installing the packages that were not located in the base environment? 

I tried running `pip install git+https://github.com/napari/napari.git --ignore-installed` in testenv2 so it would install all of the packages regardless of whether they were in the base enviroment or not and the napari window sucessfully rendered!

`napari --info` gives this now: 
```
(testenv2) C:\Users\Rupp>napari --info
napari: 0.2.12+40.gca06948
Platform: Windows-10-10.0.18362-SP0
Python: 3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)]
Qt: 5.14.2
PySide2: 5.14.2
NumPy: 1.18.2
SciPy: 1.4.1
scikit-image: 0.16.2
Dask: 2.13.0
VisPy: 0.6.4

GL version:  4.5.0 - Build 23.20.16.4973
MAX_TEXTURE_SIZE: 16384

Plugins:  None
```

I will test to make sure I can properly import napari in a Jupyter Notebook, but in the mean time, thank you so much for all of your help and patience (as well as the tip about the multi like code blocks)!

**Comment by tlambert03** [comment] 2020-04-05 23:21
great!  glad we're gradually getting to the bottom of it.  So to summarize, I think your original issue was probably something bad about the base environment.  As a general rule, I would _strongly_ recommend creating a new conda environment anytime you want to play around with something.  basically, protect your base environment aggressively, and _only_ install core libraries that you always use (or even just consider having a seperate "kitchen sink" environment where you can install anything you want to, but always have the option to delete it and start again without reinstalling anaconda).
The second issues seems to be that `pip` was including some other environment (maybe the base) when determining what packages were needed.  I'd still be curious whether you've perhaps added the site-packages folder from your base environment to your [global PYTHONPATH variable](https://docs.microsoft.com/en-us/windows/python/faqs#what-is-pythonpath), which might cause that (you can check it following [these instructions](https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0))

**Comment by katierupp** [comment] 2020-04-06 00:25
Thank you for the advice! Yeah, I hadn't been very careful about maintaining the base environment, but now I see how important it is. I just checked for the PYTHONPATH variable, but it wasn't specified. Here's the output from ` python -c "import sys; print(sys.path)" `

```
['', 'C:\\Users\\Rupp\\Anaconda3\\envs\\napari\\python37.zip', 'C:\\Users\\Rupp\\Anaconda3\\envs\\napari\\DLLs', 'C:\\Users\\Rupp\\Anaconda3\\envs\\napari\\lib', 'C:\\Users\\Rupp\\Anaconda3\\envs\\napari', 'C:\\Users\\Rupp\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\Users\\Rupp\\AppData\\Roaming\\Python\\Python37\\site-packages\\win32', 'C:\\Users\\Rupp\\AppData\\Roaming\\Python\\Python37\\site-packages\\win32\\lib', 'C:\\Users\\Rupp\\AppData\\Roaming\\Python\\Python37\\site-packages\\Pythonwin', 'C:\\Users\\Rupp\\Anaconda3\\envs\\napari\\lib\\site-packages', 'C:\\Users\\Rupp\\Anaconda3\\envs\\napari\\lib\\site-packages\\win32', 'C:\\Users\\Rupp\\Anaconda3\\envs\\napari\\lib\\site-packages\\win32\\lib', 'C:\\Users\\Rupp\\Anaconda3\\envs\\napari\\lib\\site-packages\\Pythonwin']
```

So now the napari window still comes up when I call `napari`, but a lot of warnings pop up along with it. I made a new environment, but for some reason I wasn't able to upgrade PyQt5 past 5.9.2 again (and the versions seemed to have reverted in the testenv2, I dont know why). Heres the output of `napari --info` followed by the error triggered by `napari`.  

I opened an ipython console as well, and napari responds when I load an image, but more warnings come up. 

```
(napari) C:\Users\Rupp>napari --info
c:\users\rupp\anaconda3\lib\site-packages\napari\__init__.py:38: UserWarning:
    napari was tested with QT library `>=5.12.3`.
    The version installed is 5.9.6. Please report any issues with this
    specific QT version at https://github.com/Napari/napari/issues.

  warn(message=warn_message)
napari: 0.2.12+40.gca06948
Platform: Windows-10-10.0.18362-SP0
Python: 3.7.7 (default, Mar 23 2020, 23:19:08) [MSC v.1916 64 bit (AMD64)]
Qt: 5.9.6
PyQt5: 5.9.2
NumPy: 1.18.2
SciPy: 1.4.1
scikit-image: 0.16.2
Dask: 2.13.0
VisPy: 0.6.4

GL version:  4.5.0 - Build 23.20.16.4973
MAX_TEXTURE_SIZE: 16384

Plugins:  None

(napari) C:\Users\Rupp>napari
c:\users\rupp\anaconda3\lib\site-packages\napari\__init__.py:38: UserWarning:
    napari was tested with QT library `>=5.12.3`.
    The version installed is 5.9.6. Please report any issues with this
    specific QT version at https://github.com/Napari/napari/issues.

  warn(message=warn_message)
WARNING: DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="", pointsize=12, pixelsize=16, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-16) dpi=96
WARNING: Cannot open file ':/themes/dark/right_arrow.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/right_arrow.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/right_arrow.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/right_arrow.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/right_arrow.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/right_arrow.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/right_arrow.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/right_arrow.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/delete_shape.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/delete_shape.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/pop_out.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/pop_out.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/new_points.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/new_points.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/new_shapes.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/new_shapes.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/new_labels.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/new_labels.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/delete.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/delete.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/console.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/console.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/roll.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/roll.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/transpose.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/transpose.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/home.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/home.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/3D.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/3D.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/check.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/check.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/grid.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/grid.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/delete_shape.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/delete_shape.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/pop_out.svg', because: No such file or directory
WARNING: Cannot open file ':/themes/dark/pop_out.svg', because: No such file or directory
```

**Comment by katierupp** [comment] 2020-04-06 00:42
No warnings like these occur in a Jupyter notebook, though

**Comment by tlambert03** [comment] 2020-04-06 12:19
> Here's the output from python -c "import sys; print(sys.path)"

the main thing that sticks out there is the `C:\\Users\\Rupp\\AppData\\Roaming\\Python\\Python37\\site-packages` lines that are in your path.  I don't use Windows much so I'm not certain, but I'm wondering whether that might be from a previous python install from, say, python.org rather than anaconda, where you added something to your PATH?  I would look in that folder and see if it has a bunch of folders for napari and its dependencies (napari, dask, numpy, scipy, scikit-image, etc...).  If so, my guess is that's the problem.  When you activate an anaconda environment, ideally, you will only have stuff from `C:\\Users\\Rupp\\Anaconda3\\envs\\napari` on your sys.path.

> I opened an ipython console as well, and napari responds when I load an image, but more warnings come up.

:( I'm sorry... it's so hard to say what's happening, and why you didn't get the same result as you did earlier in `testenv2` without watching exactly what you're doing.

> No warnings like these occur in a Jupyter notebook, though

there shouldn't be anything fundamentally different about running things in a notebook or not, however, depending on how you're starting everything, it's definitely possible that you're using a different environment somehow for your notebook than the command line, and that would explain it.

Do you have anyone local who might be able to sit at your computer with you?  Here are the things I think you need to generally figure out:

- get `AppData\\Roaming\\Python\\Python37\\site-packages` off your PATH.  You might [look in your system variables](https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0) for clues.  But one way or another, you want _only_ the conda environment to be in `sys.path` once you activate it
- I suspect that is the root problem, but until you figure that out, you'll need to use `--ignore-installed` every time you install something in a conda env, and you might even use `--ignore-installed --upgrade`.  You'll know it didn't work if you still get an old version of `Qt` when you run `napari --info`
- use `conda list` to debug frequently.  If it doesn't show a list of packages like mine in https://github.com/napari/napari/issues/1112#issuecomment-609485847, then something has failed.
- treat environments as "disposables" and liberally create new ones to test things if you feel like something has gone wrong

**Comment by sofroniewn** [comment] 2020-11-03 05:34
Sounds like some of these issues ended up being down to a bad environment. @katierupp if you're still having issues please let us know. We've had a number of napari releases since this was made and so things might have improved. If I don't hear anything I will close this issue soon, but it can always be reopened. Thanks!

**Closed as completed** 2020-11-16 16:53 UTC
Labels: bug, topic:installation
