### ISSUE TITLE
Console missed on menu toggle

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1078] opened 2020-03-23 20:36 UTC
## 🐛 Bug

When open console with main menu ort shortcut it fail (only place for it is visible). After trigger console with button everything works.

## To Reproduce

1. Start napari
2. Window > console (or Ctrl+Shift+C)

## Expected behavior

Visible console

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context

@sofroniewn For me it looks like #1055 introduce this.

**Comment by tlambert03** [comment] 2020-03-23 20:46
Thanks, this is a duplicate of https://github.com/napari/napari/issues/1073.  will close to keep it all in one place.

**Closed as completed by tlambert03** 2020-03-23 20:46 UTC
