### ISSUE TITLE
Rectangle Shape sometimes stops being a rectangle while drawing on canvas

### ISSUE THREAD

**Issue by TimMonko** [napari/napari#7343] opened 2024-10-28 04:21 UTC
### 🐛 Bug Report

When trying to draw on a rectangle shape, it will sometimes stop being a rectangle. See the gif below. One of two things happen:

1. The shape becomes a line with 2 points (see gif)
2. The rectangle becomes a parallelogram and dragging the mouse changes both the size and angles of shape. (this was the bug I initially found, but haven't been able to record it in a gif. 

![python_2oNUzxJQPX](https://github.com/user-attachments/assets/ccc445ce-3384-4947-991f-c71cd22a0f73)

### 💡 Steps to Reproduce

1. Add a shapes layer
2. Try to draw on a rectangle shape
3. ??? not sure, very intermittent

### 🌎 Environment

napari: 0.5.4
Platform: Windows-10-10.0.22631-SP0
Python: 3.10.15 | packaged by conda-forge | (main, Sep 30 2024, 17:41:41) [MSC v.1941 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.11
NumPy: 1.26.4
SciPy: 1.14.1
Dask: 2024.9.1
VisPy: 0.14.3
magicgui: 0.9.1
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.3.0
psygnal: 0.11.1
npe2: 0.7.7
pydantic: 2.9.2

OpenGL:
- GL version: 4.6.0 NVIDIA 551.78
- MAX_TEXTURE_SIZE: 32768
- GL_MAX_3D_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 2.0
- screen 2: resolution 1440x2560, scale 1.0

Optional:
- numba: 0.60.0
- triangle: 20230923
- napari-plugin-manager: 0.1.3

Settings path:
- C:\Users\timmo\AppData\Local\napari\ndev-311_38088f5b898b2da4d541680bbce088d4fc867539\settings.yaml

**Comment by DragaDoncila** [comment] 2024-11-06 00:00
Thanks for opening this @TimMonko! That is definitely a bug 😄  @Czaki you've been looking at shapes very closely recently - any ideas about this one?

**Comment by Czaki** [comment] 2024-11-06 08:27
It looks like some deduplication of data (all 4 points in the same position so the middle one are removed. 
But to check this it is required to reproduce bug and check inner structures.

**Comment by Czaki** [comment] 2024-11-26 00:40
@TimMonko Does this problem happen only on your horizontal screen (1920x1080 one)?

**Comment by TimMonko** [comment] 2024-11-26 01:25
> Does this problem happen only on your horizontal screen (1920x1080 one)?

Interesting.... at first I thought that was the case. But further testing has ensured its just as possible on both monitors. Also, I (accidentally) checked on an older install and this occurs on napari 0.5.1 as well. 

I don't know what your hypothesis is yet, but I did change the screen scaling to be 1.0 instead of 2.0 for the horizontal monitor and the problem continues. 

Here is a screenshot to include what it looks like when a parallelogram occurs (and one of the 'lines' below which has an almost triangular vector) 

![image](https://github.com/user-attachments/assets/cca99c57-e655-4328-b813-1208c9fe2b6c)

**Comment by Czaki** [comment] 2024-11-26 07:09
Does this happen on touchpad or with mouse?

**Comment by TimMonko** [comment] 2024-11-27 01:08
Mouse. I have not tested with any other inputs. It does occur on at least 3 different computers that I've tested (all with mouse).

**Comment by psobolewskiPhD** [comment] 2024-12-21 04:11
I spent a buncha time trying to reproduce on 0.5.5 (mac though) and I can't.
Are all 3 of the computers you mention Windows? If so, do you have access to another system to try?
Can you try 0.5.5? It has some issues with shapes too, but at least this bug I can't trigger.

**Comment by TimMonko** [comment] 2024-12-21 04:31
Still occurs on 0.5.5 -- but seemingly even more rare, maybe 1/40th of the time, rather than 1/120th). I've tested on only Windows so far. After the holiday break I can test on other OS. I will also test on my pen tablet after holidays to see if it's just mouse-input related (it's at least not a single problematic mouse).

**Comment by psobolewskiPhD** [comment] 2024-12-21 04:33
Thanks, I will keep trying on my mac whenever i use the Shapes layer.

**Comment by TimMonko** [comment] 2024-12-30 22:35
For what it's worth, I'm unable to reproduce this in a new 0.5.5 environment -- not sure if my previous comment was from a fresh or updated environment, can't remember.

**Comment by psobolewskiPhD** [comment] 2024-12-30 22:45
Ok, let's close this for now and if it appears again we can re-open or make a new issue.

**Closed as completed** 2024-12-30 22:45 UTC
Labels: bug, triage:need to reproduce

**Comment by TimMonko** [comment] 2025-01-03 19:15
Was able to replicate on a Mac today on 0.5.5. It took drawing many many shapes first, and it seems to require (from testing on 0.5.4 where it was more frequent) really fast clicking or rapid mouse movement. I don't think this is something a practical user will ever experience (now in 0.5.5 that other things have been fixed). Not really thinking this needs this needs reopened, but maybe it will be helpful evidence should some other bug be relevant in the future.

I did take the initiative to click on the shape for the first time, and noted there were 4 points. 
![image](https://github.com/user-attachments/assets/3885aee3-1137-4941-9801-472f37e4eb2c)

Clicking the outer ones had nothing happen, but clicking one of these inner two points resulted in the following error message: 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/miniconda3/lib/python3.11/site-packages/superqt/utils/_throttler.py:286, in ThrottledCallable._set_future_result(self=<superqt.utils._throttler.ThrottledCallable object>)
    285 def _set_future_result(self):
--> 286     result = self._func(*self._args[: self._max_args], **self._kwargs)
        self._func = <function _weak_func.<locals>.weak_func at 0x315cf6340>
        self = <superqt.utils._throttler.ThrottledCallable object at 0x312dceb90>
        self._args[: self._max_args] = (<MouseEvent blocked=False button=None buttons=[] delta=[0. 0.] handled=False is_dragging=False last_event=MouseEvent modifiers=() native=<PyQt5.QtGui.QMouseEvent object at 0x31c70c9d0> pos=[648 846] press_event=None source=None sources=[] time=1735931368.913605 type=mouse_move>,)
        self._kwargs = {}
        self._args = (<MouseEvent blocked=False button=None buttons=[] delta=[0. 0.] handled=False is_dragging=False last_event=MouseEvent modifiers=() native=<PyQt5.QtGui.QMouseEvent object at 0x31c70c9d0> pos=[648 846] press_event=None source=None sources=[] time=1735931368.913605 type=mouse_move>,)
        self._max_args = 1
    287     self._future.set_result(result)

File ~/miniconda3/lib/python3.11/site-packages/superqt/utils/_throttler.py:226, in _weak_func.<locals>.weak_func(*args=(<MouseEvent blocked=False button=1 buttons=[1] d...urces=[] time=1735931367.9786417 type=mouse_move>,), **kwargs={})
    224 def weak_func(*args, **kwargs):
    225     if method := weak_method():
--> 226         return method(*args, **kwargs)
        method = <bound method VispyCanvas._on_mouse_move of <napari._vispy.canvas.VispyCanvas object at 0x315915810>>
        args = (<MouseEvent blocked=False button=1 buttons=[1] delta=[0. 0.] handled=False is_dragging=True last_event=MouseEvent modifiers=() native=<PyQt5.QtGui.QMouseEvent object at 0x31c70c9d0> pos=[454 272] press_event=MouseEvent source=None sources=[] time=1735931367.9786417 type=mouse_move>,)
        kwargs = {}
    227     warnings.warn(
    228         "Method has been garbage collected", RuntimeWarning, stacklevel=2
    229     )

File ~/miniconda3/lib/python3.11/site-packages/napari/_vispy/canvas.py:456, in VispyCanvas._on_mouse_move(self=<napari._vispy.canvas.VispyCanvas object>, event=<MouseEvent blocked=False button=1 buttons=[1] d...urces=[] time=1735931367.9786417 type=mouse_move>)
    444 def _on_mouse_move(self, event: MouseEvent) -> None:
    445     """Called whenever mouse moves over canvas.
    446 
    447     Parameters
   (...)
    454     None
    455     """
--> 456     self._process_mouse_event(mouse_move_callbacks, event)
        event = <MouseEvent blocked=False button=1 buttons=[1] delta=[0. 0.] handled=False is_dragging=True last_event=MouseEvent modifiers=() native=<PyQt5.QtGui.QMouseEvent object at 0x31c70c9d0> pos=[454 272] press_event=MouseEvent source=None sources=[] time=1735931367.9786417 type=mouse_move>
        self = <napari._vispy.canvas.VispyCanvas object at 0x315915810>

File ~/miniconda3/lib/python3.11/site-packages/napari/_vispy/canvas.py:417, in VispyCanvas._process_mouse_event(self=<napari._vispy.canvas.VispyCanvas object>, mouse_callbacks=<function mouse_move_callbacks>, event=<ReadOnlyWrapper at 0x346bdc200 for MouseEvent>)
    415 layer = self.viewer.layers.selection.active
    416 if layer is not None:
--> 417     mouse_callbacks(layer, event)
        event = <ReadOnlyWrapper at 0x346bdc200 for MouseEvent at 0x33e7bb850>
        layer = <Shapes layer 'Shapes' at 0x33653a3d0>
        mouse_callbacks = <function mouse_move_callbacks at 0x17e06f240>

File ~/miniconda3/lib/python3.11/site-packages/napari/utils/interactions.py:177, in mouse_move_callbacks(obj=<Shapes layer 'Shapes'>, event=<ReadOnlyWrapper at 0x346bdc200 for MouseEvent>)
    174 obj._persisted_mouse_event[gen].__wrapped__ = event
    175 try:
    176     # try to advance the generator
--> 177     next(gen)
        gen = <generator object select at 0x31012cd50>
    178 except StopIteration:
    179     # If done deleted the generator and stored event
    180     del obj._mouse_drag_gen[func]

File ~/miniconda3/lib/python3.11/site-packages/napari/layers/shapes/_shapes_mouse_bindings.py:106, in select(layer=<Shapes layer 'Shapes'>, event=<ReadOnlyWrapper at 0x346bde1c0 for ReadOnlyWrapper>)
    104     _drag_selection_box(layer, coordinates)
    105 else:
--> 106     _move_active_element_under_cursor(layer, coordinates)
        layer = <Shapes layer 'Shapes' at 0x33653a3d0>
        coordinates = array([ 719.1405 , 1305.13133])
    108 # if a shape is being moved, update the thumbnail
    109 if layer._is_moving:

File ~/miniconda3/lib/python3.11/site-packages/napari/layers/shapes/_shapes_mouse_bindings.py:843, in _move_active_element_under_cursor(layer=<Shapes layer 'Shapes'>, coordinates=array([ 719.1405 , 1305.13133]))
    840     angle = new_angle - fixed_angle
    842 for index in layer.selected_data:
--> 843     layer._data_view.rotate(
        layer = <Shapes layer 'Shapes' at 0x33653a3d0>
        layer._data_view = <napari.layers.shapes._shape_list.ShapeList object at 0x3362d5010>
        index = 51
        layer._fixed_vertex = array([ 719.10735, 1304.76324])
        angle = -84.85389746801259
    844         index, angle, center=layer._fixed_vertex
    845     )
    846 layer._rotate_box(angle, center=layer._fixed_vertex)
    847 layer.refresh()

File ~/miniconda3/lib/python3.11/site-packages/napari/layers/shapes/_shape_list.py:992, in ShapeList.rotate(self=<napari.layers.shapes._shape_list.ShapeList object>, index=51, angle=-84.85389746801259, center=array([ 719.10735, 1304.76324]))
    980 """Performs a rotation on a single shape located at index
    981 
    982 Parameters
   (...)
    989     length 2 list specifying coordinate of center of rotation.
    990 """
    991 self.shapes[index].rotate(angle, center=center)
--> 992 self._update_mesh_vertices(index, edge=True, face=True)
        index = 51
        self = <napari.layers.shapes._shape_list.ShapeList object at 0x3362d5010>

File ~/miniconda3/lib/python3.11/site-packages/napari/layers/shapes/_shape_list.py:30, in _batch_dec.<locals>._wrapped(self=<napari.layers.shapes._shape_list.ShapeList object>, *args=(51,), **kwargs={'edge': True, 'face': True})
     27 @wraps(meth)
     28 def _wrapped(self, *args, **kwargs):
     29     with self.batched_updates():
---> 30         return meth(self, *args, **kwargs)
        meth = <function ShapeList._update_mesh_vertices at 0x30139ab60>
        self = <napari.layers.shapes._shape_list.ShapeList object at 0x3362d5010>
        args = (51,)
        kwargs = {'edge': True, 'face': True}

File ~/miniconda3/lib/python3.11/site-packages/napari/layers/shapes/_shape_list.py:746, in ShapeList._update_mesh_vertices(self=<napari.layers.shapes._shape_list.ShapeList object>, index=51, edge=True, face=True)
    744 if edge:
    745     indices = np.all(self._mesh.vertices_index == [index, 1], axis=1)
--> 746     self._mesh.vertices[indices] = (
        indices = array([False, False, ...,  True,  True])
        self = <napari.layers.shapes._shape_list.ShapeList object at 0x3362d5010>
        self._mesh.vertices = array([[ 375.30848,  600.61647],
       [ 375.30848,  904.33768],
       ...,
       [ 664.75332, 1279.37472],
       [ 664.97973, 1278.37472]])
        self._mesh = <napari.layers.shapes._mesh.Mesh object at 0x321d22150>
        shape = <napari.layers.shapes._shapes_models.rectangle.Rectangle object at 0x33dfcf910>
        shape._edge_vertices = array([[ 728.3219 , 1245.37153],
       [ 728.3219 , 1245.37153],
       ...,
       [ 728.3219 , 1245.37153],
       [ 728.3219 , 1245.37153]])
        shape._edge_offsets = array([[nan, nan],
       [nan, nan],
       ...,
       [nan, nan],
       [nan, nan]], dtype=float32)
    747         shape._edge_vertices + shape.edge_width * shape._edge_offsets
    748     )
    749     self._mesh.vertices_centers[indices] = shape._edge_vertices
    750     self._mesh.vertices_offsets[indices] = shape._edge_offsets

ValueError: shape mismatch: value array of shape (9,2) could not be broadcast to indexing result of shape (10,2)
```

**Comment by TimMonko** [comment] 2025-01-03 19:18
Tried playing with the points or moving the shape, but was unable to. Deselecting and reselecting led the shape points to look like this 
![image](https://github.com/user-attachments/assets/830d0f1e-d1dd-4768-9ba8-11ecdb29e22d)

But the vertexes are like this
![image](https://github.com/user-attachments/assets/bb094286-29fb-43ae-857a-0dfcecbde362)
