### ISSUE TITLE
QtLayerListModel fails to initialize with PySide6

### ISSUE THREAD

**Issue by n-poulsen** [napari/napari#6061] opened 2023-07-14 13:16 UTC
## 🐛 Bug

Cannot launch `napari` with PySide6 6.5.1

## To Reproduce

1. Launch napari: `napari`

Stack trace
```
Traceback (most recent call last):
  File "/miniconda/envs/napari-test/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/miniconda/envs/napari-test/lib/python3.10/site-packages/napari/__main__.py", line 564, in main
    _run()
  File "/miniconda/envs/napari-test/lib/python3.10/site-packages/napari/__main__.py", line 326, in _run
    viewer = Viewer()
  File "/miniconda/envs/napari-test/lib/python3.10/site-packages/napari/viewer.py", line 67, in __init__
    self._window = Window(self, show=show)
  File "/miniconda/envs/napari-test/lib/python3.10/site-packages/napari/_qt/qt_main_window.py", line 577, in __init__
    self._qt_viewer.dockLayerList, tabify=False, menu=self.window_menu
  File "/miniconda/envs/napari-test/lib/python3.10/site-packages/napari/_qt/qt_viewer.py", line 356, in dockLayerList
    layerListLayout.addWidget(self.layers)
  File "/miniconda/envs/napari-test/lib/python3.10/site-packages/napari/_qt/qt_viewer.py", line 334, in layers
    self._layers = QtLayerList(self.viewer.layers)
  File "/miniconda/envs/napari-test/lib/python3.10/site-packages/napari/_qt/containers/qt_layer_list.py", line 46, in __init__
    super().__init__(root, parent)
  File "/miniconda/envs/napari-test/lib/python3.10/site-packages/napari/_qt/containers/qt_list_view.py", line 43, in __init__
    self.setRoot(root)
  File "/miniconda/envs/napari-test/lib/python3.10/site-packages/napari/_qt/containers/_base_item_view.py", line 87, in setRoot
    self.setModel(create_model(root, self))
  File "/miniconda/envs/napari-test/lib/python3.10/site-packages/napari/_qt/containers/_factory.py", line 72, in create_model
    return QtLayerListModel(obj, parent=parent)
  File "/miniconda/envs/napari-test/lib/python3.10/site-packages/napari/_qt/containers/_base_item_model.py", line 80, in __init__
    super().__init__(parent=parent)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

## Expected behavior

A `napari` window should open

## Environment

`napari info`
```
napari: 0.4.18
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ]
Qt: 6.5.1
PySide6: 
NumPy: 1.25.1
SciPy: 1.11.1
Dask: 2023.7.0
VisPy: 0.12.2
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.8
app-model: 0.2.0
npe2: 0.7.0

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1470x956, scale 2.0
  - screen 2: resolution 2560x1440, scale 1.0

Settings path:
  - /Users/niels/Library/Application Support/napari/napari-test_9ea46387e0ff32ad5c07a9465f45736e9e2608f4/settings.yaml
Plugins:
  - napari: 0.4.18 (77 contributions)
  - napari-console: 0.0.8 (0 contributions)
  - napari-deeplabcut: 0.1.3.dev29+gbd53843 (16 contributions)
  - napari-svg: 0.1.10 (2 contributions)
```

**Comment by Czaki** [comment] 2023-07-14 13:20
Ouch... 
I totally forgot about pin Pyside6 version in dependencies. Here is a list of PySide6 with known incompatibilities. 
https://github.com/napari/napari/blob/9bea15e7b89156654ae02c3dc3144d6fc244aab3/resources/constraints/version_denylist.txt#L3

**Comment by n-poulsen** [comment] 2023-07-14 13:28
Thanks for the info!

**Comment by Czaki** [comment] 2023-07-14 13:32
In general, the problem comes from breaking change in PySide6 with calling the constructor of the superclass. Here original discussion: https://github.com/pyapp-kit/app-model/issues/93

**Comment by psobolewskiPhD** [comment] 2023-07-15 01:38
Thanks for reporting, this is a duplicate of https://github.com/napari/napari/issues/5703
We have an idea for solving this issue, but also face another pyside6 issue: https://github.com/napari/napari/issues/5657

Overall, our support for Qt6 is experimental, but PyQt6 is a better way to go it you need Qt6.

**Closed as completed by psobolewskiPhD** 2023-07-15 01:38 UTC
Labels: bug, triage:duplicate
