### ISSUE TITLE
Incompatibility of python 3.8 with napari on Windows

### ISSUE THREAD

**Issue by yashika51** [napari/napari#1084] opened 2020-03-25 12:36 UTC
## 🐛 Bug

Error in Installing napari on windows with the Python version 3.8 using anaconda prompt

## To Reproduce

1. Open anaconda prompt
2. Create virtual environment making sure python version==3.8 or higher
3. pip install git+https://github.com/napari/napari
You will get an error.

ERROR: Command errored out with exit status 1:
   command: 'c:\users\yashika sharma\appdata\local\programs\python\python38\python.exe' 'c:\users\yashika sharma\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Yashika Sharma\AppData\Local\Temp\pip-build-env-p_z_5_b6\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel 'setuptools>=30.3.0' setuptools_scm setuptools_scm_git_archive 'Cython>=0.29.2' 'numpy; python_version=='"'"'2.7'"'"'' 'numpy==1.13.3; python_version=='"'"'3.5'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"''
       cwd: None
  Complete output (22 lines):
  Ignoring numpy: markers 'python_version == "2.7"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.5"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
  Collecting wheel
    Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)
  Collecting setuptools>=30.3.0
    Using cached setuptools-46.1.1-py3-none-any.whl (582 kB)
  Collecting setuptools_scm
    Using cached setuptools_scm-3.5.0-py2.py3-none-any.whl (26 kB)
  Collecting setuptools_scm_git_archive
    Using cached setuptools_scm_git_archive-1.1-py2.py3-none-any.whl (3.3 kB)
  Collecting Cython>=0.29.2
    Downloading Cython-0.29.16-cp38-cp38-win_amd64.whl (1.7 MB)
  Collecting numpy==1.14.5
    Using cached numpy-1.14.5.zip (4.9 MB)
  Installing collected packages: wheel, setuptools, setuptools-scm, setuptools-scm-git-archive, Cython, numpy
      Running setup.py install for numpy: started
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: finished with status 'done'
  ERROR: Could not install packages due to an EnvironmentError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:'

  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\yashika sharma\appdata\local\programs\python\python38\python.exe' 'c:\users\yashika sharma\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Yashika Sharma\AppData\Local\Temp\pip-build-env-p_z_5_b6\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel 'setuptools>=30.3.0' setuptools_scm setuptools_scm_git_archive 'Cython>=0.29.2' 'numpy; python_version=='"'"'2.7'"'"'' 'numpy==1.13.3; python_version=='"'"'3.5'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"'' Check the logs for full command output.

## Expected behavior

I expected this to install napari on my system since the readme of the repository mentions python 3.8 works. But on windows, napari cannot install with this version. I tried on two different window systems and got the same error.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:
python_version=='"'"'3.5'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"''
3.8 is not mentioned here. After this I tried both versions 3.7 and 3.6 which worked.

**Comment by tlambert03** [comment] 2020-03-25 12:51
Hi @yashika51, 
I'm unable to reproduce this error.  On my windows10 computer, with a fresh python 3.8 conda env running `pip install git+https://github.com/napari/napari` works fine.  It looks like you're having an issues installing numpy.  one thing I notice is that it's using a relatively old cached version of numpy (1.14.5) and it's trying to compile the source rather than using a wheel, so you might try using `pip install --no-cache-dir`.  Second, the error you're getting looks a lot like [this one](https://github.com/numpy/numpy/issues/11451) reported at numpy when there are spaces in the installation path.

**Comment by yashika51** [comment] 2020-03-26 11:42
Hi, Thank you so much for your reply, the issue solved on my system but my friend is trying to use python 3.8.2 and getting error. We are figuring that out.
Also, my session was crashing in Jupyter notebook while using the %gui qt5, after searching I found the solution here https://github.com/napari/napari/blob/master/examples/notebook.ipynb.
This command should come before 'import' statements. (Mentioning this if someone else is getting same error). Now it works fine.

**Comment by tlambert03** [comment] 2020-03-26 11:59
glad it helped.  I'm going to close this issue for now, but please encourage your friend to open another issue (or comment on this one) if they need help.

**Closed as completed by tlambert03** 2020-03-26 11:59 UTC
Labels: bug
