### ISSUE TITLE
napari crash after numpy RuntimeWarning in worker_thread

### ISSUE THREAD

**Issue by sommerc** [napari/napari#2598] opened 2021-04-22 13:38 UTC
## 🐛 Bug

Hi,

I get a weird napari crash/GUI freeze when using a "thread_worker" in a napari plug-in. The crash happens when numpy throws a warning in a threaded function call. I wonder if somebody can reproduce this.

After the numpy warning appears, there's another Qt threading related warning:

```
c:\users\csommer\anaconda3\envs\napari\lib\site-packages\numpy\core\fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.!
WARNING: QObject::setParent: Cannot set parent, new parent is in a different thread
15:17:03 WARNING QObject::setParent: Cannot set parent, new parent is in a different thread
```

The napari GUI freezes and has to be killed.

## To Reproduce

Here's a minimal example. I simply use `numpy.mean([])` to trigger a "Mean of empty slice!" warning.

```python
import numpy as np
from qtpy.QtWidgets import QWidget
from napari_plugin_engine import napari_hook_implementation

@napari_hook_implementation(specname="napari_experimental_provide_dock_widget")
def test_widget():
    return (TestDock, {"area": "right"})

class TestDock(QWidget):
    def __init__(self, napari_viewer):
        self.viewer = napari_viewer
        super().__init__()

        from napari.qt.threading import thread_worker # delayed import

        @thread_worker
        def blocking(arg):
            result = np.mean(arg)

            return result

        def callback(result):
            print(result)

        worker = blocking([1, 2, 3])
        worker.returned.connect(callback)
        worker.start()
        ### prints 2.0, all fine

        worker = blocking([])
        worker.returned.connect(callback)
        worker.start()
        ### prints warnings (numpy, Qt) + crash
        
```

## Environment

(also happens with recent napari master and numpy==1.20.2)

napari: 0.4.7
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:08) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.19.5
SciPy: 1.6.2
Dask: 2021.04.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 461.92
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1080, scale 2.0

Plugins:
- PartSeg Analysis project: 0.13.2
- PartSeg Image: 0.13.2
- PartSeg Mask project save: 0.13.2
- PartSeg Mask project: 0.13.2
- PartSeg Masked Tiff: 0.13.2
- TEST: 0.0.1
- cellfinder-napari: 0.0.2
- console: 0.0.3
- itk-elastix_napari: 0.1.2
- svg: 0.1.4

**Comment by tlambert03** [comment] 2021-04-22 13:49
Hi,

may I ask what you're attempting to simulate by immediately overriding the worker object with a new worker?  I think this is likely due to the fact that you're clobering the `worker` variable, which will cause garbage collection of that thread worker and  may be the source of your error.  If you name the second worker something like worker2 does it work?

**Comment by tlambert03** [comment] 2021-04-22 13:53
just tested this... and if I change the last three lines to:
```python
        worker2 = blocking([])
        worker2.returned.connect(callback)
        worker2.start()
```
then it doesn't crash and I see the expected warning output:

```
/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3419: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
2.0
nan
```

so one solution might just be to make sure the worker doesn't immediately go out of scope (for instance, by keeping an internal set of workers if you want to spawn multiples immediately like that)

**Comment by sommerc** [comment] 2021-04-22 13:55
> may I ask what you're attempting to simulate by immediately overriding the worker object with a new worker?

That was just for illustration. For me it crashes, whenever numpy throws a warning, in a single worker instance.

Seems to be related to my installation/environment then...

**Comment by tlambert03** [comment] 2021-04-22 13:58
I see, so with a single worker instance, you're still getting that error?  I'll try to see if I can reproduce on windows

**Comment by sommerc** [comment] 2021-04-22 14:00
> so with a single worker instance, you're still getting that error?

Excactly. And it happens only when a numpy warning is thrown.

**Comment by tlambert03** [comment] 2021-04-22 14:55
huh, weird.  I was able to reproduce it once on windows... but afterwards, every time I run it I now get the expected output 🤔   will keep investigating

**Comment by psobolewskiPhD** [comment] 2024-11-09 18:37
I'm not able to reproduce on macOS, main (0.5.5dev). I get print of 2.0 and then `nan` which seems correct. I'm going to close due to this being very old. If this is still occurring then feel free to re-open or make a new, updated issue.

**Closed as completed by psobolewskiPhD** 2024-11-09 18:37 UTC
Labels: bug
