### ISSUE TITLE
Incorrect clipping at bottom edge of pyramid

### ISSUE THREAD

**Issue by jni** [napari/napari#458] opened 2019-07-31 08:28 UTC
## 🐛 Bug

(Sorry, no gif right now, will produce if you can't reproduce it.)

When I run `examples/add_pyramid.py`, if I zoom near the very bottom of the image, the image is cut off inside the viewport. This happens right at the very beginning of a level change. (ie when I go from 2 to 1, or 1 to 0.)

**Comment by sofroniewn** [comment] 2019-08-21 14:29
fixed in #485

**Comment by jni** [comment] 2019-10-07 06:23
@sofroniewn still seeing this on master on Linux... =\

**Comment by sofroniewn** [comment] 2020-01-23 16:19
Note this example here https://forum.image.sc/t/efficiently-open-qptiff-images-with-napari/33237/4?u=sofroniewn

> However, I’m now facing a weird problem. Napari opens with only the top left quarter of the image:

Some of this could be caused by their canvas being larger than we expect (say fullscreen mode on a big monitor). Right now we hard code this max tile shape https://github.com/napari/napari/blob/master/napari/layers/image/image.py#L136 which is currently in the model, but as has been pointed out by @d-v-b maybe this should be living in more of the view code and should be dependent on the canvas size, something which only the view knows ...

**Closed as completed** 2020-04-17 05:37 UTC
Labels: bug
