### ISSUE TITLE
magic name appears to be broken for tracks layer

### ISSUE THREAD

**Issue by jni** [napari/napari#1968] opened 2020-11-30 13:06 UTC
## 🐛 Bug

That's all I have time for for now. =P

**Comment by andy-sweet** [comment] 2022-06-07 15:51
@jni : I'm not sure what magic name means here.

My guess is that is meant an automatic name assigned to a tracks layer after calling `Viewer.add_tracks` without a `name` argument? Which seems to be controlled by the [`magic_name`](https://cs.github.com/napari/napari/blob/2dc5aa659f875c353bfbde3b20d8f07a664ed8a8/napari/utils/naming.py#L135) function. 

But that works for me at v0.4.2 and on main now (5c10022337601f350ad64ce56eddf6664306e40e). In both cases, I tested that by running `python examples/tracks_2d.py` and then running `viewer.add_tracks(viewer.layers[-1].data)` in the console.

If you can remember any more context here or a way to reproduce, please add it. Otherwise, I think we should consider closing this.

**Comment by psobolewskiPhD** [comment] 2024-07-28 02:42
@jni any idea what you the bug was here? Or can we close?

**Comment by andy-sweet** [comment] 2024-07-29 15:50
I'm in a closing mood, so I'm just going to go ahead and close this because it's been open for so long without a way to reproduce or more information.

**Closed as completed by andy-sweet** 2024-07-29 15:50 UTC
Labels: bug, triage:probably solved

**Comment by jni** [comment] 2024-07-30 07:22
Oh! Sorry, the issue here was almost certainly one I've now run into many times, and it gets me every time 😂: if the input data is not *the exact object* that ends up being `layer.data`, then the magic name fails. This happens in any of:
- the input data is a dask array or a list or something that needs to be converted to a NumPy array
- the input data is sliced: `viewer.add_tracks(arr[:, :4])`
- the input data needs to be internally processed in some other way, e.g. `self._data = data[np.argsort(data[:, 0])]`.

I don't think that there is much way to fix that barring absurd levels of dark magic. (e.g. examining the ast 😂) So, closing is fine.
