### ISSUE TITLE
unset NAPARI_OCTREE no longer works

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2863] opened 2021-06-09 23:39 UTC
## 🐛 Bug

Not sure if we should just begin dropping the NAPARI_OCTREE env variable, but now that we have the settings remembering the tiled rendering case, if you do `export NAPARI_OCTREE=1` from the command line it will turn on the tiled rendering setting, which gets saved. If you then do `unset NAPARI_OCTREE` the env variable gets cleared, but you still have the setting, so you have to go into the GUI and clear this too.

That might be ok, but we might want to add this to our documentation somewhere so people don't get confused. Curious what @ppwadhwa and @goanpeca think is best here, and if the behaviour is actually happening as I suggest.

**Comment by goanpeca** [comment] 2021-06-10 00:34
That is odd since env variables should not be saved.

Does the same happen with theme (an easy one to test with)?

**Comment by ppwadhwa** [comment] 2021-06-10 01:06
I just reproduced the bug.  I tried both the octree setting and I also tested with theme.  If you set something in the environment, it will overwrite the setting and disable the widget.  It is weird, because I am fairly certain I had tested that the setting was not overwritten before and I don't remember seeing this behavior.  I am wondering if #2848 affected this?

**Comment by ppwadhwa** [comment] 2021-06-10 01:13
So, I just reverted a bit of code that was changed in #2848, and the settings are not overwritten when setting environment variables.  So, this bug does seem to have been introduced with #2848.

**Comment by sofroniewn** [comment] 2021-06-10 19:06
Nice detective work @ppwadhwa, do you see how to fix? I think it can also wait till next release if it turns out to be tricky

**Comment by ppwadhwa** [comment] 2021-06-10 19:23
@sofroniewn I didn't immediately see how to fix it, but I can look more soon.

**Comment by goanpeca** [comment] 2021-06-10 19:24
I don't think it should hold RC. I can take a look at it @sofroniewn :) 

Thanks for tracking the source @ppwadhwa !

**Comment by Carreau** [comment] 2021-06-11 16:03
Hum, my guess is that when set with the env variable it is seen by the code that remove the default as having been modified, and hence it saves it.

That seem coherent as if I set the env variable I immediately get 
```
experimental:
  octree: true
```
in my setting file.

**Comment by goanpeca** [comment] 2021-06-11 16:16
Working on a fix for this.

**Comment by Carreau** [comment] 2021-06-11 16:49
I can reproduce with pre- #2848 so I doubt this is due to it. 

if you set NAPARI_OCTREE to 1 then start napari

```
experimental:
  octree: true
```

is stored in the settings anyways and because of 

```
        @classmethod
        def customise_sources(
            cls,
            init_settings: SettingsSourceCallable,
            env_settings: SettingsSourceCallable,
            file_secret_settings: SettingsSourceCallable,
        ):
            cls._env_settings = env_settings
            return (
                init_settings,
                env_settings,
                yaml_config_settings_source,
                file_secret_settings,
            )
```

Yaml config then takes precedence. 

I'm also concern that this also affects things that might be in file_secret_settings, and that if someone write something in their secrets file, then it might get propagated to their normal YML settings file. Though I don't see anything in napari about secrets, though maybe in a plugin ?

**Closed as completed** 2021-06-14 18:26 UTC
Labels: bug, documentation
