### ISSUE TITLE
Napari windows resizes out of screen in case `layer.features` contains many columns

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#5417] opened 2022-12-17 17:28 UTC
## 🐛 Bug

When `layer.features` contains a wide table and a user hovers over the labels layer, the Napari window resizes out of screen. I presume it has something to do with the status text field on the bottom of the window showing label properties.

## To Reproduce

1. Run this code:
```
import numpy as np
import napari
import pandas

viewer = napari.Viewer()

viewer.add_image(np.asarray([[1,2],[2,2]]))
labels_layer = viewer.add_labels(np.asarray([[1,2],[3,3]]))

labels_layer.features = {
    "label": [1, 2, 3],
    "very_wide_column_name_1": [1/3, 1/3, 1/3],
    "very_wide_column_name_2": [1/3, 1/3, 1/3],
    "very_wide_column_name_3": [1/3, 1/3, 1/3],
    "very_wide_column_name_4": [1/3, 1/3, 1/3],
    "very_wide_column_name_5": [1/3, 1/3, 1/3],
    "very_wide_column_name_6": [1/3, 1/3, 1/3],
    "very_wide_column_name_7": [1/3, 1/3, 1/3],
    "very_wide_column_name_8": [1/3, 1/3, 1/3],
    "very_wide_column_name_9": [1/3, 1/3, 1/3],
}
```
3. Afterwards, hover with your mouse over a label in the image.
4. Napari's screen window size will become very wide and the image jumps out of screen:

https://user-images.githubusercontent.com/12660498/208253942-fa83204e-f0cd-49a8-a14b-815b9216911d.mp4

## Expected behavior

Napari's window size does not change when the user hovers with their mouse over the label image.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.17
Platform: Windows-10-10.0.19045-SP0
Python: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:41:22) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.23.5
SciPy: 1.9.3
Dask: 2022.12.1
VisPy: 0.11.0
magicgui: 0.6.1
superqt: unknown
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.1

OpenGL:
- GL version: 4.6.14802 Compatibility Profile Context 21.40.18.19 30.0.14018.19001
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

```

 - Any other relevant information:

I'm running on Windows 10

## Workaround:

```
mamba install napari=0.4.15 -c conda-forge
```

**Comment by haesleinhuepf** [comment] 2022-12-17 17:33
Addendum: Sometimes, this warning is printed out confirming that a resize event is the issue here:

WARNING: QWindowsWindow::setGeometry: Unable to set geometry 2654x698+1309+366 (frame: 2670x737+1301+335) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1924x698+1309+366 (frame: 1940x737+1301+335) margins: 8, 31, 8, 8 minimum size: 374x557 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=390,596 maxtrack=0,0)

**Comment by haesleinhuepf** [comment] 2022-12-17 17:50
One more workaround using [napari-skimage-regionprops 0.5.7](https://github.com/haesleinhuepf/napari-skimage-regionprops/releases/tag/0.5.7):

```
from napari_skimage_regionprops import add_table
add_table(labels_layer, viewer)
```

**Comment by Czaki** [comment] 2022-12-18 20:45
@haesleinhuepf It looks like there is a problem with the outdated superqt version. Could you install the latest superqt and check if the error is still present?

**Comment by haesleinhuepf** [comment] 2022-12-19 15:28
The [latest version of superqt](https://anaconda.org/conda-forge/superqt) appears to be 0.4.1 which I have installed.

**Comment by brisvag** [comment] 2022-12-20 16:20
Duplicate of #5177.

**Comment by Czaki** [comment] 2022-12-21 21:22
> The [latest version of superqt](https://anaconda.org/conda-forge/superqt) appears to be 0.4.1 which I have installed.

You are right. The issue is here https://github.com/pyapp-kit/superqt/issues/148

**Closed as completed** 2023-01-24 19:58 UTC
Labels: bug
