### ISSUE TITLE
3D rendering incoherences

### ISSUE THREAD

**Issue by cnstt** [napari/napari#4801] opened 2022-07-11 16:24 UTC
## 🐛 Bug

When enabling 3d view with several layers, I have detected incoherences.

## To Reproduce

1. Have a labels layer at 0.33 opacity
2. On top have another labels layer with 1 opacity
3. On top add an image layer with 1 opacity (in white on the screenshot)
4. When tilting in 3d view, and the bottom most labelmap overlaps the others in the perspective, the brown suddenly appears white. Something isn't coherent in this rendering ^^

![image](https://user-images.githubusercontent.com/104427648/178310895-43e30c48-832f-4ee1-b097-65c1fea325c8.png)

## Expected behavior

The rendering should be coherent: either only display brown or white (because the labelmap on top has roughly the same locations as the white image layer)!

## Environment

napari: 0.4.16
Platform: Linux-5.18.7-100.fc35.x86_64-x86_64-with-glibc2.34
System: Fedora Linux 35 (Workstation Edition)
Python: 3.9.13 (main, Jun 9 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.22.4
SciPy: 1.7.3
Dask: 2022.05.2
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 NVIDIA 515.48.07
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.4
- napari-deepfinder: 0.0.1
- napari-em-reader: 0.1.0
- napari-svg: 0.1.6
- scikit-image: 0.4.16

**Comment by psobolewskiPhD** [comment] 2024-03-06 21:40
Eeep, this one fell through the cracks.
I'm trying to reproduce based on the description with no luck
![image](https://github.com/napari/napari/assets/76622105/31d65d91-f437-4f3f-9ce9-eec75d1aeec3)

Do you have a script maybe or more advice?
It might be solved with all the labels changes in 0.4.19

**Comment by GenevieveBuckley** [comment] 2024-03-07 05:41
I can't reproduce it either.
Possibly I am not doing *exactly* the same thing, but hopefully it is that more recent changes have fixed the problem.

**Comment by psobolewskiPhD** [comment] 2024-07-28 19:23
I'm going to close this as probably solved. If this is still happening, please provide more details so we can try to sort it out.

**Closed as completed by psobolewskiPhD** 2024-07-28 19:23 UTC
Labels: bug, triage:need to reproduce, triage:probably solved
