### ISSUE TITLE
Napari 0.4.18.rc3 Stardist plugin error

### ISSUE THREAD

**Issue by AwolnyNencki** [napari/napari#6030] opened 2023-07-03 13:40 UTC
## To Reproduce

1. When I am trying to run Stradist plugin this erros shows up:

module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by jni** [comment] 2023-07-03 14:11
@AwolnyNencki the phrase `np.object` or `numpy.object` does not appear anywhere in the napari code base, so I presume this is a stardist issue. Having said that, stardist *also* does not include that phrase anywhere, so I don't know exactly where the error is coming from.

Since I'm fairly confident this is not a napari issue, I am going to close it, but if you want help troubleshooting please feel free to continue the conversation here! To help you effectively we would need you to share more information:

- version of numpy
- version of stardist
- version of napari-stardist

(☝️ all of the above will be provided by the `napari --info` command)

We also need the full error message, and, ideally, detailed steps to reproduce the problem, e.g. an image that we can load, and exactly at what point of running stardist the error happens.

**Closed as completed by jni** 2023-07-03 14:11 UTC
Labels: bug
