### ISSUE TITLE
horizontal/vertical shapes scaling does not work

### ISSUE THREAD

**Issue by tdmorello** [napari/napari#3977] opened 2022-01-18 19:02 UTC
## 🐛 Bug

After drawing a shape on a shapes layer there are markers/anchors to grab and scale the shape. The markers at the corners, appropriately change the size of the shape,  but the markers on the tops and sides (scaling constrained to vertical and horizontal) do not work.

## To Reproduce

1. Draw a shape on a shapes layer.
2. Click and drag an anchor to scale vertically or horizontally

## Expected behavior

Shape size changes.

## Environment

napari: 0.4.13
Platform: macOS-12.1-x86_64-i386-64bit
System: MacOS 12.1
Python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 20:33:18) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.22.1
SciPy: 1.7.3
Dask: 2022.01.0
VisPy: 0.9.4

OpenGL:
- GL version: 2.1 INTEL-18.3.5
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0

Plugins:
- aicsimageio-in-memory: 0.4.1
- aicsimageio-out-of-memory: 0.4.1
- clEsperanto: 0.12.0
- console: 0.0.4
- napari-crop: 0.1.5
- napari-ome-zarr: 0.3.2
- napari-time-slicer: 0.4.2
- napari-tools-menu: 0.1.10
- napari_skimage_regionprops1: 0.2.9
- napari_skimage_regionprops2: 0.2.9
- ome-types: 0.2.10
- scikit-image: 0.4.13
- svg: 0.1.6

**Comment by psobolewskiPhD** [comment] 2022-01-18 19:48
That's wierd, cause it works for polygons, but not rectangles (also on 0.4.13).
BTW: am I the only one ('cause of arm64?) that gets the divide by zero on making a new  (empty) shapes layer? https://github.com/napari/napari/issues/3568
@tdmorello you're also on 0.4.13, also on macOS 12.1, same vispy... you're env looks identical to mine:
```
napari: 0.4.13
Platform: macOS-12.1-arm64-arm-64bit
System: MacOS 12.1
Python: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:07) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.22.0
SciPy: 1.7.3
Dask: 2022.01.0
VisPy: 0.9.4

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.13
- svg: 0.1.5


```

Just I'm -arm64. Do you get that warning?

**Comment by tdmorello** [comment] 2022-01-27 14:39
@psobolewskiPhD  Hmm I'm not getting any errors on creating a new shapes layer but I'm on an intel processor.

**Comment by andy-sweet** [comment] 2022-05-19 20:49
I temporarily checked out v0.4.13 and reproduced this issue: the horizontal/vertical only scaling control points do not work for rectangles and maybe some other shapes, though they do work for polygons. I found the same behavior for the latest release (v0.4.15), but it seems to be fixed on the main branch.

I also think this is effectively a duplicate of #4262, so I'm assuming the same fix for that fixed this too. Will close this issue after closing that issue.

**Comment by andy-sweet** [comment] 2022-05-19 20:52
Actually, I'm feeling pretty confident that #4291 fixes this so I'm closing. @tdmorello : if `main` or v0.4.16 (once it releases) does not work for you, feel free to reopen this issue.

**Closed as completed by andy-sweet** 2022-05-19 20:52 UTC
Labels: bug
