### ISSUE TITLE
Unsupported types for keyboard (python 3.10)

### ISSUE THREAD

**Issue by tischi** [napari/napari#3741] opened 2021-12-03 14:48 UTC
## 🐛 Bug

<img width="752" alt="image" src="https://user-images.githubusercontent.com/2157566/144619202-b50afa72-b937-4f33-a3ed-7483f3430311.png">

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/anaconda3/envs/napari-plugin-dev/lib/python3.10/site-packages/vispy/app/backends/_qt.py in mouseMoveEvent(self=, ev=)
    533             native=ev,
    534             pos=_get_event_xy(ev),
--> 535             modifiers=self._modifiers(ev),
        global modifiers = undefined
        self._modifiers = >
        ev = 
    536         )
    537 

/anaconda3/envs/napari-plugin-dev/lib/python3.10/site-packages/vispy/app/backends/_qt.py in _modifiers(self=, event=)
    625                      [qt_keyboard_modifiers.AltModifier, keys.ALT],
    626                      [qt_keyboard_modifiers.MetaModifier, keys.META]):
--> 627             if q & qtmod:
        q = 33554432
        qtmod = 
    628                 mod += (v,)
    629         return mod

TypeError: unsupported operand type(s) for &: 'KeyboardModifier' and 'KeyboardModifiers'
```
## To Reproduce

1. `conda install -c conda-forge napari`
2. `napari`
3. `File > Open Sample > skiimage > Clock`
4. Hover over image

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

`Mac OS 10.14.6`

The napari info did unfortunately not work (probably due to above bug).

## Additional context

In the same folder where I started Napari, I also started developing a napari plugin and did `pip install -e .`

```
(napari-plugin-dev) tischer@mac-almf13 my-first-napari-plugin (main) $ ls
total 64
drwxr-xr-x  14 tischer  staff   448B Dec  3 15:07 ./
drwxr-xr-x   3 tischer  staff    96B Dec  3 15:20 ../
drwxr-xr-x  12 tischer  staff   384B Dec  3 15:07 .git/
drwxr-xr-x   3 tischer  staff    96B Dec  3 15:07 .github/
-rw-r--r--   1 tischer  staff   993B Dec  3 15:07 .gitignore
drwxr-xr-x   3 tischer  staff    96B Dec  3 15:07 .napari/
-rw-r--r--   1 tischer  staff   1.5K Dec  3 15:07 LICENSE
-rw-r--r--   1 tischer  staff   121B Dec  3 15:07 MANIFEST.in
-rw-r--r--   1 tischer  staff   2.7K Dec  3 15:07 README.md
-rw-r--r--   1 tischer  staff   193B Dec  3 15:07 requirements.txt
-rw-r--r--   1 tischer  staff   1.4K Dec  3 15:07 setup.cfg
-rw-r--r--   1 tischer  staff    84B Dec  3 15:07 setup.py
drwxr-xr-x   4 tischer  staff   128B Dec  3 15:22 src/
-rw-r--r--   1 tischer  staff   860B Dec  3 15:07 tox.ini
```

**Comment by tlambert03** [comment] 2021-12-03 19:18
looks like you ended up with python 3.10 ... which (while we [recently added support for it](https://github.com/napari/napari/pull/3702)) probably still has shoddy general support for Qt related things.  
try specifying a python version:

`conda install -c conda-forge python=3.9 napari`

**Comment by dalthviz** [comment] 2022-12-27 17:45
Hi, just in case, maybe this was already fixed over the vispy side at https://github.com/vispy/vispy/pull/2293

**Comment by psobolewskiPhD** [comment] 2022-12-27 18:02
Thanks for the bump @dalthviz 
I can't reproduce the issue on my mac and python 3.10:
`mamba create -n nap-test -c conda-forge python=3.10 napari`
```
napari: 0.4.17
Platform: macOS-13.1-arm64-arm-64bit
System: MacOS 13.1
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.0
SciPy: 1.9.3
Dask: 2022.12.1
VisPy: 0.11.0
magicgui: 0.6.1
superqt: unknown
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.1

OpenGL:
- GL version: 2.1 Metal - 83
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

```

I think we can close this.

**Closed as completed** 2023-05-02 20:14 UTC
Labels: bug
