### ISSUE TITLE
48-bit RGB (3-channel uint16 support and hela-cells.tif)

### ISSUE THREAD

**Issue by mkitti** [napari/napari#924] opened 2020-01-29 08:04 UTC
## 🐛 Bug

[edited title and description after @tlambert03's assessment]

48-bit RGB (3-channel uint16) images should be supported.
For example: https://imagej.nih.gov/ij/images/hela-cells.zip

## To Reproduce

```
import napari, skimage
img = skimage.io.imread('hela-cells.tif')
napari.view_image(img) 
```

img is a numpy.ndarray
```
In [3]: img.dtype                                                               
Out[3]: dtype('uint16')

In [4]: img.shape                                                               
Out[4]: (512, 672, 3)
```

This was using QT 5.9.6
```
napari/__init__.py:27: UserWarning: 
    napari was tested with QT library `>=5.12.3`.
    The version installed is 5.9.6. Please report any issues with this
    specific QT version at https://github.com/Napari/napari/issues.
```

Here is the actual error produced:
```
In [5]: napari.view_image(img)                                                  
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/napari/_qt/layers/qt_base_layer.py in <lambda>(value)
     26         sld.setSingleStep(1)
     27         sld.valueChanged[int].connect(
---> 28             lambda value=sld: self.changeOpacity(value)
     29         )
     30         self.opacitySlider = sld

~/anaconda3/lib/python3.7/site-packages/napari/_qt/layers/qt_base_layer.py in changeOpacity(self, value)
     45     def changeOpacity(self, value):
     46         with self.layer.events.blocker(self._on_opacity_change):
---> 47             self.layer.opacity = value / 100
     48 
     49     def changeBlending(self, text):

~/anaconda3/lib/python3.7/site-packages/napari/layers/base/base.py in opacity(self, opacity)
    227 
    228         self._opacity = opacity
--> 229         self._update_thumbnail()
    230         self.status = format_float(self.opacity)
    231         self.events.opacity()

~/anaconda3/lib/python3.7/site-packages/napari/layers/image/image.py in _update_thumbnail(self)
    567             colormapped = color_array.rgba.reshape(downsampled.shape + (4,))
    568             colormapped[..., 3] *= self.opacity
--> 569         self.thumbnail = colormapped
    570 
    571     def _get_value(self):

~/anaconda3/lib/python3.7/site-packages/napari/layers/base/base.py in thumbnail(self, thumbnail)
    448             with warnings.catch_warnings():
    449                 warnings.simplefilter("ignore")
--> 450                 thumbnail = img_as_ubyte(thumbnail)
    451 
    452         padding_needed = np.subtract(self._thumbnail_shape, thumbnail.shape)

~/anaconda3/lib/python3.7/site-packages/skimage/util/dtype.py in img_as_ubyte(image, force_copy)
    484 
    485     """
--> 486     return convert(image, np.uint8, force_copy)
    487 
    488 

~/anaconda3/lib/python3.7/site-packages/skimage/util/dtype.py in convert(image, dtype, force_copy, uniform)
    253 
    254         if np.min(image) < -1.0 or np.max(image) > 1.0:
--> 255             raise ValueError("Images of type float must be between -1 and 1.")
    256         # floating point -> integer
    257         prec_loss()

ValueError: Images of type float must be between -1 and 1.
Out[5]: <napari.viewer.Viewer at 0x7fe6ea245cd0>
```

## Expected behavior

Napari should show the Hela cell example image in RGB as rendered by ImageJ/FIJI.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.2.10
Platform: Linux-4.15.0-74-generic-x86_64-with-debian-buster-sid
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Qt: 5.9.6
PyQt5: 5.9.2
VisPy: 0.6.4
NumPy: 1.18.1
SciPy: 1.3.2
scikit-image: 0.15.0
Dask: 2.9.2

GL version: 4.5 (Compatibility Profile) Mesa 19.2.0-devel
MAX_TEXTURE_SIZE: 16384
```

 - Any other relevant information:

I'm using Anaconda.

**Comment by tlambert03** [comment] 2020-01-29 12:15
Hi @mkitti,

thanks for the example.  It's not that napari doesn't support `uint16`, it's that we didn't anticipate that type of image (48-bit RGB): it's arranged as an RGB image (n x n x 3), so napari interprets it as an RGB image and tries to show it as such ... but it's not in an 8-bit range as almost all other RGB images are.  So the following _would_ work:

```python
# use the channel_axis argument to tell napari your image is multichannel
napari.view_image(img, channel_axis=2)

# keep it as an RGB image (where the channels are not separated)
# but bring it into the "typical" range of RGB images
napari.view_image(img/img.max())
```

I'll note that one of the reasons this image works in ImageJ is that it has ImageJ-specific metadata in the ImageDescription tag: (`channels=3`) that is telling imageJ similar info to our `channel_axis` argument.  We don't (currently) try to read ImageJ tags.

in any case, I do agree it would be nice to have this all be more obvious when opening such a file.  we could potentially add some more "magic" to detect a non-standard RGB image.  what do @jni and @sofroniewn think?

**Comment by mkitti** [comment] 2020-01-29 16:18
Thanks @tlambert03 .

In this case it seems the error is coming from thumbnail generation. Perhaps it would be best to use something like bytescale since the thumbnail numbers are not critical. 
https://docs.scipy.org/doc/scipy-0.13.0/reference/generated/scipy.misc.bytescale.html


Incidentally I came across this when sending images from Julia to Napari via PyCall.jl.
https://gist.github.com/mkitti/2f7c5fc3d3f8b0d15dd13f6d67b0e73d
Converting to Float32 did provide a workaround.

In Julia convention, all images are a normalized fixed point numbers. While I found that a bit cumbersome initially, that design does avoid issues like this. 
https://juliaimages.org/latest/arrays_colors/#fixedpoint-1

**Comment by sofroniewn** [comment] 2020-01-29 16:26
Thanks @mkitti for catching this, and thanks @tlambert03 for those initial tips.

> In this case it seems the error is coming from thumbnail generation. Perhaps it would be best to use something like bytescale since the thumbnail numbers are not critical.

We should be able to work around this - I'm not sure how vispy, the library we use for rendering will handle this type of image (adding support there should be possible too, but might take more time). I can look into this when I get the chance

**Comment by cgohlke** [comment] 2020-02-07 20:40
After working around the ValueError, 16 bit integer RGB images are rendered correctly. Unfortunately interactive contrast and gamma adjustments have no effect on RGB images.

**Comment by sofroniewn** [comment] 2020-03-22 20:33
Also @tlambert03 given recent vispy work, is there the opportunity to address this issue?

**Comment by tlambert03** [comment] 2020-03-22 20:52
yeah, we could address this... but those recent PRs to vispy won't let us address this in any more of an elegant way than we currently could just by downscaling the data prior to creating the `ImageNode`.  The main issue there, is that the GPU Texture objects in vispy are hard-coded at 8bits ([here](https://github.com/vispy/vispy/blob/01df04b675d8dc39beb3e0b2558f5df5254b6def/vispy/gloo/glir.py#L1528), and [here](https://github.com/vispy/vispy/blob/01df04b675d8dc39beb3e0b2558f5df5254b6def/vispy/gloo/glir.py#L1624), for 2D and 3D respectively).
I might make an additional PR to vispy that exposes the texture bit-depth to the user, at which point clim scaling for 48 bit color images could be fully on the GPU.

**Comment by sofroniewn** [comment] 2020-03-22 21:01
If it's natural to address this stuff in vispy that makes the most sense to me. I don't want to overwhelm them with PRs though, but it would be nice to fix

**Comment by tlambert03** [comment] 2020-03-22 21:03
the best internal fix for us would be to simply add the magic I mentioned in https://github.com/napari/napari/issues/924#issuecomment-579729438, to do some checking and rescale data accordingly.  It would require vendoring a _lot_ of stuff to achieve the "proper" (GPU-based) fix internally.

(the internal checking/scaling strategy would make for a "good first issue" though, btw 😉 )

**Comment by sofroniewn** [comment] 2020-08-24 22:20
> the best internal fix for us would be to simply add the magic I mentioned in #924 (comment), to do some checking and rescale data accordingly. 

A good place to think about that renormalization could be on the vispy side of things right here, before we set the data
https://github.com/napari/napari/blob/master/napari/_vispy/vispy_image_layer.py#L55-L67

**Comment by tlambert03** [comment] 2021-09-16 22:34
bumping this issue again.  This is not a hard one to solve for anyone looking for something to work on.  we should be able to be smarter about 48 bit RGBs

**Comment by andy-sweet** [comment] 2021-10-04 23:40
I tried to reproduce this on the main branch in Python 3.7 and 3.9 environments, but I don't get an error when calling `viewer.add_image` with the given image.

I can change the contrast limits and gamma, which are needed here because by default the image is hard to see. That's because the contrast limits are calculated from the [min, max] of the data as [0, 4095], but after averaging over the color channels in some way (to get some kind of scalar brightness value), most of the values are much lower than 4095.

Napari retains the data as np.uint16, but effectively visualizes it as a color float in some arbitrary range, which seems like fairly reasonable behavior and maybe what people were looking for here. I guess we could do something smarter with the `contrast_limits` (e.g. use percentiles instead of [min, max]), but I'm not aware of anything obvious/standard. Suggestions are welcome, but if there aren't any strong opinions, I think we might to close this bug - thoughts @tlambert03 or anyone else?

One remaining bug is that the thumbnail is a saturated white image, likely because the logic used to generate the thumbnail doesn't handle this as well as the vispy rendering logic/pipeline does. We should fix that, but I feel like the right way to do that is to use vispy to render all our thumbnails (as mentioned in #3409) rather than try to maintain a separate rendering pipeline.

Here is the 3.7 environment info dump from napari for reference (in case this related to the version of a dependency).

```
napari: 0.4.12.dev67+g869f0501.d20210924
Platform: Darwin-20.6.0-x86_64-i386-64bit
System: MacOS 11.6
Python: 3.7.11 (default, Jul 27 2021, 07:03:16) [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.09.1
VisPy: 0.8.1

OpenGL:
- GL version: 2.1 INTEL-16.5.2
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.12.dev67+g869f0501.d20210924
- svg: 0.1.5
```

**Comment by andy-sweet** [comment] 2021-10-04 23:48
One other potential bug is that after changing the contrast limits to a more visible range, there is much quantization when viewing the `np.uint16` RGB image compare to the normalized `np.float64` RGB image (i.e. that comes from `img / img.max()`).

I'm not sure if that's something we want to fix here, or is easily fixable, so any clarification would be welcome!

**Comment by mkitti** [comment] 2021-10-05 11:32
1. I think the error / crash is fixed.
2. I agree the thumbnail bug still exists, but agree that vispy is probably the best route if it is fast enough.
3. There may be some additional ImageJ metadata in that particular image indicating contrast limits. A general issue would be increasing ImageJ compatability where possible.

**Comment by sofroniewn** [comment] 2021-10-06 05:01
> I think the error / crash is fixed.

Ok good to know, will now close this issue - thanks for investigation @andy-sweet!

 > I agree the thumbnail bug still exists, but agree that vispy is probably the best route if it is fast enough.

Yes agreed too

> I feel like the right way to do that is to use vispy to render all our thumbnails (as mentioned in #3409) rather than try to maintain a separate rendering pipeline.

Yes, let's open up a dedicated issue for that if there isn't already @andy-sweet. It would definitely drop a lot of custom code. We need to think about the data flow between the layer, vispy, and the Qt widget that shows the thumbnail. We should also see if there is a big performance cost, or if that can be minimized by downsampling first, or if we can somehow just reuse what is already rendered. But in theory I think this change is the right move. I'd love to have none of the thumbnail generation code on the layer anymore.

> There may be some additional ImageJ metadata in that particular image indicating contrast limits. A general issue would be increasing ImageJ compatability where possible.

Well noted, but probably something for a dedicated issue/ discussion elsewhere.

I'll close this now, but followups as noted above. thanks!!

**Closed as completed by sofroniewn** 2021-10-06 05:01 UTC
Labels: bug, contribute:good first issue, priority:medium
