### ISSUE TITLE
How do I update the x/y axis in a VisPy plot using set_data()

### ISSUE THREAD

**Issue by cudmore** [napari/napari#790] opened 2019-12-13 06:47 UTC
I am creating a Napari plugin that has an external Qt window which includes a VisPy plot in a QHBoxLayout. See [my plugin](http://blog.cudmore.io/ShapeAnalysisPlugin/)

The initial VisPy plots are working fine but when I try to update the plot with set_data(), the axis are not scaling to the new data values? Not sure if this is Napari or VisPy but your help would be welcomed.

Here is some working code where I bring up the interface and then set some new data with set_data() and the axis do not update. If I mouse scroll out I can eventually see the new plotted points...

```
import numpy as np
import napari
from PyQt5 import QtWidgets
import vispy.plot as vp

class TryToUpdatePlot(QtWidgets.QWidget):
	def __init__(self):
		super(TryToUpdatePlot, self).__init__()
		viewer = napari.Viewer()
		self.initUI()

	def initUI(self):
		fig = vp.Fig(size=(800, 600), show=False)
		# random data
		data = np.random.rand(100, 2)

		line1 = fig[0, 0].plot(data=data)
		line2 = fig[1, 0].plot(data=data)

		self.myHBoxLayout = QtWidgets.QHBoxLayout(self)

		self.myHBoxLayout.addWidget(QtWidgets.QPushButton('A Button'))
		self.myHBoxLayout.addWidget(fig.native)

		self.show()

		# update line1 plot with new data offset by 100
		data = np.random.rand(100, 2) + 100
		# this call to set_data does not update the range of x/y axis
		# it remains at the original scale ???
		line1.set_data(data)

		# Is there something I can add here ???
		#line1.update()
		#line1.view.camera.set_range()

if __name__ == '__main__':
	with napari.gui_qt():
		test = TryToUpdatePlot()

```

**Comment by jni** [comment] 2019-12-13 07:08
@cudmore Very cool!!

It definitely seems to be a vispy issue more than a napari one, but I wonder: have you tried making *just* a vispy plot and using `set_data()`? Does that update?

In short, my advice would be to work on the *minimal* example that demonstrates your issue, because that might help us get some vispy developers on board with helping you. Personally I don't know immediately what would help, or whether this is even broken or expected behavior.

**Comment by tlambert03** [comment] 2019-12-13 11:11
FWIW, this is exactly the kind of plot (with axis linking) that #675 is working on

**Comment by tlambert03** [comment] 2019-12-14 16:39
Hi @cudmore, in the meantime, you need to add something like this to your code to get it working (right where you have `# Is there something I can add here ???`)
```
fig[0, 0].view.camera.set_range(x=(data[:,0].min(), data[:,0].max()), y=(data[:,1].min(), data[:,1].max()))
```
I don't believe the `vispy.PlotWidget` is designed to autoscale the range/domain when calling `set_data()`, so you have to do it yourself. `fig[0,0]` is actually the `PlotWidget` that contains the `view`, which in turn contains the `camera` whose range you are wanting to set.  the `camera` object has a `set_range` method that accepts `x` and `y` 2-tuples for the plot domain and range.  Hope that helps!

**Comment by tlambert03** [comment] 2020-01-11 01:47
Hey @cudmore, did the `set_range` tip help?  ok if we close this issue?

**Comment by kcpevey** [comment] 2022-12-07 20:04
Nearly 3 years later, I can confirm that the `set_range` approach works as expected. I suggest closing.

**Closed as completed** 2023-09-18 01:38 UTC
Labels: question
