### ISSUE TITLE
Active napari viewer breaks ipywidgets events

### ISSUE THREAD

**Issue by jstutters** [napari/napari#687] opened 2019-11-12 12:35 UTC
## 🐛 Bug

If an instance of napari.Viewer() is present in a jupyter notebook, ipython widget events do not function properly.  The following error is sent to stderr:

`IPKernelApp] WARNING | No such comm: b161f0d81502401fab9931c48a91f974`

## To Reproduce

1. Run the following code in a notebook:

```python
%gui qt
```

Then:

```python
import napari
import ipywidgets as widgets
from IPython.display import display

viewer = napari.Viewer()

def print_it(ev):
    with outputter:
        if ev["name"] == "value":
            print(ev["new"])
            
select = widgets.Select(options=["image 1", "image 2"])
select.observe(print_it)
outputter = widgets.Output()
display(select, outputter)
```

## Expected behavior

Widget events should fire correctly.

## Environment

napari==0.2.5+2.g09a4117
PyQt5==5.13.2
jupyter-core==4.6.1
ipywidgets==7.5.1
ipython==7.9.0

**Comment by sofroniewn** [comment] 2019-11-12 15:30
Hmm, ok - I suspect it might be something to do with our console code - we connect our napari console to the existing jupyter kernel here https://github.com/napari/napari/blob/32e4533c210d69115fd9f1c9b28861bdd8ca5751/napari/_qt/qt_console.py#L73 and maybe that's causing something weird to happen

I can try reproducing on my machine, and then try seeing if the problem persists if I disable the console. That will at least narrow things down

**Comment by guiwitz** [comment] 2019-12-16 23:29
I ran several times into this same problem and stumbled across this issue. I tried to do what @sofroniewn suggested and modified the qt_console.py section into:
```python
elif isinstance(shell, ZMQInteractiveShell):
            # if launching from jupyter notebook, connect to the existing
            # kernel
            '''kernel_client = QtKernelClient(
                connection_file=get_connection_file()
            )
            kernel_client.load_connection_file()
            kernel_client.start_channels()

            self.kernel_manager = None
            self.kernel_client = kernel_client
            self.shell = shell
            self.push = self.shell.push'''
            self.shell = None
```
and also commented out this line:
https://github.com/napari/napari/blob/5c2848f298bbdb94ee9706b1cc280cc2c6d61e96/napari/viewer.py#L63
and it seems it did solve the problem. So now I can finally use ipywidgets with napari!

I don't know how to solve this problem in general. It would be good however to do it because ipywidgets is quite popular in the Jupyter environment and is a nice complement to napari to e.g. create small interactive applications. Maybe there could be an option when creating the viewer to disable the console, something like ```napari.View(console = False)```?

**Comment by sofroniewn** [comment] 2020-03-21 03:37
Console loading has now been made lazy by default with #1055 so the console imports will not happen unless someone clicks the console button. Does this satisfy peoples needs here? (in which case i will close the issue). Otherwise we could additionally provide a way to hide the open console button too so that it could never be accidentally opened.

**Comment by jni** [comment] 2020-03-21 03:48
@sofroniewn I'd like to leave this open until the root cause here can be fixed or the error *completely* prevented. If that means no console when launching from Jupyter, so be it... Honestly I think the most valuable use case for the console is when launching from script. Other uses are essentially redundant and have caused us quite a lot of grief (eg the `viewer` variable being overwritten).

**Comment by psobolewskiPhD** [comment] 2022-10-19 18:57
The original issue is solved:
<img width="1136" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/76622105/196779729-e359c1b1-9ccb-4db1-a8d7-866a6c649bdd.png">

@jni at present the console still launches when napari is launched from jupyter but it is empty. I've made a PR to disable the button, same as for ipython:
https://github.com/napari/napari/pull/5213
Is that sufficient to close this issue?

**Closed as completed** 2022-11-08 19:09 UTC
Labels: bug, topic:jupyter
