### ISSUE TITLE
Cancel button in plugin installer

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#3340] opened 2021-09-05 12:01 UTC
## 🚀 Feature
Hi all,

I sometimes try to install plugins and it takes forever. Furthermore, one can actually predict that it will fail eventually. Would it be possible to build in a 'Cancel' button in the installer Window?

![image](https://user-images.githubusercontent.com/12660498/132125997-56ffdeeb-39a3-4a51-abef-58ad52c96d0a.png)

**Comment by tlambert03** [comment] 2021-09-05 12:05
duplicate of https://github.com/napari/napari/issues/3070

**Closed as completed by tlambert03** 2021-09-05 12:05 UTC
Labels: feature
