### ISSUE TITLE
Viewing a list of images with different shapes

### ISSUE THREAD

**Issue by pskeshu** [napari/napari#755] opened 2019-12-03 06:15 UTC
There's a frequent use-case which is not supported by napari currently is the ability to view numpy arrays of different sizes stored in a list. I'm not sure if there's an elegant solution to this, but I'm making this issue anyway, in case someone has any ideas.

**Comment by jni** [comment] 2019-12-03 07:39
@pskeshu this is a duplicate of #661 and #605. =) See there for discussions. Closing this as duplicate for now, though!

**Closed as completed by jni** 2019-12-03 07:39 UTC
