### ISSUE TITLE
Delete selected layers keybinding is possibly incorrect

### ISSUE THREAD

**Issue by TimMonko** [napari/napari#7448] opened 2024-12-13 18:06 UTC
### 🐛 Bug Report

GUI and Preferences -> Keybinding state that `Ctrl+Del` (on Windows) is the keybinding to Delete Selected Layers. However, `Del` on it's own functions in this capacity. As such, I cannot confirm if `Ctrl+Del` is working as intended, because any combination of `Key+Del` works to delete layers (`Shft+Del`, `a+Del`, etc.)

### 💡 Steps to Reproduce

1. Add Layers
2. Press `Del`
3. Selected layers are deleted

### 🌎 Environment

napari: 0.5.5
Platform: Windows-11-10.0.22631-SP0
Python: 3.12.7 (main, Oct 16 2024, 00:21:24) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.11
NumPy: 1.26.4
SciPy: 1.14.1
Dask: 2024.12.0
VisPy: 0.14.3
magicgui: 0.9.1
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.3.1
psygnal: 0.11.1
npe2: 0.7.7
pydantic: 2.10.3

OpenGL:
- GL version: 4.6.0 NVIDIA 551.78
- MAX_TEXTURE_SIZE: 32768
- GL_MAX_3D_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 2.0
- screen 2: resolution 1440x2560, scale 1.0

Optional:
- numba: 0.60.0
- triangle: 20230923
- napari-plugin-manager: 0.1.3

Settings path:
- C:\Users\timmo\AppData\Local\napari\.venv_48daee6d4e8fe572adbe83a068fdb1e2351d2f1c\settings.yaml

**Comment by psobolewskiPhD** [comment] 2024-12-14 00:02
I tested this and indeed, delete alone deletes layers, so Command-Delete doesn't do anything.
I re-bound it to Shift-O and that worked, so the action and keybind work correctly, it's just the current binding isn't needed.
Looking a bit more, you can see that delete, backspace, and return are special:
https://github.com/napari/napari/blob/b2edccd6e40e04467ccfeec0257c2160783f7187/napari/_qt/containers/qt_layer_list.py#L87-L92

They are handled by qt.
Ah so now I understand:
- delete key will delete a layer when the layer list is focused, because it's handled by Qt
- the Command-delete binding should work when the canvas, etc. is focused, because it's handled by the viewer.
...but it doesn't. Shift-delete works, shift-O works but not Command-Delete for me. It appears to be a macOS system shortcut for delete the to the beginning to the line.

@TimMonko Can you try on windows:
- make multiple layers
- select one
- click to the canvas!
- test `Del` -- it shouldn't do anything -- test the control-del binding. does it work?

I think deleting a layer when focused on the canvas is a legit use case? So the keybind should work. Shame the default macOS doesn't....

**Comment by TimMonko** [comment] 2024-12-14 02:01
From my Windows testing:
- `Del` works when layer list is focused. `Del` does NOT remove layer when layerlist is not focused (like canvas is focused), as you posited.
- `Ctrl+Del` keybinding _does_ work when layerlist is not in focus. (so this is a difference on Win I suppose)
- Adding alt keybinding (I used `Shift-O` lol) _does_ work when layerlist is both in and out of focus. My guess then is that `Ctrl+Del` is likely working when layer list is in focus, but being superseded by the special Qt binds. 

I guess you came prepared for this from things like #7417

**Comment by psobolewskiPhD** [comment] 2024-12-14 02:09
So what do you think we should do with this? Close?
Change the binding in some way? (alt-del would work on macOS)

**Comment by TimMonko** [comment] 2024-12-14 04:58
Well there's still a few issues:

1. The keybinding _is_ incorrectly functioning on mac
2. Regardless of `ctrl+del` working -- either silently on the layerlist, due to `del` function, and correctly on unfocused layerlist -- it is not intuitive for the user what is happening. I actually remember a long time ago trying to use just `del` to delete layers and not understanding why it wasn't working. I was unaware that the keybinding was `ctrl+del` and I was likely unaware that I was probably no longer focused on the  layerlist.

Is there a reason that `Key_Delete` gets special treatment? Is this function specifically when editing the layer name in the GUI? 

https://github.com/napari/napari/blob/b2edccd6e40e04467ccfeec0257c2160783f7187/napari/_qt/containers/qt_layer_list.py#L87C1-L92C55

(p.s., I can't seem to figure out how to render those nice when lines from files are linked)

**Comment by jni** [comment] 2024-12-14 07:17
@TimMonko

> I can't seem to figure out how to render those nice when lines from files are linked

you have to select only the lines (L87-L92), using the line numbers (ie shift-clicking on the left side of the code), rather than select the text with a cursor, which then includes character count (L87C1-L92C55), which is a new feature that I hate in no small part because it only works occasionally. 😂

**Comment by jni** [comment] 2024-12-14 07:17
(I fixed up your comment just by delecting the "Cxx" characters from the link text)

**Comment by Czaki** [comment] 2024-12-14 10:43
We may overwrite the key handler in the layer list widget to avoid default handling.

**Comment by psobolewskiPhD** [comment] 2024-12-14 16:29
Re: the macOS aspect: I think app-models supports explicit Control, so could switch to that. Windows/Linux would be unchanged and on mac Control-del would work where command-del doesn't as noted above.

@TimMonko Can you clarify:
> Regardless of ctrl+del working -- either silently on the layerlist, due to del function, and correctly on unfocused layerlist -- it is not intuitive for the user what is happening. I actually remember a long time ago trying to use just del to delete layers and not understanding why it wasn't working. I was unaware that the keybinding was ctrl+del and I was likely unaware that I was probably no longer focused on the layerlist. If we don't change the binding, then I think it should be made more clear (even if it's in the docs) how exactly some of the keybinds interact with focused and unfocused elements.

Does <del> on the layerlist not work? Could this be a mac vs windows thing too? windows has backspace?
But yes, the special treatment in that code block is to ensure that when a user is interacting with the layer list, e.g. editing a name, the keybind *doesn't e.g. delete a point*. You can actually bind just <del> to the delete selected layer viewer binding and it will work in both cases: with or without layerlist focus. First you would need to remove the conflicts with delete point/shape which must be much more common than deleting a layer not via the layer list. 
As i mentioned, deleting a layer from the canvas, not via layer list I think is a valid use case, but I expect it is quite uncommon, so it shouldn't be too easy to accidentally do this IMO.
Overall, I think that the different behaviors depending on focus arn't that uncommon in apps? Even in this GitHub form keybinds work differently due to the text entry field than outside of it...
My expectation when in the layer list is for delete to work.
But at the same time i'd be shocked if I was drawing a shape and hit delete and the layer was deleted. I think intuitively I expect that there is a context to the actions of keys I press.

**Comment by psobolewskiPhD** [comment] 2024-12-15 02:11
Per https://github.com/pyapp-kit/app-model/issues/229
We should just add `KeyMod.WinCtrl | KeyCode.Delete` as a 2ndary binding. That will ensure control-del works on macOS. Knock-on effect is that windows-key-del will start working on windows, but I think that's ok?

**Comment by psobolewskiPhD** [comment] 2024-12-15 03:03
Ha! It's actually all working correctly!
`    'napari:delete_selected_layers': [KeyMod.CtrlCmd | KeyCode.Delete],`
require the use of the `delete` key, but on a macOS MacBook keyboard the physical key labeled `delete` is actually backspace!
So what I've been testing is effectively Command-Backspace which is not correct and doesn't work. But if I press Command-Fn-`delete key on keyboard` (Fn-`delete key on keyboard` yields true delete, forward delete) then it works!
See:
https://github.com/pyapp-kit/app-model/issues/229#issuecomment-2543421435

So technically everything is correct here.

I think we should make a 2ndary binding of `KeyMod.CtrlCmd | KeyCode.Backspace` to make it work on macOS.

**Comment by TimMonko** [comment] 2024-12-15 03:46
@psobolewskiPhD to clarify:
1. When Layer List is in focus, both `Del` and `Backspace` deletes selected layers.
2. When Layer List is not in focus, only `Ctrl+Del` deletes selected layers.

Overall, you've sort of convinced me how unimportant this extra keybind is because I assume in _most_ cases a user will be interacting with the layer list and also be making decisions about whether to remove that layer list, so the sensible `Del` and `Backspace` keys would work because the viewer is in focus. 

I guess the confusing part that remains is
1. This in-focus functionality is not made clear to the user
2. The keybinding displayed on the GUI icon is for out-of-focus functionality.
3. Users would benefit from `Del` functionality being explicitly explained as conditional. i.e. layerlist in focus deletes layer, canvas and points/shapes deletes the selected element, etc. I mean, I think some times I understand this implicit connection, and in other times I get completely confused, because its not intuitive what I have focused in the viewer to give me that feedback.

**Comment by psobolewskiPhD** [comment] 2024-12-15 04:15
My proposal:
1. add 2ndary binding `KeyMod.CtrlCmd | KeyCode.Backspace` to give macOS parity
2. update the viewer tutorial layer list section https://napari.org/stable/tutorials/fundamentals/viewer.html#layer-list to mention layer-list specific keybindings.

**Comment by psobolewskiPhD** [comment] 2024-12-15 15:44
Pursuant to the above I made a docs issue:
https://github.com/napari/docs/issues/538
and a PR to address the macOS keybinding:
https://github.com/napari/napari/pull/7449

**Comment by Czaki** [comment] 2024-12-16 14:27
The delete layer using Delete or Backspace is hardcoded here:

https://github.com/napari/napari/blob/c41596f242d5594349ff3370aa2f46e07c557b49/napari/_qt/containers/_base_item_view.py#L56-L58

And these lines are called from:

https://github.com/napari/napari/blob/c41596f242d5594349ff3370aa2f46e07c557b49/napari/_qt/containers/qt_layer_list.py#L85-L86

**Comment by TimMonko** [comment] 2024-12-16 14:51
@psobolewskiPhD Yes, the keybinding works both in- and out-of focus for me. Sorry to be confusing there. I think my biggest concern remains that it is unclear to the user that there are _layer list specific_ keybinds that are _not_ the same as the keybinds in preferences. 

I wonder if there is a way to add these Layer List keybinds also to `Preferences` -> `Shortcuts` -> `Group` -> (new group) `Layer List bindings`. For now, they could be non-editable. I think [napari/docs#538](https://github.com/napari/docs/issues/538) is a great idea too, but I'm just wondering if there is a non-docs way to make this information more clear.

**Comment by psobolewskiPhD** [comment] 2024-12-16 16:23
> We could just disable the code that I pointed in above comment and then everything will work in same way.

I would be a hard `no` on this. It would be a massive regression IMO.
The layer list keyboard interactions are consistent with other applications where there are lists and things.

**Comment by DragaDoncila** [comment] 2024-12-17 22:44
> I wonder if there is a way to add these Layer List keybinds also to Preferences -> Shortcuts -> Group -> (new group) Layer List bindings. For now, they could be non-editable.

Hi all, been following these discussions. Don't have a lot to add, but I will say this should be a thing. It might be a bit tricky now given the like, eleventy billion keybinding handling mechanisms we have 😬, but **all** keybindings should be listed in that Preferences tab and eventually editable.

**Comment by Czaki** [comment] 2024-12-18 07:56
> Hi all, been following these discussions. Don't have a lot to add, but I will say this should be a thing. It might be a bit tricky now given the like, eleventy billion keybinding handling mechanisms we have 😬, but **all** keybindings should be listed in that Preferences tab and eventually editable.

Should be. But it means that we should finish refactor and fully use single solution. Not app-model and custom actions like now.

**Comment by psobolewskiPhD** [comment] 2024-12-21 03:57
I think editable layer list keybindings should be pretty down the priority list, but if they are to be a thing it makes sense to route them via app-model like everything else. So maybe we can tack on a stretch goal to the existing keybinding work and then given 
https://github.com/napari/docs/issues/538
and https://github.com/napari/napari/pull/7449
we close this, since in fact the keybindings are set and work correctly?

**Comment by TimMonko** [comment] 2024-12-21 04:23
After this thorough discussion, I'm ok closing with closing this issue. I think we should make a new issue to incorporate layerlist keybindings into Preferences (even if not editable)

**Closed as completed** 2024-12-30 21:34 UTC
Labels: bug

**Comment by psobolewskiPhD** [comment] 2025-01-07 02:37
For lack of better place, app-model has a PR to support explicit Ctrl and Meta:
https://github.com/pyapp-kit/app-model/pull/230
