### ISSUE TITLE
Exception when deleting markers layer in annotate-2d example

### ISSUE THREAD

**Issue by royerloic** [napari/napari#226] opened 2019-04-20 20:08 UTC
## 🐛 Bug

Exception thrown when removing (deleting) a markers layer:
(whole layer not just a single marker)

`
click to add markers; close the window when finished.
WARNING: Traceback (most recent call last):
  File "/Users/royer/workspace/python/napari/examples/annotate-2d.py", line 17, in <module>
    markers.mode = 'add'
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/royer/workspace/python/napari/napari/util/app.py", line 26, in app_context
    app.exec()
  File "/Users/royer/workspace/python/napari/napari/components/_layers_list/model.py", line 193, in remove_selected
    self.pop(i)
  File "/Users/royer/workspace/python/napari/napari/util/list/_model.py", line 55, in pop
    self.events.removed(item=obj)
  File "/Users/royer/workspace/python/napari/napari/util/event.py", line 490, in __call__
    self._invoke_callback(cb, event)
  File "/Users/royer/workspace/python/napari/napari/util/event.py", line 505, in _invoke_callback
    cb(event)
  File "/Users/royer/workspace/python/napari/napari/components/_layers_list/model.py", line 29, in _remove
    layer.viewer = None
  File "/Users/royer/workspace/python/napari/napari/layers/_base_layer/model.py", line 170, in viewer
    self._parent = parent
  File "/Users/royer/workspace/python/napari/napari/layers/_base_layer/_visual_wrapper.py", line 82, in _parent
    self._node.parent = parent
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/frozen.py", line 17, in __setattr__
    object.__setattr__(self, key, value)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/scene/node.py", line 209, in parent
    self._update_trsys(None)
  File "/Users/royer/workspace/python/napari/napari/_vispy/scene/visuals.py", line 82, in _update_trsys
    self.transforms.scene_transform = scene.node_transform(doc)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/visuals/transforms/transform_system.py", line 276, in scene_transform
    self._scene_transform.transforms = tr
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/visuals/transforms/chain.py", line 96, in transforms
    self.update()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/visuals/transforms/base_transform.py", line 153, in update
    self.changed(*args)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/visuals/transforms/chain.py", line 212, in _subtr_changed
    self.update(ev)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/visuals/transforms/base_transform.py", line 153, in update
    self.changed(*args)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/visuals/transforms/chain.py", line 281, in source_changed
    new_tr = [tr[0]]
IndexError: list index out of range
ERROR: Invoking <bound method SimplifiedChainTransform.source_changed of <ChainTransform [<STTransform scale=[1. 1. 1. 1.] translate=[0. 0. 0. 0.] at 0x4852466968>,
                 <STTransform scale=[1.0765465e+00 1.0765465e+00 1.0000000e-06 1.0000000e+00] translate=[71.416046 33.31137   0.        0.      ] at 0x4850432320>] at 0x1213e95c0>> for Event
`

## To Reproduce

1. run annotate-2d example
2. delete markers layer
3. boom

## Expected behavior

no exception

## Environment

 - napari Version (e.g., 1.0): latest dim PR
 - OS (e.g., Linux): OSX
 - Python version: 3.7
 - Any other relevant information:

**Comment by sofroniewn** [comment] 2019-04-20 20:09
This is a duplicate of #170

**Closed as completed** 2019-04-23 23:42 UTC
Labels: triage:duplicate
