### ISSUE TITLE
Visualization bug in nbscreenshot

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#2506] opened 2021-04-04 18:34 UTC
## 🐛 Bug

Hi all,

I just noticed a visualization a bug when using `napari.utils.nbscreenshot(viewer)`. The screenshot doesn't 100%ly fit to what I see in the actual napari window. Differences are highlighted with white arrows in this screenshot:

![image](https://user-images.githubusercontent.com/12660498/113518030-03fbfe00-9584-11eb-9500-56edb03ebe39.png)

## To Reproduce

The notebook where I observed this is online available. The error is reproducible on my machine. For the screenshot, please scroll to the very end of the notebook.
https://nbviewer.jupyter.org/github/BiAPoL/Bio-image_Analysis_with_Python/blob/3fa983e7109f39f18aabb33b7e4fe70898c7e682/image_processing/07_Labeling.ipynb

## Expected behavior

Pixel intensities from the canvas should be copied correctly to the screenshot.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
```
napari: 0.4.7
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.2
SciPy: 1.6.1
Dask: 2021.03.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.8681
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- clEsperanto: 0.7.4
- console: 0.0.2
- svg: 0.1.4
```

 - Any other relevant information:

## Additional context

That's propably a low-priority bug. No hurry from my side :-)

Happy Easter!

**Comment by sofroniewn** [comment] 2021-04-04 23:06
Unfortunately we've already seen several reports of this, #1566 and #1237. We need to look in more. Fine to leave this open though as it is another example

**Comment by psobolewskiPhD** [comment] 2024-02-04 19:17
I can't reproduce this, it looks like this was fixed by https://github.com/vispy/vispy/pull/2090
If it pops up again, please re-open or make a new issue.

**Closed as completed by psobolewskiPhD** 2024-02-04 19:17 UTC
Labels: bug, topic:vispy
