### ISSUE TITLE
Deprecated `edge_color` cannot be passed to `ViewerModel.add_points`

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#6978] opened 2024-06-11 22:00 UTC
### 🐛 Bug Report

I tried to pass `edge_color` through `ViewerModel.add_points`. I expected to get a deprecation warning, but instead I got an exception:

```
TypeError: add_points() got an unexpected keyword argument 'edge_color'
```

Note that I can pass `edge_color` to the `Points.__init__`.

I assume similar behavior for other deprecated `edge_*` parameters, but I have not tried them. 

### 💡 Steps to Reproduce

```python
from napari.layers import Points
p = Points(edge_color='red')  # Works with deprecation warning
v = napari.components.ViewerModel()
v.add_points(edge_color='red')  # Fails
```

### 💡 Expected Behavior

I expect to get the same deprecation warning as when using `Points.__init__`.

### 🌎 Environment

napari: 0.4.17rc4.dev907+g3aac4b71
Platform: macOS-14.5-arm64-arm-64bit
System: MacOS 14.5
Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:51:49) [Clang 16.0.6 ]
Qt: 5.15.11
PyQt5: 5.15.10
NumPy: 1.26.4
SciPy: 1.13.1
Dask: 2024.5.1
VisPy: 0.14.2
magicgui: 0.8.2
superqt: 0.6.6
in-n-out: 0.2.1
app-model: 0.2.7
npe2: 0.7.5

OpenGL:
  - GL version:  2.1 Metal - 88.1
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 3440x1440, scale 1.0
  - screen 2: resolution 1512x982, scale 2.0

Optional:
  - numba: 0.59.1
  - triangle not installed

Settings path:
  - /Users/asweet/Library/Application Support/napari/napari-dev_bed8b9b3d61b11a9560a577ec715d63283498f35/settings.yaml
Plugins:
  - napari: 0.4.8rc3.dev2013+g2300b0ed (81 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.1.10 (2 contributions)

### 💡 Additional Context

I expect this bug occurs because `add_points` is automatically generated using the signature of `Points.__init__`, but `rename_argument` works in a way that does not add the deprecated name to the signature (instead it assigns the deprecated parameter value to the new parameter).

**Comment by Czaki** [comment] 2024-06-11 23:28
it is a duplicate of #6966

**Comment by DragaDoncila** [comment] 2024-06-11 23:31
Can confirm #6970 fixes it. Weirdly though I never get the deprecation warning. Could that be something just on my end?

**Comment by Czaki** [comment] 2024-06-11 23:33
> Could that be something just on my end?

Deprecation warning are not rendered by default on user side. I think that we should switch it to FutureWarning. https://docs.python.org/3/library/exceptions.html#DeprecationWarning

**Comment by andy-sweet** [comment] 2024-06-11 23:36
Thanks for the quick updates! And the fix! I'll let this be closed when the PR is merged.

**Comment by DragaDoncila** [comment] 2024-06-11 23:38
> Deprecation warning are not rendered by default on user side. I think that we should switch it to FutureWarning.

What?? That seems terrible, in that a lot of users may never see these warnings and stuff will just stop working next release? @jni did you know this lol

**Comment by Czaki** [comment] 2024-06-11 23:45
> What?? That seems terrible, in that a lot of users may never see these warnings and stuff will just stop working next release? @jni did you know this lol

I am repeating this discussion every few months with some core-dev.

**Comment by Czaki** [comment] 2024-06-12 06:58
> Can confirm #6970 fixes it. Weirdly though I never get the deprecation warning. Could that be something just on my end?

I have just checked code, and Future warning is there. Did you use a constructor with passing deprecated kwargs?

**Comment by DragaDoncila** [comment] 2024-06-12 07:48
> Did you use a constructor with passing deprecated kwargs?

I just used the snippet from Andy above, so yes `Points(edge_color='red')`

**Comment by Czaki** [comment] 2024-06-12 08:24
It is a Deprecation warning... Opening PR.

**Closed as completed** 2024-06-13 00:38 UTC
Labels: bug
