### ISSUE TITLE
Cannot change interpolation mode or attenuation value with invisible layers

### ISSUE THREAD

**Issue by jni** [napari/napari#1398] opened 2020-07-03 08:08 UTC
## 🐛 Bug

When I have one or more layers with `visible=False` and in 3D viewer mode, changing the interpolation mode or the attenuation value (and maybe other things?) crashes napari.

## To Reproduce

```python
import os
import numpy as np
import napari

volume = np.random.random((5, 768, 1024))


with napari.gui_qt():
    viewer = napari.Viewer(ndisplay=3)
    layer_norm = viewer.add_image(
        volume,
        visible=False,
    )
    layer_norm.interpolation = 'linear'
```

## Expected behavior

The interpolation mode should be changed with minimum fuss.

## Environment

```
napari: 0.3.6.dev11+ge43f730
Platform: Darwin-18.7.0-x86_64-i386-64bit
Python: 3.7.4 (default, Aug 13 2019, 15:17:50)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.17.2
SciPy: 1.3.1
Dask: 2.19.0
VisPy: 0.6.4

GL version:  2.1 NVIDIA-12.0.24 355.11.10.50.10.103
MAX_TEXTURE_SIZE: 16384

Plugins:
  - napari-plugin-engine: 0.1.6
  - svg: 0.1.3
```

**Comment by sofroniewn** [comment] 2020-07-05 21:35
I can reproduce this - it is because of how we're swapping out the Image and Volume visuals from vispy when you transition from 2D to 3D renderings and the fact that the swap hasn't happened yet when the data is not visible. Definitely a bug that we should fix and something that it will be easy to add a test for.

Given my comment here https://github.com/napari/napari/issues/1347#issuecomment-653111750 about keeping both the Image and Volume nodes around and then just changing which one is used/ shown as being something we want to do anyway, I think I will attempt a solution for this using that approach too

**Comment by sofroniewn** [comment] 2020-07-05 22:12
One option actually is to just always use the `VolumeNode` this could actually dramatically simplfy things for us, especially as we propagate changes and improvements to vispy.

Downsides are right now the volume node doesn't support rgb (we'd have to add that to vispy) and it doesn't support all the rendering modes, but it does have `nearest` and `linear` which is I think all we need.

What do @tlambert03 and @jni think of this idea? I'm curious @tlambert03 how this would influence your current PRs to VisPy which I think are implementing improvements to both `Volume` and `Image`?

We'd have to see if how the texture limits apply to `Volume` in the event of very big (say 8k x 8k) 2D slices too and if there are additional overheads.

Note that when in 2D viewing mode the camera would still be a 2D camera just call `np.expand_dims(data, axis=0)` on our 2D image to pass a "flat" 3D image to vispy, so functionality would be same as before. This really would make the transition between 2D and 3D viewing much much more straight forward!!

**Comment by sofroniewn** [comment] 2020-07-05 22:36
I just realized we're actually already overwriting quite a bit of our own vispy volume node here https://github.com/napari/napari/blob/master/napari/_vispy/volume.py and things like the `attenuation` parameter were never actually added into `VisPy` yet!!

This means we can actually still fix a but of the strangeness that came following #1376 (such as the overloaded `threshold` parameter) and some of the weirdness required to fix #1403 and #1402.

We can also incorporate the changes from @tlambert03 that are about to merge in https://github.com/vispy/vispy/pull/1842 if we'd like to get this stuff out before waiting on the next vispy release (similar to the approach taken in https://github.com/napari/napari/pull/1056 which we never merged).

All we'd need to do is implement rgb support for volumes, something requested in VisPy here https://github.com/vispy/vispy/issues/1256 and then we'd be be at feature parity between the `Image` and `Volume` visuals and assuming we didn't run into performance issues we could just use `Volume` going forward which really would be a big simpliciation.

I might work on a PR that has everything apart from the rgb support to see what that is like. Shouldn't be too hard to add rgb support. Thoughts everyone?

**Comment by sofroniewn** [comment] 2020-07-14 22:14
As it seems unlikely that we will go with the approach of #1404 I want to pull out link to this test which will currently fail on master, but pass after the issue is fixed https://github.com/napari/napari/blob/61d990344263052c1ec494cf77ab0238d5f5fdf6/napari/_vispy/_tests/test_image_rendering.py#L40-L73

**Comment by jni** [comment] 2020-07-15 08:02
Thanks @sofroniewn and sorry for the silence here! It was a busy week as you know. =) Fixing this bug easily might be an interesting argument in favour of #1404... Either way, maybe we should prioritise model simplification first, as it might make these bug fixes simpler too.

**Comment by sofroniewn** [comment] 2020-11-16 17:04
There have been a number of changes to this part of the code since this bug report was made, so we should check and see if it is still an issue, I'm not sure

**Comment by jni** [comment] 2020-11-17 03:00
Yep, still an issue. Running the code above raises the error:

```pytb
ValueError: interpolation must be one of bessel, bicubic, bilinear, blackman, catrom, gaussian, hamming, hanning, hermite, kaiser, lanczos, mitchell, nearest, quadric, sinc, spline16, spline36
```

**Comment by sofroniewn** [comment] 2021-06-03 00:01
@alisterburt this might be something you want to look into while looking at the vispy volume stuff too

**Comment by psobolewskiPhD** [comment] 2023-05-18 09:46
I can't reproduce this on 0.4.17 on `main` using ipython:
```
import os
import numpy as np
import napari

volume = np.random.random((5, 768, 1024))
viewer = napari.Viewer(ndisplay=3)
layer_norm = viewer.add_image(
        volume,
        visible=False,
    )
layer_norm.interpolation = 'nearest' # or linear, bessel, etc. (bessel is slow!)
```

I do get a warning though:
```
DeprecationWarning: Interpolation setting is deprecated since 0.4.17. Please use interpolation2d or interpolation3d
```
but that's un-related.

**Comment by kephale** [comment] 2023-05-18 11:59
I also don't get this issue with the code @psobolewskiPhD shared in either ipython or running as a script when testing with current `main`.

**Comment by psobolewskiPhD** [comment] 2023-05-18 12:47
Thanks for checking @kephale 
Going to close—there's a number of PRs that have touched that code in the past **3 years** 🤯 not going to bisect the fix. If it's still a thing, we can always reopen.

**Closed as completed** 2023-05-18 12:47 UTC
Labels: bug, priority:high
