### ISSUE TITLE
Can't run the source code because of the napari._version

### ISSUE THREAD

**Issue by LZY-SPCA** [napari/napari#6983] opened 2024-06-13 07:22 UTC
### 🐛 Bug Report

I want to run the souce code of napari in pycharm, but there is something wrong with napari._version in io.py. It doesn't look like there is a module named napari._version. I tried to use __version__ in napari only but it raised an InvalidVersion exception with an output of "Invalid version:'not-installed'".

### 💡 Steps to Reproduce

run `__main__.py` under napari

### 🌎 Environment

Python: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.26.4
SciPy: 1.13.1
Dask: 2024.5.2
VisPy: 0.14.2
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.7
npe2: 0.7.5

OpenGL:
  - GL version:  4.6.0 Compatibility Profile Context 24.5.1.240502
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 3072x1920, scale 1.0
  - screen 2: resolution 4608x2592, scale 1.0

Settings path:
  - C:\Users\LZY\AppData\Local\napari\.venv_bac5904ed74be86e33a186102191391224af3686\settings.yaml
Plugins:
  - napari: 0.4.19.post1 (77 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.1.10 (2 contributions)

**Comment by Czaki** [comment] 2024-06-13 07:44
You need to install napari in editable mode to execute it from source (`pip install -e ./path_to_napari`)

**Comment by jni** [comment] 2024-06-13 08:12
I'm going to close this since it is not a bug with napari, but if you have issues with @Czaki's suggested fix @LZY-SPCA then feel free to keep discussing here! 🙏

**Closed as completed by jni** 2024-06-13 08:12 UTC
Labels: bug
