### ISSUE TITLE
Save window state doesn't save open plugins

### ISSUE THREAD

**Issue by shamus-li** [napari/napari#6136] opened 2023-08-11 03:43 UTC
## 🐛 Bug

The "save window state" setting does not retain the dock widgets that were open upon closing and reopening napari.

## To Reproduce

1. Open napari and activate various plugins.
2. Go to Settings and check the "save window state" option.
3. Close napari.
4. Reopen napari.

As far as I understand, the widgets that were open should be restored, but the normal blank napari window opens instead.

## Environment

napari: 0.4.18
Platform: macOS-14.0-arm64-arm-64bit
System: MacOS 14.0
Python: 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Qt: 6.5.2
PyQt6: 
NumPy: 1.25.2
SciPy: 1.11.1
Dask: 2023.8.0
VisPy: 0.12.2
magicgui: 0.7.2
superqt: 0.5.0
in-n-out: 0.1.8
app-model: 0.2.0
npe2: 0.7.2

OpenGL:
- GL version: 2.1 Metal - 86
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1512x982, scale 2.0

Settings path:
- /Users/shamus/Library/Application Support/napari/venv_76f82552ad566365ec5f35f0d9b6cbf79dcb2d8e/settings.yaml

## Additional context

I can also reproduce this issue on PyQt5, and also on a Windows platform.

**Comment by jni** [comment] 2023-08-11 05:36
@sha-moose actually that is not currently the intention. napari settings apply only to "bare napari" and not to plugins (since the settings apply regardless of which plugins you have installed). And indeed dock widgets might include widgets added in scripts that napari knows nothing about.

In the future, it's certainly possible that we update this. One particular feature we've been discussing is "startup items" that include plugin contributions, so that would be a natural place for this ("start plugin widgets X, Y, and Z upon napari launch").

**Comment by sha-moose** [comment] 2023-08-11 22:14
I see. It was a little confusing since plugins also provide widgets, but I look forward to that startup items feature in the future. Marking this as closed since this is not a bug.

**Closed as completed by sha-moose** 2023-08-11 22:14 UTC
Labels: feature
