### ISSUE TITLE
No napari viewer in Visual Studio Code

### ISSUE THREAD

**Issue by sebherbert** [napari/napari#2626] opened 2021-04-28 09:45 UTC
## 🐛 Bug

No napari viewer in Visual Studio Code

## To Reproduce

1. Start Visual Studio Code 
2. In the integrated terminal 
2. Create and activate a conda environment
3. Use the `conda install -c conda-forge napari` to install the library
4. import napari
5. start napari

```
herber0000@pdw12:/media/herber0000/Data/Projects/IAP_Project670/Devel/imcftodo-670$ conda activate iap670-env
(iap670-env) herber0000@pdw12:/media/herber0000/Data/Projects/IAP_Project670/Devel/imcftodo-670$ ipython
Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import napari
/home/herber0000/miniconda3/envs/iap670-env/lib/python3.8/site-packages/napari/_qt/__init__.py:37: UserWarning: 
    napari was tested with QT library `>=5.12.3`.
    The version installed is 5.9.7. Please report any issues with this
    specific QT version at https://github.com/Napari/napari/issues.
    
  warn(message=warn_message)

In [2]: napari
Out[2]: <module 'napari' from '/home/herber0000/miniconda3/envs/iap670-env/lib/python3.8/site-packages/napari/__init__.py'>
```

## Expected behavior

I am working on 3D stacks in Python using skimage, I was hoping here to open a viewer and later open the images I'm working on in a napari viewer.

## Environment

I'm using Linux Mint 20 and VSC version: 1.55.2

 - Any other relevant information:

I've tested the same process in a normal terminal and napari opens as expected. Let me know if I can add anything else!

**Comment by jni** [comment] 2021-04-28 09:58
You are opening ipython in the VSCode terminal, whereas I expect you are just typing "napari" in the normal terminal. :blush: To get a napari viewer in IPython, you need to make it (`viewer = napari.Viewer()`) or use one of the `view_*` functions (e.g. `viewer = napari.view_image(a_numpy_array)`).

You can read more about this in our [getting started tutorial](https://napari.org/tutorials/fundamentals/getting_started.html).

I'm closing this now as I'm pretty certain it's not a bug, but feel free to keep asking us questions! We love helping newcomers get started with napari! :blush:

**Comment by jni** [comment] 2021-04-28 09:58
(not to mention scikit-image, btw! :smiley:)

**Closed as completed by jni** 2021-04-28 09:58 UTC

**Comment by sebherbert** [comment] 2021-04-28 10:10
Thanks! It was indeed my issue! 
I didn't realize that there are different ways to call the viewer depending on the environment! 

Thanks for the welcome and very fast support!
