### ISSUE TITLE
Accessing viewer mouse clicks more easily from plugin

### ISSUE THREAD

**Issue by sejalsrivastava1** [napari/napari#4976] opened 2022-08-23 21:10 UTC
## 🚀 Feature
@viewer.mouse_drag_callbacks within plugin

## Motivation

I've been unable to gain responsiveness (especially accessing the position of a mouse click relative to a layer) from the viewer when clicking on a layer, even while overriding qt's mousePressEvent method. It would be nice to be able to use @viewer.mouse_drag_callbacks within a plugin, similar to how it can be used when making a napari gui outside of a plugin. Calculating position relative to a layer so far has been extremely difficult and time consuming and I would prefer to be able to do it easily in the same way as I can outside of a plugin.

## Pitch

I would like to be able to easily access mouse clicks within the viewer in a plugin context, preferably without using PyQt5.

## Alternatives

Continue using PyQt5.

**Comment by Czaki** [comment] 2022-08-23 21:35
> Calculating position relative to a layer so far has been extremely difficult and time consuming

What did you mean? Did you want layer coordinates, world coordinates, or canvas (pixel) coordinates?

**Comment by tathey1** [comment] 2022-08-23 22:08
@Czaki I believe the action that @sejalsrivastava1 is interested in is clicking on a component in a labels layer, then allowing a plugin to access that component's label number.

@sejalsrivastava1 and I are working together - we have been able to:
1.  use magic factory to create a napari plugin with a widget ([here](https://github.com/neurodata/brainlit/blob/develop/brainlit/napari_viterbrain/viterbrain_plugin.py)) 
2. use decorators such as `@viewer.mouse_drag_callbacks.append` to write custom scripts that access layer values from clicks (e.g. [here](https://github.com/neurodata/brainlit/blob/a059f75975d114edbc6fbe0379ffaee9485cd3ce/experiments/ViterBrain/scripts/napari_gui.py#L144))

However we want to combine the two. We do not know how to use mouse bindings (`@viewer.mouse_drag_callbacks.append`) in the context of an official napari plugin (`@magic_factory`) that napari will find and add to the plugin dropdown options.

**Comment by tathey1** [comment] 2022-08-23 22:25
In fact, I think that knowing how to create a plugin that simply changes the color of a component in a labels layer when you click on it would help us solve our problem.

**Comment by Czaki** [comment] 2022-08-23 22:44
At first, the magic factory is for the simplest plugins, and more complex one should use [`Container`](https://napari.org/magicgui/usage/_autosummary/magicgui.widgets.Container.html) or QtWidgets directly. 

For accessing to another plugin widget there is [`viewer.window.add_plugin_dock_widget`](https://github.com/napari/napari/blob/392c4bd9ae95fafc2096f05c698f1473b2e32c1d/napari/_qt/qt_main_window.py#L651)

Currently, we found that there is a bug in setting a chosen color for components, but the discussion about this is on [zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/labels.20.28direct.29/near/294911191)

In general, each layer has two attributes: [`position`](https://github.com/napari/napari/blob/392c4bd9ae95fafc2096f05c698f1473b2e32c1d/napari/layers/base/base.py#L176) and [`coordinates`](https://github.com/napari/napari/blob/392c4bd9ae95fafc2096f05c698f1473b2e32c1d/napari/layers/base/base.py#L169). Tee second one may be more interesting for you to determine which component is clicked. 

Most probably, you would like to calculate and assign a new value of `color` property of `Labels` layer, but because of the bug mentioned above, it will not work as expected until we solve it.

**Comment by alisterburt** [comment] 2022-08-25 17:16
Welcome @sejalsrivastava1  and @tathey1 !

To add a little clarity around what @Czaki mentioned, I think the key insight here is that the `magic_factory` API does not give access to the viewer (by design, this allows us to understand what comes in and out of the plugin widget without surprising behaviour)

https://github.com/napari/cookiecutter-napari-plugin/blob/c0a345adbb4087a84f5b6c3f38f6eb9292c01401/%7B%7Bcookiecutter.plugin_name%7D%7D/src/%7B%7Bcookiecutter.module_name%7D%7D/_widget.py#L37-L39

For these more complex cases, the solution is to use a plugin API which gives access to the viewer, and thus also `viewer.mouse_drag_callbacks` -> in this case the `add_dock_widget` API is suitable, it provides a mechanism for accessing the viewer instance

https://github.com/napari/cookiecutter-napari-plugin/blob/c0a345adbb4087a84f5b6c3f38f6eb9292c01401/%7B%7Bcookiecutter.plugin_name%7D%7D/src/%7B%7Bcookiecutter.module_name%7D%7D/_widget.py#L18-L34

Does this make things clearer?

**Comment by alisterburt** [comment] 2022-08-25 17:16
I am going to close this please reopen if you feel the issue has not been addressed!

**Closed as completed by alisterburt** 2022-08-25 17:16 UTC
Labels: feature

**Comment by tathey1** [comment] 2022-08-25 17:44
Thanks so much @alisterburt and @Czaki ! We'll take a look at your tips and come back if things are still unclear. Cheers.
