### ISSUE TITLE
Labels layer with autogenerated pyramid levels shows artifacts

### ISSUE THREAD

**Issue by aeisenbarth** [napari/napari#2922] opened 2021-06-25 19:45 UTC
## 🐛 Bug

When loading a label layer with multiscale pyramids (e.g. from ome-zarr), randomly colored pixels can occur at the contours of labeled regions. This indicates additional label values differing from the labeled region's value, which might be caused by downsampling with interpolation or antialiasing. 

![image](https://user-images.githubusercontent.com/54448967/123475467-b7ace100-d5fb-11eb-95c7-dbda61287692.png)

In my case I originally used `skimage.transform.rescale(array, scale=0.5, order=0, anti_aliasing=False, preserve_range=True).astype(np.uint)`. I could confirm that all my multiscale levels were all uint images with the same set of values.

This seems to be caused when Napari autogenerates additional multiscale levels (the ome-zarr file might contain just as many levels as considered sufficient by the generator, but may still be valid). The downscaling method does maybe not visually impact normal image layers, but for labels layers it does, since arbitrary colors can be assigned to regions.

## To Reproduce

```python
import napari
import numpy as np
from skimage.draw import circle

# Draw a curved segmentation with a label value greater 1. Due to varying boundary 
# direction, incorrect downsampling will produce a range of intensity values.
label_image_0 = np.zeros((2048, 2048), dtype=np.uint)
label_image_0[circle(r=1024, c=1024, radius=1000)] = 10
label_image_1 = np.zeros((1024, 1024), dtype=np.uint)
label_image_1[circle(r=512, c=512, radius=500)] = 10
pyramid = [label_image_0, label_image_1]

viewer = napari.Viewer()
viewer.add_labels(pyramid, name="label_image")
napari.run()
```

## Expected behavior

When zooming in and out, a each region should be displayed with a single color without that boundary pixels change color.

## Environment

napari: 0.4.9
Platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.10
System: Ubuntu 18.04.5 LTS
Python: 3.8.5 (default, Sep 4 2020, 07:30:14) [GCC 7.3.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.20.1
SciPy: 1.6.1
Dask: 2021.01.1
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 390.143
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.3
- napari-ome-zarr: 0.1.1
- scikit-image: 0.4.9
- svg: 0.1.4

**Comment by sofroniewn** [comment] 2021-06-26 19:56
> The downscaling method does maybe not visually impact normal image layers, but for labels layers it does, since arbitrary colors can be assigned to regions.

yikes, thanks for flag - we should get on fixing this!

**Comment by alisterburt** [comment] 2021-07-08 23:56
tried to reproduce locally and I can't see any of the artefacts shown, my environment for comparison...

napari: 0.4.11.dev31+gd488fa88
Platform: macOS-11.2.1-x86_64-i386-64bit
System: MacOS 11.2.1
Python: 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:27:35)  [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.6.6

OpenGL:
  - GL version:  2.1 Metal - 71.0.7
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1440x900, scale 2.0

Plugins:
  - console: 0.0.3
  - scikit-image: 0.4.11.dev31+gd488fa88
  - svg: 0.1.5

**Comment by sofroniewn** [comment] 2021-07-09 00:11
@nclack did you also tell me that you tried to reproduce but couldn't? Maybe this was broken in `0.4.9` but is now fixed on master?

**Comment by nclack** [comment] 2021-07-09 16:27
I also couldn't reproduce. I see:

![image](https://user-images.githubusercontent.com/98295/125108984-c2ae4980-e0b0-11eb-8141-7d3c5b383227.png)

I tried on 0.4.9 and master on a few different systems.  Here's the info for the linux one:

napari: 0.4.9
Platform: Linux-5.11.0-7620-generic-x86_64-with-glibc2.33
System: Pop!_OS 21.04
Python: 3.9.5 (default, Jun  4 2021, 12:28:51)  [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.7.0

OpenGL:
  - GL version:  4.6.0 NVIDIA 465.31
  - MAX_TEXTURE_SIZE: 32768

Screens:
  - screen 1: resolution 1920x1080, scale 1.0

Plugins:
  - console: 0.0.3
  - scikit-image: 0.4.9
  - svg: 0.1.5

**Comment by aeisenbarth** [comment] 2021-07-09 16:48
I tried again and I noticed that an environment variable was set, namely `NAPARI_OCTREE=1` as workaround for https://github.com/napari/napari/issues/1942.

When set to `0`, the issue does not occur. So it seems not to be a bug in the default code, but probably only in the octree code.

**Comment by nclack** [comment] 2021-07-09 17:04
ah. I'll take a look.

**Comment by sofroniewn** [comment] 2021-07-09 19:57
> ah. I'll take a look.

We can in theory disable the autogeneration, or maybe only do it for image data, or maybe have one method for labels data that uses something like a mode operation to downsample and another method for image data that uses something like a mean operation. In general I think we've found that often when we autogenerate though it causes us problems eventually

**Comment by psobolewskiPhD** [comment] 2023-07-17 23:16
Octree has been removed: https://github.com/napari/napari/pull/5816
and I cannot reproduce this on 0.4.18.
Updated snippet for circle deprecation:
```
import napari
import numpy as np
from skimage.draw import disk

# Draw a curved segmentation with a label value greater 1. Due to varying boundary 
# direction, incorrect downsampling will produce a range of intensity values.
label_image_0 = np.zeros((2048, 2048), dtype=np.uint)
label_image_0[disk(center=(1024, 1024), radius=1000)] = 10
label_image_1 = np.zeros((1024, 1024), dtype=np.uint)
label_image_1[disk(center=(512, 512), radius=500)] = 10
pyramid = [label_image_0, label_image_1]
viewer.add_labels(pyramid, name="label_image")
```

Note: I do see a brief glitch with the thumbnail while zooming, but that's a different issue.

**Closed as completed by psobolewskiPhD** 2023-07-17 23:16 UTC
Labels: bug, contribute:good first issue
