### ISSUE TITLE
Function will not be called if a `FunctionGui` is removed or closed before the actual function call

### ISSUE THREAD

**Issue by hanjinliu** [napari/napari#3371] opened 2021-09-11 14:18 UTC
## 🐛 Bug

When I use a `FunctionGui` as a dialog box, I want to close the widget after it is called.

I connected a close function to the push button changed event. It worked fine with `FunctionGui` alone but If I added it into napari as a dock widget, function was not called. Strangely, if I make a new `FunctionGui` and add to napari again, I worked.

## To Reproduce

1. Run following code.

```python
from magicgui import magicgui
import napari
viewer = napari.Viewer()

@magicgui
def f(x:int):
    print(locals())

dock = viewer.window.add_dock_widget(f, name="test")

@f._call_button.changed.connect
def close(e):
    # either or both of the next two lines will raise same problem.
    viewer.window.remove_dock_widget(dock)
    f.native.close()
```

2. Click "Run" button &rarr; Nothing printed
3. Make new object and click "Run" button &rarr; Printed
```python
@magicgui
def f(x:int):
    print(locals())

dock = viewer.window.add_dock_widget(f, name="test")

@f._call_button.changed.connect
def close(e):
    viewer.window.remove_dock_widget(dock)
    f.native.close()
```

4. Run without napari &rarr; Printed.

```python
@magicgui
def f(x:int):
    print(locals())

@f._call_button.changed.connect
def close(e):
    f.native.close()
f.show(True)
```

## Environment

napari: 0.4.11
Platform: Windows-10-10.0.19042-SP0
Python: 3.9.6 (default, Aug 18 2021, 15:44:49) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.20.3
SciPy: 1.6.2
Dask: 2021.08.1
VisPy: 0.8.1

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.8681
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1368x912, scale 2.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.11
- svg: 0.1.5

 - Any other relevant information:

## Additional context

magicgui: 0.2.10

**Comment by tlambert03** [comment] 2021-09-11 15:58
I'm not able to reproduce that first observation, where clicking run prints nothing:

https://user-images.githubusercontent.com/1609449/132953838-92e2b808-03cb-45ab-aa77-56075d7aef17.mov

(checked out magicgui 0.2.10 and current napari).

I'll try to test on windows later?

**Comment by tlambert03** [comment] 2021-09-11 16:24
side question though: would it be sufficient for you to use `f.called.connect(...)` instead of `f._call_button.changed.connect(...)` ?  That really is the intended API for this use case anyway.

**Comment by hanjinliu** [comment] 2021-09-11 22:56
Yes, `f.called.connect` works pretty fine, so I have no reason to continue using `f._call_button` 😅

**Comment by tlambert03** [comment] 2021-09-11 23:15
ok, let's go with that then :) `func.called` is emitted [after the function is called](https://github.com/napari/magicgui/blob/f41a37e7eeb8d6d7d16fae9be4a5a885bab03eef/magicgui/widgets/_function_gui.py#L298), so you're guaranteed to have the function executed before closing the widget.  The private `_call_button` is probably not a good target for connection.  thanks!

**Closed as completed by tlambert03** 2021-09-11 23:15 UTC
Labels: bug
