### ISSUE TITLE
One test from napari.layers.points is not working

### ISSUE THREAD

**Issue by ziyuanzhao2000** [napari/napari#6276] opened 2023-09-28 00:04 UTC
## 🐛 Bug

It seems that there's something not quite right with how napari currently handles point layer with default properties choices but no point. As a result, one of the test is not passing (at least for me).

## To Reproduce

I try to run this test:
```
def test_empty_points_with_properties_list():
    """Test instantiating an empty Points layer with properties
    stored in a list

    See: https://github.com/napari/napari/pull/1069
    """
    properties = {'label': ['label1', 'label2'], 'cont_prop': [0]}
    pts = Points(property_choices=properties)
    current_props = {k: np.asarray(v[0]) for k, v in properties.items()}
    np.testing.assert_equal(pts.current_properties, current_props)

    # add two points and verify the default property was applied
    pts.add([10, 10])
    pts.add([20, 20])
    props = {
        'label': np.array(['label1', 'label1']),
        'cont_prop': np.array([0, 0], dtype=float),
    }
    np.testing.assert_equal(pts.properties, props)
```

But then I see the following error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 test_empty_points_with_properties_list()

Cell In[2], line 10, in test_empty_points_with_properties_list()
      2 """ Test instantiating an empty Points layer with properties
      3 stored in a list
      4 See: https://github.com/napari/napari/pull/1069
      5 """
      6 properties = {
      7     'label': ['label1', 'label2'],
      8     'cont_prop': [0],
      9 }
---> 10 pts = napari.layers.Points(properties=properties)
     11 current_props = {k: np.asarray(v[0]) for k, v in properties.items()}
     12 np.testing.assert_equal(pts.current_properties, current_props)

File ~/mambaforge/envs/cylinter_test/lib/python3.11/site-packages/napari/layers/points/points.py:437, in Points.__init__(self, data, ndim, features, feature_defaults, properties, text, symbol, size, edge_width, edge_width_is_relative, edge_color, edge_color_cycle, edge_colormap, edge_contrast_limits, face_color, face_color_cycle, face_colormap, face_contrast_limits, out_of_slice_display, n_dimensional, name, metadata, scale, translate, rotate, shear, affine, opacity, blending, visible, cache, property_choices, experimental_clipping_planes, shading, canvas_size_limits, antialiasing, shown)
    434 # Save the point coordinates
    435 self._data = np.asarray(data)
--> 437 self._feature_table = _FeatureTable.from_layer(
    438     features=features,
    439     feature_defaults=feature_defaults,
    440     properties=properties,
    441     property_choices=property_choices,
    442     num_data=len(self.data),
    443 )
    445 self._text = TextManager._from_layer(
    446     text=text,
    447     features=self.features,
    448 )
    450 self._edge_width_is_relative = False

File ~/mambaforge/envs/cylinter_test/lib/python3.11/site-packages/napari/layers/utils/layer_utils.py:951, in _FeatureTable.from_layer(cls, features, feature_defaults, properties, property_choices, num_data)
    925 """Coerces a layer's keyword arguments to a feature manager.
    926 
    927 Parameters
   (...)
    948     that length is not equal to the given num_data.
    949 """
    950 if properties is not None or property_choices is not None:
--> 951     features = _features_from_properties(
    952         properties=properties,
    953         property_choices=property_choices,
    954         num_data=num_data,
    955     )
    956 return cls(features, defaults=feature_defaults, num_data=num_data)

File ~/mambaforge/envs/cylinter_test/lib/python3.11/site-packages/napari/layers/utils/layer_utils.py:1073, in _features_from_properties(properties, property_choices, num_data)
   1069         values = (
   1070             properties[name] if name in properties else [None] * num_values
   1071         )
   1072         properties[name] = pd.Series(values, dtype=dtype)
-> 1073 return _validate_features(properties, num_data=num_data)

File ~/mambaforge/envs/cylinter_test/lib/python3.11/site-packages/napari/layers/utils/layer_utils.py:1001, in _validate_features(features, num_data)
    997     features = {
    998         key: np.array(value, copy=False) for key, value in features.items()
    999     }
   1000 index = None if num_data is None else range(num_data)
-> 1001 return pd.DataFrame(data=features, index=index)

File ~/mambaforge/envs/cylinter_test/lib/python3.11/site-packages/pandas/core/frame.py:709, in DataFrame.__init__(self, data, index, columns, dtype, copy)
    703     mgr = self._init_mgr(
    704         data, axes={"index": index, "columns": columns}, dtype=dtype, copy=copy
    705     )
    707 elif isinstance(data, dict):
    708     # GH#38939 de facto copy defaults to False only in non-dict cases
--> 709     mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
    710 elif isinstance(data, ma.MaskedArray):
    711     from numpy.ma import mrecords

File ~/mambaforge/envs/cylinter_test/lib/python3.11/site-packages/pandas/core/internals/construction.py:481, in dict_to_mgr(data, index, columns, dtype, typ, copy)
    477     else:
    478         # dtype check to exclude e.g. range objects, scalars
    479         arrays = [x.copy() if hasattr(x, "dtype") else x for x in arrays]
--> 481 return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)

File ~/mambaforge/envs/cylinter_test/lib/python3.11/site-packages/pandas/core/internals/construction.py:120, in arrays_to_mgr(arrays, columns, index, dtype, verify_integrity, typ, consolidate)
    117         index = ensure_index(index)
    119     # don't force copy because getting jammed in an ndarray anyway
--> 120     arrays, refs = _homogenize(arrays, index, dtype)
    121     # _homogenize ensures
    122     #  - all(len(x) == len(index) for x in arrays)
    123     #  - all(x.ndim == 1 for x in arrays)
   (...)
    126 
    127 else:
    128     index = ensure_index(index)

File ~/mambaforge/envs/cylinter_test/lib/python3.11/site-packages/pandas/core/internals/construction.py:608, in _homogenize(data, index, dtype)
    605         val = lib.fast_multiget(val, oindex._values, default=np.nan)
    607     val = sanitize_array(val, index, dtype=dtype, copy=False)
--> 608     com.require_length_match(val, index)
    609     refs.append(None)
    611 homogenized.append(val)

File ~/mambaforge/envs/cylinter_test/lib/python3.11/site-packages/pandas/core/common.py:576, in require_length_match(data, index)
    572 """
    573 Check the length of data matches the length of the index.
    574 """
    575 if len(data) != len(index):
--> 576     raise ValueError(
    577         "Length of values "
    578         f"({len(data)}) "
    579         "does not match length of index "
    580         f"({len(index)})"
    581     )

ValueError: Length of values (2) does not match length of index (0)
```
## Expected behavior

Expect that the test pass

**Comment by psobolewskiPhD** [comment] 2023-09-28 02:29
Hmm, I cannot reproduce with my fresh 3.11 napari dev environment (`pip install -e .[dev]`), arm64 macOS.
```
pytest napari/layers/points/_tests/test_points.py             (napari-311) ─╯
============================= test session starts ==============================
platform darwin -- Python 3.11.5, pytest-7.4.2, pluggy-1.3.0
PyQt5 5.15.9 -- Qt runtime 5.15.8 -- Qt compiled 5.15.8
rootdir: /Users/piotrsobolewski/Dev/napari
configfile: pyproject.toml
plugins: hypothesis-6.87.0, qt-4.2.0, napari-0.5.0a2.dev356+g62cd9ed88, cov-4.1.0, napari-plugin-engine-0.2.0, npe2-0.7.2, pretty-1.2.0
collected 155 items                                                            

napari/layers/points/_tests/test_points.py ............................. [ 18%]
........................................................................ [ 65%]
......................................................                   [100%]

============================= slowest 10 durations =============================
0.98s call     napari/layers/points/_tests/test_points.py::test_add_colormap[edge]
0.14s setup    napari/layers/points/_tests/test_points.py::test_empty_points
0.14s call     napari/layers/points/_tests/test_points.py::test_empty_points_with_properties
0.10s call     napari/layers/points/_tests/test_points.py::test_selecting_points
0.09s call     napari/layers/points/_tests/test_points.py::test_to_mask_2d_with_size_4_bottom_right
0.08s call     napari/layers/points/_tests/test_points.py::test_new_point_size_editable[size-20]
0.08s call     napari/layers/points/_tests/test_points.py::test_copy_and_paste
0.07s call     napari/layers/points/_tests/test_points.py::test_text_from_property_value[properties0]
0.05s call     napari/layers/points/_tests/test_points.py::test_shown_view_size_and_view_data_have_the_same_dimension
0.04s call     napari/layers/points/_tests/test_points.py::test_thumbnail_with_n_points_greater_than_max
Results (5.52s):
       155 passed
```
Can you post output of `napari --info` and/or your env details?

**Comment by ziyuanzhao2000** [comment] 2023-09-28 02:34
Napari info output:
```
(cylinter_test) [data] napari --info                                 22:33:37 
napari: 0.4.18
Platform: macOS-12.1-arm64-arm-64bit
System: MacOS 12.1
Python: 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:26:40) [Clang 14.0.6 ]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.24.3
SciPy: 1.11.1
Dask: 2023.6.0
VisPy: 0.12.1
magicgui: 0.7.3
superqt: 0.5.4
in-n-out: 0.1.8
app-model: 0.2.1
npe2: 0.7.2

OpenGL:
  - GL version:  2.1 Metal - 76.3
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1512x982, scale 2.0

Settings path:
  - /Users/ziyuanzhao/Library/Application Support/napari/cylinter_test_bf12ff2d49b2bb7b62fddf54c51c2262514476c3/settings.yaml
Plugins:
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
  - napari: 0.4.18 (77 contributions)
  - napari-console: 0.0.8 (0 contributions)
  - napari-svg: 0.1.10 (2 contributions)
  - ome-types: 0.3.2 (4 contributions)
```

My env:
```
(cylinter_test) [data] mamba list                                    22:33:44 
# packages in environment at /Users/ziyuanzhao/mambaforge/envs/cylinter_test:
#
# Name                    Version                   Build  Channel
abseil-cpp                20211102.0           hc377ac9_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
aom                       3.6.0                h313beb8_0  
app-model                 0.2.1              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyhd3eb1b0_0  
appnope                   0.1.2           py311hca03da5_1001  
arrow-cpp                 11.0.0               hc7aafb3_2  
asciitree                 0.3.3                      py_2  
asttokens                 2.0.5              pyhd3eb1b0_0  
attrs                     22.1.0          py311hca03da5_0  
aws-c-common              0.6.8                h80987f9_1  
aws-c-event-stream        0.1.6                h313beb8_6  
aws-checksums             0.1.11               h80987f9_2  
aws-sdk-cpp               1.8.185              ha71a6ea_1  
babel                     2.11.0          py311hca03da5_0  
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      1.0                    openblas  
blosc                     1.21.3               h313beb8_0  
bokeh                     3.2.1           py311hb6e6a13_0  
boost-cpp                 1.73.0              h1a28f6b_12  
bottleneck                1.3.5           py311ha0d4635_0  
brotli                    1.0.9                h1a28f6b_7  
brotli-bin                1.0.9                h1a28f6b_7  
brotlipy                  0.7.0           py311h80987f9_1002  
brunsli                   0.1                  hc377ac9_1  
bzip2                     1.0.8                h620ffc9_4  
c-ares                    1.19.1               h80987f9_0  
ca-certificates           2023.08.22           hca03da5_0  
cachey                    0.2.1              pyh9f0ad1d_0    conda-forge
cellcutter                0.2.7                      py_0    labsyspharm
certifi                   2023.7.22       py311hca03da5_0  
cffi                      1.15.1          py311h80987f9_3  
cfitsio                   3.470                h7f6438f_7  
charls                    2.2.0                hc377ac9_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4           py311hca03da5_0  
click-default-group       1.2.2           py311hca03da5_0  
cloudpickle               2.2.1           py311hca03da5_0  
colorama                  0.4.6           py311hca03da5_0  
comm                      0.1.2           py311hca03da5_0  
contourpy                 1.0.5           py311h48ca7d4_0  
cryptography              41.0.3          py311hd4332d6_0  
cssselect2                0.2.1              pyh9f0ad1d_1    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0  
cylinter                  0.0.47                   pypi_0    pypi
cyrus-sasl                2.1.28               h9131b1a_1  
cython                    3.0.0           py311h80987f9_0  
cytoolz                   0.12.0          py311h80987f9_0  
dask                      2023.6.0        py311hca03da5_0  
dask-core                 2023.6.0        py311hca03da5_0  
dataclasses               0.8                pyh6d0b6a4_7  
dav1d                     1.2.1                h80987f9_0  
debugpy                   1.6.7           py311h313beb8_0  
decorator                 5.1.1              pyhd3eb1b0_0  
dill                      0.3.7           py311hca03da5_0  
distributed               2023.6.0        py311hca03da5_0  
docformatter              1.5.1              pyhd8ed1ab_0    conda-forge
docstring_parser          0.15               pyhd8ed1ab_0    conda-forge
docutils                  0.16            py311hca03da5_2  
elementpath               2.5.3              pyhd8ed1ab_0    conda-forge
entrypoints               0.4             py311hca03da5_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.5.0                h313beb8_0  
fasteners                 0.16.3             pyhd3eb1b0_0  
fontconfig                2.14.1               hee714a5_2  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.10.4               h1192e45_0  
freetype-py               2.2.0              pyhd3eb1b0_0  
fsspec                    2023.4.0        py311hca03da5_0  
gettext                   0.21.0               h13f89a0_1  
gflags                    2.2.2                hc377ac9_0  
giflib                    5.2.1                h80987f9_3  
glib                      2.69.1               h514c7bf_2  
glog                      0.5.0                hc377ac9_0  
grpc-cpp                  1.48.2               hc60591f_1  
gst-plugins-base          1.14.1               h313beb8_1  
gstreamer                 1.14.1               h80987f9_1  
hdbscan                   0.8.33          py311hb49d859_3    conda-forge
heapdict                  1.0.1              pyhd3eb1b0_0  
hsluv                     5.0.3           py311hca03da5_0  
icu                       68.1                 hc377ac9_0  
idna                      3.4             py311hca03da5_0  
imagecodecs               2023.1.23       py311h5e7c512_0  
imageio                   2.31.1          py311hca03da5_0  
imagesize                 1.4.1           py311hca03da5_0  
importlib-metadata        6.0.0           py311hca03da5_0  
importlib_metadata        6.0.0                hd3eb1b0_0  
in-n-out                  0.1.8              pyhd8ed1ab_0    conda-forge
ipykernel                 6.25.0          py311hb6e6a13_0  
ipython                   8.15.0          py311hca03da5_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
jedi                      0.18.1          py311hca03da5_1  
jinja2                    3.1.2           py311hca03da5_0  
joblib                    1.2.0           py311hca03da5_0  
jpeg                      9e                   h80987f9_1  
jsonschema                4.17.3          py311hca03da5_0  
jupyter_client            8.1.0           py311hca03da5_0  
jupyter_core              5.3.0           py311hca03da5_0  
jxrlib                    1.1                  h1a28f6b_2  
kiwisolver                1.4.4           py311h313beb8_0  
krb5                      1.20.1               hf3e1bf2_1  
lazy_loader               0.2             py311hca03da5_0  
lcms2                     2.12                 hba8e193_0  
lerc                      3.0                  hc377ac9_0  
libaec                    1.0.4                hc377ac9_1  
libavif                   0.11.1               h80987f9_0  
libboost                  1.73.0              h49e8a49_12  
libbrotlicommon           1.0.9                h1a28f6b_7  
libbrotlidec              1.0.9                h1a28f6b_7  
libbrotlienc              1.0.9                h1a28f6b_7  
libclang                  14.0.6          default_h1b80db6_1  
libclang13                14.0.6          default_h24352ff_1  
libcurl                   8.2.1                h3e2b118_0  
libcxx                    14.0.6               h848a8c0_0  
libdeflate                1.17                 h80987f9_0  
libedit                   3.1.20221030         h80987f9_0  
libev                     4.33                 h1a28f6b_1  
libevent                  2.1.12               h02f6b3c_1  
libffi                    3.4.4                hca03da5_0  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libiconv                  1.16                 h1a28f6b_2  
libllvm14                 14.0.6               h7ec7a93_3  
libnghttp2                1.52.0               h62f6fdd_1  
libopenblas               0.3.21               h269037a_0  
libpng                    1.6.39               h80987f9_0  
libpq                     12.15                h02f6b3c_1  
libprotobuf               3.20.3               h514c7bf_0  
libsodium                 1.0.18               h1a28f6b_0  
libsqlite                 3.43.0               hb31c410_0    conda-forge
libssh2                   1.10.0               h02f6b3c_2  
libthrift                 0.15.0               h73c2103_2  
libtiff                   4.5.1                h313beb8_0  
libwebp                   1.3.2                ha3663a8_0  
libwebp-base              1.3.2                h80987f9_0  
libxml2                   2.10.4               h372ba2a_0  
libxslt                   1.1.37               habca612_0  
libzlib                   1.2.13               h53f4e23_5    conda-forge
libzopfli                 1.0.3                hc377ac9_0  
llvm-openmp               14.0.6               hc6e5704_0  
llvmlite                  0.40.0          py311h514c7bf_0  
locket                    1.0.0           py311hca03da5_0  
lxml                      4.9.3           py311h50ffb84_0  
lz4                       4.3.2           py311h80987f9_0  
lz4-c                     1.9.4                h313beb8_0  
magicgui                  0.7.3              pyhd8ed1ab_0    conda-forge
markdown-it-py            2.2.0           py311hca03da5_1  
markupsafe                2.1.1           py311h80987f9_0  
matplotlib                3.7.2           py311hca03da5_0  
matplotlib-base           3.7.2           py311h7aedaa7_0  
matplotlib-inline         0.1.6           py311hca03da5_0  
mdurl                     0.1.0           py311hca03da5_0  
msgpack-python            1.0.3           py311h48ca7d4_0  
munkres                   1.1.4                      py_0  
mypy_extensions           1.0.0           py311hca03da5_0  
mysql                     5.7.24               ha71a6ea_2  
napari                    0.4.18             pyhd8ed1ab_2    conda-forge
napari-console            0.0.8              pyhd8ed1ab_0    conda-forge
napari-plugin-engine      0.2.0              pyhd8ed1ab_2    conda-forge
napari-svg                0.1.10             pyhd8ed1ab_0    conda-forge
natsort                   7.1.1              pyhd3eb1b0_0  
ncurses                   6.4                  h313beb8_0  
nest-asyncio              1.5.6           py311hca03da5_0  
networkx                  3.1             py311hca03da5_0  
npe2                      0.7.2              pyhd8ed1ab_0    conda-forge
numba                     0.57.1          py311h7aedaa7_0  
numcodecs                 0.11.0          py311h313beb8_0  
numexpr                   2.8.4           py311h6dc990b_1  
numpy                     1.24.3          py311hb57d4eb_0  
numpy-base                1.24.3          py311h1d85a46_0  
numpydoc                  1.5.0           py311hca03da5_0  
ome-types                 0.3.2              pyhd8ed1ab_0    conda-forge
openjpeg                  2.3.0                h7a6adac_2  
openssl                   3.0.11               h1a28f6b_2  
orc                       1.7.4                hdca1487_1  
packaging                 23.1            py311hca03da5_0  
pandas                    2.0.3           py311h7aedaa7_0  
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.4.0           py311hca03da5_0  
pcre                      8.45                 hc377ac9_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.4.0           py311h313beb8_1  
pint                      0.22               pyhd8ed1ab_1    conda-forge
pip                       23.2.1          py311hca03da5_0  
platformdirs              3.10.0          py311hca03da5_0  
ply                       3.11            py311hca03da5_0  
pooch                     1.4.0              pyhd3eb1b0_0  
prompt-toolkit            3.0.36          py311hca03da5_0  
psutil                    5.9.0           py311h80987f9_0  
psygnal                   0.9.4              pyhd8ed1ab_0    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pyarrow                   11.0.0          py311h7575258_1  
pycparser                 2.21               pyhd3eb1b0_0  
pydantic                  1.10.8          py311h80987f9_0  
pygments                  2.15.1          py311hca03da5_1  
pynndescent               0.5.10          py311hca03da5_0  
pyopengl                  3.1.1a1         py311hca03da5_0  
pyopenssl                 23.2.0          py311hca03da5_0  
pyparsing                 3.0.9           py311hca03da5_0  
pypdf2                    2.10.5          py311hca03da5_0  
pyproject_hooks           1.0.0           py311hca03da5_0  
pyqt                      5.15.7          py311h313beb8_0  
pyqt5-sip                 12.11.0         py311h313beb8_0  
pyrsistent                0.18.0          py311h80987f9_0  
pysocks                   1.7.1           py311hca03da5_0  
python                    3.11.0          h3ba56d0_1_cpython    conda-forge
python-build              0.10.0          py311hca03da5_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-lmdb               1.4.1           py311h313beb8_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
python_abi                3.11                    4_cp311    conda-forge
pytz                      2023.3.post1    py311hca03da5_0  
pywavelets                1.4.1           py311h80987f9_0  
pyyaml                    6.0             py311h80987f9_1  
pyzmq                     25.1.0          py311h313beb8_0  
qt-main                   5.15.2               h9b4df51_9  
qt-webengine              5.15.9               h2903aaf_7  
qtconsole-base            5.4.3              pyha770c72_0    conda-forge
qtpy                      2.2.0           py311hca03da5_0  
qtwebkit                  5.212                h19f419d_5  
re2                       2022.04.01           hc377ac9_0  
readline                  8.2                  h1a28f6b_0  
reportlab                 3.6.12          py311h80987f9_0  
requests                  2.31.0          py311hca03da5_0  
rich                      13.3.5          py311hca03da5_0  
scikit-image              0.20.0          py311h313beb8_0  
scikit-learn              1.2.2           py311h313beb8_1  
scipy                     1.11.1          py311hc76d9b0_0  
seaborn                   0.12.2          py311hca03da5_0  
setuptools                68.0.0          py311hca03da5_0  
shellingham               1.5.0           py311hca03da5_0  
sip                       6.6.2           py311h313beb8_0  
six                       1.16.0             pyhd3eb1b0_1  
snappy                    1.1.9                hc377ac9_0  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
sphinx                    4.4.0              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
sqlite                    3.41.2               h80987f9_0  
stack_data                0.2.0              pyhd3eb1b0_0  
superqt                   0.5.4              pyh9208f05_2    conda-forge
svglib                    1.5.1              pyhd8ed1ab_0    conda-forge
tbb                       2021.8.0             h48ca7d4_0  
tblib                     1.7.0              pyhd3eb1b0_0  
threadpoolctl             2.2.0              pyh0d69192_0  
tifffile                  2023.4.12       py311hca03da5_0  
tinycss2                  1.2.1           py311hca03da5_0  
tk                        8.6.12               hb8d0fd4_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1           py311hca03da5_0  
tomli-w                   1.0.0              pyhd3eb1b0_0  
toolz                     0.12.0          py311hca03da5_0  
toposort                  1.10               pyhd8ed1ab_0    conda-forge
tornado                   6.3.2           py311h80987f9_0  
tqdm                      4.65.0          py311hb6e6a13_0  
traitlets                 5.7.1           py311hca03da5_0  
typer                     0.9.0           py311hca03da5_0  
typing-extensions         4.7.1           py311hca03da5_0  
typing_extensions         4.7.1           py311hca03da5_0  
tzdata                    2023c                h04d1e81_0  
umap-learn                0.5.3           py311hca03da5_0  
untokenize                0.1.1                      py_0    conda-forge
urllib3                   1.26.16         py311hca03da5_0  
utf8proc                  2.6.1                h1a28f6b_0  
vispy                     0.12.1          py311h1eb0683_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1           py311hca03da5_1  
wheel                     0.38.4          py311hca03da5_0  
wrapt                     1.14.1          py311h80987f9_0  
xmlschema                 1.11.3             pyhd8ed1ab_0    conda-forge
xsdata                    23.7               pyhd8ed1ab_0    conda-forge
xyzservices               2022.9.0        py311hca03da5_1  
xz                        5.4.2                h80987f9_0  
yaml                      0.2.5                h1a28f6b_0  
zarr                      2.16.0             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                hc377ac9_0  
zfp                       1.0.0                h313beb8_0  
zict                      2.2.0           py311hca03da5_0  
zipp                      3.11.0          py311hca03da5_0  
zlib                      1.2.13               h53f4e23_5    conda-forge
zstd                      1.5.5                hd90d995_0  
```

**Comment by ziyuanzhao2000** [comment] 2023-09-28 02:46
I think I understand what is going on:

I realized that I copied the test from [here](https://github.com/napari/napari/pull/1069/commits/e13fa8133e51d4a1d001d3b85c8812056f7c82dd), which is outdated compared to the latest test.

And there's a subtle difference between that test and the latest test in that the latest test uses the `property_choice` param, but the old test uses `property`.

But I find this change confusing given the explanation here in this [merge](https://github.com/napari/napari/pull/1069#issuecomment-608997761), which explicitly says "If the user does not provide data (i.e., the layer is empty), but does provide properties, the dictionary passed to properties will be interpreted as Points.property_choices and Points.properties will be initialized with a dictionary with the appropriate keys and empty numpy arrays for the values." 

However, if we change `property_choice` in the current test back to `property` I think it will break the test. In that case, maybe the current implementation does not satisfy the behavior expected from that merge?

Please try this and let me know what you think, thanks!

**Comment by andy-sweet** [comment] 2023-09-28 20:32
Sorry for the confusion here!

I think this is mostly a documentation problem. The [docstrings for `properties` and `property_choices` @ v0.4.18](https://github.com/napari/napari/blob/82a6f31b5c29602a02bb19b7e35ec59e9ed03a64/napari/layers/points/points.py#L66) loosely suggest the current behavior (i.e. pass `property_choices` not `properties` when you want to specify the choices), though they could be more detailed.

We do have some [plans to improve the general documentation](https://github.com/napari/docs/issues/23) on this topic, which will also handle the [in progress properties->features deprecation work](https://github.com/napari/napari/issues/3911) which is part of the larger #2866. Sorry, more changes! We will try to have this in a better, less confusing state for the next minor release (v0.5.0).

> In that case, maybe the current implementation does not satisfy the behavior described in that merge?

Agreed. But that merge is over three years old. The initial behavior was deprecated (with a warning), which was then [removed (fairly late) for v0.4.18](https://github.com/napari/napari/pull/5041/files#diff-0f1588377d587a70fc4bdd1dc19e5d0036b98029a9651f7d3a7d87815ab4f210L348).

So I'm reluctant to make any code changes to make the old test case pass again. @ziyuanzhao2000 : what do you think?

**Comment by ziyuanzhao2000** [comment] 2023-09-29 15:38
Hi Andy, thank you very much for the quick response! 

I agree that it will be very beneficial to have some "high level documentation that explains how users and developers should think about properties [and features]," as you mentioned in the other open issue. Yes, I've also become aware of the properties to features depreciation work going on, after reading through some of the issues here and posts in the Napari forum. I think it will be a good idea to warn users about this in the main documentation as well.

No need to change the old test case, but as you said, things could be explained better. I'm happy to help

**Comment by psobolewskiPhD** [comment] 2024-01-22 22:09
Given the original issue was due to a version mismatch I'm going to close this. 
With 0.4.18 being released the proper doc strings should also be on stable now.

**Closed as completed by psobolewskiPhD** 2024-01-22 22:09 UTC
Labels: bug
