### ISSUE TITLE
Improve labels painting performance

### ISSUE THREAD

**Issue by YubinXie** [napari/napari#647] opened 2019-10-30 19:38 UTC
## 🐛 Bug

Hi, Thanks for the great tool.
My project involves large amount and size data, and sometimes the python window dies (no responding) after click around. I was wondering if there is any setting that I can assign more memory/cpu to this task? Thanks!

I installed the Napari in a new Conda environment with pip under Mac OS. When I open 1 image of 2000x3000 and just try to add label. It took 5s for the annotation to show up after I draw something. 
## To Reproduce

1. Open a 2000x3000 image in napari 
2. Add a label layer
3. Draw the label

## Expected behavior
The draw is very smooth under 200x300 image, but in 2000x3000, it lags too much and it is impossible to work with it.

## Environment

napari, 0.2.2
Qt, 5.13.1
NumPy, 1.17.3
SciPy, 1.3.1
VisPy, 0.6.1
scikit-image, 0.16.2

Platform: Darwin-18.7.0-x86_64-i386-64bit
Python:   3.7.4 (default, Aug 13 2019, 15:17:50)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Backend:  PySide2
GL version:  '2.1 ATI-2.11.20'
MAX_TEXTURE_SIZE: 16384
 - Any other relevant information:
Mac OS

**Comment by YubinXie** [comment] 2019-10-30 19:45
This problem is worse when I open 0 image and just try to add label. It took 5s for the annotation to show up after I draw something.

**Comment by AhmetCanSolak** [comment] 2019-10-30 20:07
Hi @YubinXie ,

Thank you for the issue. would you mind opening a bug report with more details?

**Comment by AhmetCanSolak** [comment] 2019-10-30 20:08
or change this issue into a bug report please

**Comment by YubinXie** [comment] 2019-10-30 20:11
sure. Do you know how to change to bug report?

**Comment by AhmetCanSolak** [comment] 2019-10-30 20:12
(get the template from bug report issue, tell us more about your setup and your data)

**Comment by YubinXie** [comment] 2019-10-30 20:25
Got it. Updated!

**Comment by sofroniewn** [comment] 2019-10-30 20:35
Hi @YubinXie - we currently have some problems with drawing in our labels layer when images get large, see #569, this will likely be fixed by #204, but we still havn't gotten that implemented.

Sorry that it's not performing for you right now. We can try and get something like #204 in sooner rather than later!

**Comment by YubinXie** [comment] 2019-10-30 20:38
Sounds great. No worries. Look forward to seeing the update!

I am new in community and I want to ask a quick question here. When I load a folder and it shows in Z axis order in the viewer, is it possible to add file name to the image so that I know what I am looking at?

**Comment by sofroniewn** [comment] 2019-10-30 21:27
Welcome! Right now there is no way to add a name to each z-slice, but you can add a name to each layer. If this is something you are interested in can you make a new "Feature Request" issue that explains in a little more detail your usage and what you want to see

**Comment by YubinXie** [comment] 2019-10-30 21:57
Got it. Thanks.
For the layer name, it only displays at the left part (and long name does not show properly), and it is hard to see when I do grid view mode. Is there a way to put layer name around the image?

**Comment by sofroniewn** [comment] 2019-10-31 00:05
If you click inside the textbox you'll be able to scroll to see the rest of the name, we can work on improving that. You might also be interested in the text layer that we are currently working on #600

**Comment by YubinXie** [comment] 2019-10-31 02:13
@sofroniewn Sounds great.

One thing that might be related to this issue is that, I found the saved Label file for 33x2028x2048 is 1GB due to its data type being int64. For the label, int from 0-128 should be enough. Will this help the annotation speed?

**Comment by sofroniewn** [comment] 2019-10-31 02:23
i'm not sure, but i can do some benchmarking to see. I don't think it will be as large a difference as getting #204 in. you can do something like `your_data = your_data.astype(np.uint8)` before adding it to the labels layer to check yourself

**Comment by YubinXie** [comment] 2019-10-31 02:34
did not realize I can change the data type directly. I tried it and I think it is faster (although still lagging)

**Comment by jni** [comment] 2019-10-31 03:04
@YubinXie the issue is that the workflow of converting labels to *well-separated floats* is done in the CPU. So that will always be quite slow for large images. @sofroniewn some quick gains might be had by changing that code to use float32 instead of system floats (usually 64). The copy in vispy might be significantly faster than a cast.

**Comment by sofroniewn** [comment] 2019-11-25 23:11
I'm closing as duplicate of #569 which is currently being worked on

**Closed as completed by sofroniewn** 2019-11-25 23:11 UTC
Labels: bug, performance
