### ISSUE TITLE
documentation links to Github teams are not public

### ISSUE THREAD

**Issue by neuromusic** [napari/napari#1868] opened 2020-11-13 22:51 UTC
## 📚 Documentation

In the napari docs on governance, there are links to Github teams, but these links are not public.

For example, in the "[core developers](https://napari.org/docs/0.3.8/developers/GOVERNANCE.html#core-developers)" section, core developers are not listed, but instead a link is provided to https://github.com/orgs/napari/teams/core-devs. However, as a member of the public, this link returns a 404 error for me.

Suggested changes:

- Remove links to Github teams for the Steering Council and Core Develoeprs
- Explicitly list core developers in governance docs

**Comment by sofroniewn** [comment] 2020-11-14 21:19
This is a duplicate of #1190, we were going to fix during the website reorg, but that's still in progress, so we should just do a quick fix now. we can leave both this and #1190 open till that's done

**Comment by andy-sweet** [comment] 2022-06-07 16:31
@neuromusic : as part of #1190 there were some updates to this as the core developers are listed now, though that needs to be kept in sync. But the links to the GitHub teams ([core-devs](https://github.com/orgs/napari/teams/core-devs) and [steering council](https://github.com/orgs/napari/teams/steering-council)) are still present.

If I try to open these in a Chrome incognito window, then GitHub asks me to login. If I'm logged in to this account, then I can see both, but then I'm a member of the napari organization and the core-devs team.

If you could try out the behavior from your side, maybe we could close this now? Or if based on that behavior, you still think we should remove the team links, then I guess this should stay open.

**Comment by neuromusic** [comment] 2022-06-08 03:29
I'm also a member of the napari org & the behavior for me is the same.

So I'm not sure what the behavior is like for someone logged into Github but not a member of the napari org.

**Comment by andy-sweet** [comment] 2022-06-08 20:22
I had @junxini test this as someone with a GitHub account, but not currently a member of the napari organization.

They can see [the napari organization](https://github.com/orgs/napari/people) fine, but get a 404 for the [core-devs](https://github.com/orgs/napari/teams/core-devs) and [steering council](https://github.com/orgs/napari/teams/steering-council) teams.

So leaving this open for now.

I'm not an admin/owner of the napari org, but I might check with someone who is to see if we could just make those teams public if that's possible. Seems like an alternative to removing the links, which are fairly useful and represent the best source of truth in terms of actual control of the repos.

**Comment by andy-sweet** [comment] 2022-06-08 20:49
Seems like making teams public is not supported yet: https://github.community/t/why-is-my-github-team-isnt-visible-to-anyone-outside-my-organization/251617

There's some related discussion in #1190 and #816 around whether to keep the team links or not. I don't feel strongly as the core dev members and steering council are listed and linked to, but if someone else does feel free to pick up this issue and open a PR that removes them.

**Comment by sofroniewn** [comment] 2022-07-13 20:31
> Seems like making teams public is not supported yet: https://github.community/t/why-is-my-github-team-isnt-visible-to-anyone-outside-my-organization/251617

Yes this is unfortunately not supported.

I think we should open a PR to remove links that don't work when not logged in and replace them with links to the about page in the napari.org site. Maybe @chili-chiu can make sure this is on the radar for the docs working group. should be a very minimal PR. Thanks!!!

**Comment by psobolewskiPhD** [comment] 2024-02-22 02:57
The `project and team` page now lists people rather than linking to the problematic GitHub pages.
I'm going to close, we have a related issue at the docs repo.

**Closed as completed by psobolewskiPhD** 2024-02-22 02:57 UTC
Labels: bug, documentation
