### ISSUE TITLE
Viewer buttons pannel dissapear when oppening a image in napari (windows 11)

### ISSUE THREAD

**Issue by Dr2-JMM** [napari/napari#5573] opened 2023-02-18 19:48 UTC
## 🐛 Bug

After launching napari viewer from the anaconda terminal and open an image (any image, even the samples) the canvas windows resize, and buttons panel disappears behind the windows taskbar turning them unaccessible.

Buttons can be shown when reducing the window and maximizing it again but as soon the cursor moves the window is resized and the buttons panel disappears again.  

## To Reproduce

1. Launch napari from anaconda terminal
2. Open any image
3. Try to use the buttons panel 

## Expected behavior

When opening the image I do not expect any change in the viewer window nor in the canvas

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.17
Platform: Windows-10-10.0.22621-SP0
Python: 3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.23.5
SciPy: 1.10.0
Dask: 2022.7.0
VisPy: 0.11.0
magicgui: 0.6.1
superqt: unknown
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.2

OpenGL:
- GL version: 4.6.0 - Build 30.0.101.1692
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 960x540, scale 2.0

 - Any other relevant information:

## Additional context
 Windows information
Edition	Windows 11 Home
Version	22H2
Installed on	‎09/‎02/‎2023
OS build	22621.1265
Serial number	PF2ZYHT6
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by Czaki** [comment] 2023-02-18 20:11
> * screen 1: resolution 960x540, scale 2.0

I think that the source of the problem is here. Until now, we do not support very small napari windows. Could you share your use case for why you need to use napari on such a small screen?

**Comment by Dr2-JMM** [comment] 2023-02-18 20:54
I´m actually using a Lenovo Ideapad 5 15ITL05 with 15.6'' screen and a 1920 x1080 resolution (same as resolution 960x540, scale 2.0?) which is my working laptop, I wouldn't consider it as a small screen, it is rather a standard size for laptop.

**Comment by Czaki** [comment] 2023-02-18 21:13
960x540 is a small area. 

It means that I do not understand. What is the resolution visible in your system settings?

**Comment by psobolewskiPhD** [comment] 2023-02-18 21:29
Maybe some HIDPI setting gone amok?

**Comment by Dr2-JMM** [comment] 2023-02-18 21:43
@Czaki as I said my resolution is 1920x1080. Not 960x540. Seems to me that napari is providing my resolution as 960x540 times 2, as it says screen 1: resolution 960x540, **scale 2.0**

@psobolewskiPhD it could be, but at the moment this mismatch between app size window and window display only happens with napari.

**Comment by psobolewskiPhD** [comment] 2023-02-18 21:45
Maybe you can try:
`set QT_SCALE_FACTOR=1`
before launching napari?

**Comment by Dr2-JMM** [comment] 2023-02-18 21:58
Thanks @psobolewskiPhD for suggesting but it didn't work.

For clarity some screenshots of my issue:
Before opening the image:
<img width="960" alt="before" src="https://user-images.githubusercontent.com/66313775/219901187-e3418e77-1486-4968-a7e4-e1d26ea03180.png">

And then when opening the image happens this:
<img width="960" alt="after" src="https://user-images.githubusercontent.com/66313775/219901198-0169d1eb-6ee0-447d-a24e-80d66e50ee5c.png">

Buttons panel disappear and it is impossible to use them.

**Comment by psobolewskiPhD** [comment] 2023-02-18 22:08
Oh, OK, that's different.
Can you try without fullscreen mode and see if the window size also changes?
But I think there is still something wrong with the scaling--the napari UI stuff looks huge compared to your Windows stuffs.

another thing to try:
`QT_AUTO_SCREEN_SCALE_FACTOR=1`
edit: actually, maybe you need `QT_AUTO_SCREEN_SCALE_FACTOR=0`

**Comment by Dr2-JMM** [comment] 2023-02-18 22:28
Thanks @psobolewskiPhD the issue is fixed!!

Using:
`set QT_AUTO_SCREEN_SCALE_FACTOR=0`
Before launching napari fixed the issue.

For reference, before fixing the issue, when not using full screen mode I could'n make small enough to fit in the screen.

**Comment by psobolewskiPhD** [comment] 2023-02-18 22:41
Yay! Out of curiosity can you post napari info again with fixed behavior?

**Comment by Czaki** [comment] 2023-02-18 23:44
> I´m actually using a Lenovo Ideapad 5 15ITL05 with 15.6'' screen and a 1920 x1080 resolution (same as resolution 960x540, scale 2.0?) which is my working laptop, I wouldn't consider it as a small screen, it is rather a standard size for laptop.

In general, it is a standard size, but for scaling 1.0. 
Did you scale the interface, or is scale 2.0 some mistake? I remember that sometimes Qt wrong interprets fractional scaling. Or you do not have scaling and for some reason, Qt treats your display as high DPI?

**Comment by Dr2-JMM** [comment] 2023-02-19 00:26
> Yay! Out of curiosity can you post napari info again with fixed behavior?

Yes @psobolewskiPhD here is the napari info, and as expected the resolution is also fixed with a scaling factor of 1, not 2 as before:

napari: 0.4.17
Platform: Windows-10-10.0.22621-SP0
Python: 3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.23.5
SciPy: 1.10.0
Dask: 2022.7.0
VisPy: 0.11.0
magicgui: 0.6.1
superqt: unknown
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.2

OpenGL:
- GL version: 4.6.0 - Build 30.0.101.1692
- MAX_TEXTURE_SIZE: 16384

Screens:
**- screen 1: resolution 1920x1080, scale 1.0**

**Comment by psobolewskiPhD** [comment] 2023-02-19 13:27
@Dr2-JMM 
Glad it's working and yes now the scaling info is correct. This isn't really a napari bug, but rather an issue with your environment, perhaps you migrated computers or used external monitors with some other Qt app (not just python)? It's that or something in your Windows settings...
As your problem is resolved, I'm going to close this, but if the issue recurs or you have a way to replicate it, please feel free to re-open.

**Closed as completed by psobolewskiPhD** 2023-02-19 13:27 UTC
Labels: bug
