### ISSUE TITLE
Napari 0.4.10 not backwards compatible

### ISSUE THREAD

**Issue by ViktorvdValk** [napari/napari#2944] opened 2021-06-29 10:03 UTC
## 🐛 Bug

Upgrading to napari 0.4.10 results in pytest failure, whereas a pytest run with 0.4.8 succeeds.
See [elastix_napari CI](https://github.com/SuperElastix/elastix_napari/runs/2940558731?check_suite_focus=true) for more info.

Pytest indicates that the test functions are missing required arguments, which were previously not necessary.  
Unfortunately the suggested fix (setting the variables with a {'bind': None} dictionary in the decorator doesn't work)
Any suggestions on how to fix this in the plugin?

## To Reproduce

1. Upgrade or install latest napari
2. clone elastix_napari plugin repo
3. run pytest 

## Expected behavior

Pytest should succeed like it did with napari 0.4.8

## Environment

python > 3.7 (somehow python 3.7 still succeeds)

 - Any other relevant information:

The failure has something to do with arguments to the plugin tests that are now required, but setting them with the suggested dictionary ( {'bind': None} ) doesn't work.

**Comment by tlambert03** [comment] 2021-06-29 12:19
thanks for the report @ViktorvdValk and sorry about that.
looks like that's a regression that git bisect puts at #2662 ... will have a look today

**Comment by tlambert03** [comment] 2021-06-29 16:44
fix in #2949 @ViktorvdValk ...

but, just so you have a better sense for what's causing this (and a workaround before the next update).  This is a bug caused by napari not calling the function that tells magicgui how to handle napari types (`utils._magicgui.register_types_with_magicgui`) before your program calls magicgui.

It _should_ be the case that you simply annotating something as a `'napari.layers.Image'` triggers that call (and that's what is fixed in #2949).  I fixed a similar bug in #2891, but I apologize that I missed this one.

In the meantime, if you want to just make your tests work again, you could add `import napari.types` somewhere before your `@magic_factory` usage.

**Comment by ViktorvdValk** [comment] 2021-06-30 07:41
@tlambert03 
Thanks a lot for the quick response.
And your workaround does the trick on the CI. 👍

**Closed as completed** 2021-07-06 00:31 UTC
Labels: bug
