### ISSUE TITLE
Windows SmartScreen warns during app installation

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#3339] opened 2021-09-05 11:13 UTC
## 🐛 Bug

Hi all,

I just installed the napari bundled app 0.4.11. At the beginning of the installation, this warning shows up:
![image](https://user-images.githubusercontent.com/12660498/132124532-283a1162-665f-45c2-894d-5271817a561a.png)

The German error message basically says that the author of the program cannot be verified,

## To Reproduce

1. Download the bundled app for Windows from https://github.com/napari/napari/releases/tag/v0.4.11
2. Open the zip file
3. double click the napari.msi installer

## Expected behavior

If the msi file is signed properly, this error should go away.

## Environment

It is a pretty normal Windows PC I'm running on:
![image](https://user-images.githubusercontent.com/12660498/132124651-f68a4911-11cf-4c47-ab8e-9e84712d414c.png)

 - Please copy and paste the information at napari info option in help menubar here:
 - napari: 0.4.11
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
Qt: 5.15.2
PySide2: 5.15.2
NumPy: 1.19.3
SciPy: 1.7.1
Dask: 2021.08.1
VisPy: 0.8.1

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.8681
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1280x800, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image
- svg: 0.1.5

 - Any other relevant information:

**Comment by tlambert03** [comment] 2021-09-05 12:09
> If the msi file is signed properly, this error should go away.

yep, this is a known issue.  We've got the same thing on mac.  (see  the [installation guide](https://napari.org/tutorials/fundamentals/installation#installing-as-a-bundled-app) where we alert people to the warning for the mac install).  In this case "signing properly" takes money, and someone to buy napari an official developer certificate.

We're well aware of this, so I'm going to close this issue as a duplicate of others.  but cc @goanpeca  and @jaimergp just as a reminder ... who are ultimately working on getting the bundle into app stores (which would also require an official cert).

also cc @sofroniewn: this comes up so often, any chance CZI wants to actually buy that cert?

**Closed as completed by tlambert03** 2021-09-05 12:09 UTC
Labels: bug

**Comment by haesleinhuepf** [comment] 2021-09-05 12:13
> I'm going to close this issue as a duplicate of others. 

Ok, cool. Can you point me to one?

Thanks

**Comment by tlambert03** [comment] 2021-09-05 12:46
it came up in napari/napari#496, napari/napari#1289, napari/napari#1074...
I created a dedicated task instead of a bug so that it's clear this requires someone to pay money. https://github.com/napari/packaging/issues/25

**Comment by haesleinhuepf** [comment] 2021-09-05 19:17
Thanks! 🙂
