### ISSUE TITLE
Unable to open another viewer after closing another one in the same program

### ISSUE THREAD

**Issue by JoOkuma** [napari/napari#3033] opened 2021-07-12 21:11 UTC
## 🐛 Bug

Napari can't open multiple viewers inside a for loop, note that they are not being executed at the same time.
This used to work in 0.4.6, it might be related to #2977.

I'm not sure where to start to fix this.

## To Reproduce

1. Execute the following code.

```python3
import napari

for i in range(10):
    viewer = napari.Viewer()
    napari.run()
```
2. Close the first viewer.
3. Subsequent viewers do not work as expected, they open all at once.

## Expected behavior

To open the next viewer as usual after the previous one was closed.

## Environment

```
napari: 0.4.10
Platform: Linux-5.8.0-59-generic-x86_64-with-glibc2.17
System: Ubuntu 20.04.2 LTS
Python: 3.8.10 (default, Jun 4 2021, 15:09:15) [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.05.1
VisPy: 0.7.0

OpenGL:
- GL version: 4.6.0 NVIDIA 460.73.01
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 3440x1440, scale 1.0

Plugins:
- console: 0.0.3
- napari-dexp: 0.0.1.dev1
- napari-ibacktracker: 0.1.dev20+gb5119c1
- napari-interactive-segm: 0.1.dev3+g23d71b8.d20210712
- napari-simple-crop: 0.1.dev3+g1852e97
- scikit-image: 0.4.10
- svg: 0.1.5
```

**Comment by JoOkuma** [comment] 2021-07-12 21:17
After commenting [these lines](https://github.com/napari/napari/blob/4cfe609c71bd5d9347e3c93da0bec20dd662768d/napari/_qt/qt_event_loop.py#L351-L353) it works as expected.

**Comment by JoOkuma** [comment] 2021-07-12 21:24
When used as below it works as expected.
```python3
import napari

for i in range(10):
    viewer = napari.Viewer()
    viewer.show(block=True)
```

**Comment by tlambert03** [comment] 2021-07-12 21:58
assuming you were running that code in IPython, this is by design

The default in IPython is to not block (unless, as you discovered, you use `block=True`).  Note, if you put your first code example in a file `test.py` and ran `python test.py` ... it _would_ behave as you expected, but if you run the identical code in IPython, it assumes you want interactive usage unless you explicitly ask for it to block (i.e. it assumes you want to manipulate the viewer object programmatically while it's being shown).
You can read a bit more about our IPython behavior [here](https://napari.org/guides/stable/event_loop.html#in-ipython-or-jupyter-notebook)... and if you _don't_ want that to be the default behavior, see the tip the link above:

```
from napari.utils import get_settings

get_settings().application.ipy_interactive = False
# now each call to napari.run() will block
```

**Comment by JoOkuma** [comment] 2021-07-12 23:08
Thanks for the reply, Talley.

This is happening when I run from Terminator or the vscode terminal, both inside a conda environment. I also tried opening a fresh terminal and it still happens.

**Comment by tlambert03** [comment] 2021-07-12 23:09
in the terminal though, how do you launch python?

**Comment by JoOkuma** [comment] 2021-07-12 23:13
`python debug.py`

**Comment by tlambert03** [comment] 2021-07-12 23:14
and debug.py contains the script above?

```py
import napari

for i in range(10):
    viewer = napari.Viewer()
    napari.run()
```

**Comment by JoOkuma** [comment] 2021-07-12 23:37
Yes

**Comment by tlambert03** [comment] 2021-07-12 23:43
we might need to pair up on this then, when I run that script above as `python debug.py` (regardless of which terminal I run it in, VScode, iterm2, terminal, etc...) shows each viewer, one at a time...  if I run it as `ipython -i x.py` then they all show up at once as you're describing.  you don't happen to have any aliases that turn `python` into `ipython` do you?

also just want to clarify: is your concern/experience that all 10 viewers open immediately?  or that only one opens, and then once you close it the program exists?  (the title of this posts kinda suggests that you only get one viewer, but your post said "they open all at once.")

if you want to screencap, that might be helpful

**Comment by JoOkuma** [comment] 2021-07-13 17:29
The recording tool that I use in Linux stopped working, so I tried reproducing the bug on my mac laptop and it does not happen. I can show it at the next napari meeting if I can't reproduce it until then.

**Comment by tlambert03** [comment] 2021-07-13 17:30
ok, good to know that it's linux specific, will try to reproduce

**Comment by tlambert03** [comment] 2021-07-13 17:36
perfect, i see something funny now.  actually reminds me of https://github.com/napari/napari/pull/2276 a little bit

will try to see what's going on with the event loop in linux that might cause this

**Comment by tlambert03** [comment] 2021-07-13 17:43
oh you know what, I think this is also related to https://github.com/napari/napari/issues/2925
the main point there is that when the console is open, our "_ipython_has_eventloop" logic gets confused, and it no longer blocks on the event loop.  Can you confirm this for me?  first try `pip uninstall napari-console` (you can reinstall it afterwards) and tell me if that fixes it?
Then, reinstall `napari-console`, make certain that you haven't left the console open in the napari window, and then try again?

**Comment by JoOkuma** [comment] 2021-07-13 18:30
You found the issue :). After I uninstalled `napari-console` it worked as intended and when I reinstalled it back the issue returned.

**Comment by tlambert03** [comment] 2021-07-13 18:42
thanks for checking!

**Closed as completed** 2021-09-02 19:58 UTC
Labels: bug
