### ISSUE TITLE
ZARR only readable/viewable after installation of `zarr` package (?)

### ISSUE THREAD

**Issue by vreuter** [napari/napari#6708] opened 2024-03-05 01:15 UTC
### 🐛 Bug Report

I dragged-and-dropped a ZARR folder into a Napari viewer, but there was no plugin capable of reading it. Is it supposed to be the case that `zarr` is required to view data of that format? If so, could it be noted in the docs (sorry if I missed it!)

### 💡 Steps to Reproduce

1. In a clean, active 3.10.13 virtualenv, I installed `napari` with `python -m pip install "napari[all]==0.4.18"` (after having what now seems to be a non-version-specific issue, perhaps, when on the latest version).
2. I opened Napari, with `napari`
3. I dragged a ZARR folder into the viewer.
4. I got a an error:
```console
    247             "Tried to read {path_message} with plugin {plugin}, because it was associated with that file extension/because it is the only plugin capable of reading that path, but it gave an error. Try associating a different plugin or installing a different plugin for this kind of file.",
    248             path_message=f"[{paths[0]}, ...]"
    249             if len(paths) > 1
    250             else paths[0],
    251             plugin=plugin_name,
    252         ),
    253         plugin_name,
    254         paths,
    255     ) from error
    257 return readers

ReaderPluginError: Tried to read /path/to/my.zarr with plugin napari, because it was associated with that file extension/because it is the only plugin capable of reading that path, but it gave an error. Try associating a different plugin or installing a different plugin for this kind of file.
```
5. Closing Napari, installing `zarr` in the environment, and then reopening Napari and trying once more to load the image data behaves as I had anticipated.

### 💡 Expected Behavior

I expected to see the same (roughly) grid of black, white, and grey pixels I'd seen when viewing the same data in `napari` when opened from another environment, in which it happens that `zarr` was installed. From the docs on [viewing large datasets](https://napari.org/stable/tutorials/processing/dask.html) and the existence of this [ZARR reader function](https://github.com/napari/napari/blob/main/napari_builtins/io/_read.py#L105), I'd expected to be able to view the data stored as ZARR without needing to have `zarr` installed in the environment from which I was using Napari.

### 🌎 Environment

napari: 0.4.18
Platform: macOS-13.5.2-arm64-arm-64bit
System: MacOS 13.5.2
Python: 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Qt: 5.15.11
PyQt5: 5.15.10
NumPy: 1.26.4
SciPy: 1.12.0
Dask: 2024.2.1
VisPy: 0.12.2
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.4
npe2: 0.7.4

### 💡 Additional Context

Installing `zarr` "fixed" the problem, but I'd not anticipated needing it and feel it would be good to make that requirement clearer in the docs if it's intended (for viewing ZARR).

**Comment by psobolewskiPhD** [comment] 2024-03-05 01:28
Thanks for raising the issue.
This is actually a duplicate of:
https://github.com/napari/napari/issues/2321

We have a fix open as a PR, need to revisit it:
https://github.com/napari/napari/pull/6297

I'm going to close, but appreciate the bump.
❤️

**Closed as completed by psobolewskiPhD** 2024-03-05 01:28 UTC
Labels: bug

**Comment by vreuter** [comment] 2024-03-05 01:39
Indeed, sorry about that! Thanks @psobolewskiPhD

**Comment by psobolewskiPhD** [comment] 2024-03-05 01:42
No worries, this was actually helpful! Things often slip through the cracks, so we can always use some prompting!
Appreciate your engagement with the project!
❤️
