### ISSUE TITLE
Pyside 5.15.0 breaking buttons?

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1312] opened 2020-05-29 15:19 UTC
## 🐛 Bug

just found that all instances of `QtModePushButton` weren't working for me.  (like the "add layer" buttons)
<img width="148" alt="Screen Shot 2020-05-29 at 11 13 35 AM" src="https://user-images.githubusercontent.com/1609449/83276126-25d76800-a19e-11ea-8ab3-b96e48f6886f.png">

I had pyside 5.15.0 in my environment, and downgraded to 5.14.2 and they worked again...

Can someone else confirm this? 

If so... we should probably release a patch that pins pyside2 < 5.15

**Comment by tlambert03** [comment] 2020-05-29 16:35
another observation... this may be multifactorial, but on my mac (10.13.6), pyside2 5.15.0 breaks a lot more than just buttons:

```
conda create -n test python=3.8
conda activate test
pip install ipython pyside2==5.15
ipython --gui qt
# cannot type anything into the interpreter!

pip install pyside==5.14.2
ipython --gui qt
# works again
```

**Comment by sofroniewn** [comment] 2020-05-29 23:42
Looks like PySide2 `5.15.0` has some changes to threading https://www.qt.io/blog/qt-for-python-5.15.0-is-out and Qt `5.15.0` has some changes around how they are handling their 3D graphics https://www.qt.io/blog/qt-5.15-released in preparation for a `Qt6` release which will be their next major release.

These changes sound pretty major, so pinning `< 5.15.0` sounds good or `==5.14.2.2` - note the extra `.2` there. Maybe @tlambert03 can you confirm that release still works. Maybe @jni and @ziyangczi can look into this too

**Comment by tlambert03** [comment] 2020-05-30 00:46
5.14.2.2 works, but can someone please try the buttons in the first example?  That’s more pressing than the threading at the moment

**Comment by jni** [comment] 2020-05-30 00:56
fwiw I just tested `example/add_image.py` with PySide 5.15 on Linux and it works fine. (ie I can add a points layer no problem.) Testing on my Mac now.

**Comment by tlambert03** [comment] 2020-05-30 00:57
test out the ipython --gui qt thing too while you're at it.  I saw it on two different macs

**Comment by jni** [comment] 2020-05-30 00:59
@tlambert03 which thing exactly?

**Comment by jni** [comment] 2020-05-30 01:00
(btw `--gui qt` is also part of my IPython config. =P)

**Comment by tlambert03** [comment] 2020-05-30 01:00
https://github.com/napari/napari/issues/1312#issuecomment-636068885

**Comment by jni** [comment] 2020-05-30 01:04
Whoa. Yeah same issue! =(

**Comment by jni** [comment] 2020-05-30 01:04
Rename issue "PySide2 5.15 breaking the world"?

**Comment by tlambert03** [comment] 2020-05-30 01:05
well, glad it's not just me.  but sounds like we should probably pin at <5.15

**Comment by jni** [comment] 2020-05-30 01:06
Yeah. I wonder though, with breaking something as big as IPython, whether they will fix this on their end, in which case maybe we should maybe try `!=5.15.0` and cross our fingers?

**Comment by tlambert03** [comment] 2020-05-30 01:09
hmmm I kinda doubt it ...  I fear we may all have to figure out what changed on our end ...  I did create an IPython issue as well: https://github.com/ipython/ipython/issues/12350

**Comment by jni** [comment] 2020-05-30 01:16
> I did create an IPython issue as well

great! Thanks, that's very valuable to get more eyeballs looking at this.

**Comment by jni** [comment] 2020-05-30 01:19
Whooaaaaa, the IPython issue *does* happen on Linux.

**Comment by tlambert03** [comment] 2020-05-30 01:20
# 😫

**Comment by sofroniewn** [comment] 2020-05-30 01:22
I can make an emergency release tonight if we want, I’ll be free in ~30 min

**Comment by tlambert03** [comment] 2020-05-30 01:23
@jni. I'm making a PR... I had made it <5.15 but you pick:  feeling optimistic for !=5.15.0?

**Comment by sofroniewn** [comment] 2020-05-30 01:26
I’d go <, much easier to intentionally fix and release when we want then have to go through another emergency release if it breaks again

**Comment by tlambert03** [comment] 2020-05-31 12:01
nothing figured out yet, just some notes:
I tried to create a minimal example of this button problem by ripping out the bare minimum code that gets us from the `Viewer` down to the `QtViewerPushButton` in the `QtLayerButtons` where the "add layer" buttons live... but it still "works" (in the sense that clicking the buttons calls the callback).

<details>
<summary>minimal example</summary>

```python
from qtpy.QtCore import Qt
from qtpy.QtWidgets import (
    QWidget,
    QApplication,
    QPushButton,
    QMainWindow,
    QHBoxLayout,
    QVBoxLayout,
    QFrame,
    QSplitter,
    QDockWidget,
)


class QtViewerPushButton(QPushButton):
    def __init__(self, button_name, slot=None):
        super().__init__(button_name)
        if slot is not None:
            self.clicked.connect(slot)


class QtLayerButtons(QFrame):
    def __init__(self):
        super().__init__()
        self.newPointsButton = QtViewerPushButton("new_points", lambda: print("click"))
        layout = QHBoxLayout()
        layout.addWidget(self.newPointsButton)
        self.setLayout(layout)


class QtViewerDockWidget(QDockWidget):
    def __init__(self, qt_viewer, widget: QWidget, name: str = ""):
        self.qt_viewer = qt_viewer
        super().__init__(name)
        self.qt_area = Qt.LeftDockWidgetArea
        self.setMinimumHeight(50)
        self.setMinimumWidth(50)
        self.setWidget(widget)
        widget.setParent(self)
        self._widget = widget


class QtViewer(QSplitter):
    def __init__(self, viewer):
        super().__init__()

        self.viewer = viewer
        self.layerButtons = QtLayerButtons()
        layerList = QWidget()
        layerListLayout = QVBoxLayout()
        layerListLayout.addWidget(self.layerButtons)
        layerList.setLayout(layerListLayout)
        self.dockLayerList = QtViewerDockWidget(self, layerList, name="layer list")
        self.dockLayerList.setMaximumWidth(258)
        self.dockLayerList.setMinimumWidth(258)


class Window:
    def __init__(self, qt_viewer: QtViewer, *, show: bool = True):
        self.qt_viewer = qt_viewer
        self._qt_window = QMainWindow()
        self._qt_center = QWidget(self._qt_window)
        self._qt_center.setLayout(QHBoxLayout())
        self._qt_center.layout().addWidget(self.qt_viewer)
        self._qt_center.layout().addWidget(
            QtViewerPushButton("asdf", slot=lambda: print("click"))
        )
        self._qt_window.setCentralWidget(self._qt_center)
        self._qt_window.setFixedSize(500, 300)
        self._add_viewer_dock_widget(self.qt_viewer.dockLayerList)

        if show:
            self._qt_window.resize(self._qt_window.layout().sizeHint())
            self._qt_window.show()

    def _add_viewer_dock_widget(self, dock_widget: QtViewerDockWidget):
        """Add a QtViewerDockWidget to the main window

        Parameters
        ----------
        dock_widget : QtViewerDockWidget
            `dock_widget` will be added to the main window.
        """
        dock_widget.setParent(self._qt_window)
        self._qt_window.addDockWidget(dock_widget.qt_area, dock_widget)


class Viewer:
    def __init__(self):
        qt_viewer = QtViewer(self)
        self.window = Window(qt_viewer, show=True)


app = QApplication([])
v = Viewer()
app.exec_()
```

</details>

**Comment by Czaki** [comment] 2020-06-02 09:41
I'm not sure if it is connected with this Issue but Qt 5.15 remove `xcb` libs form build so it fail to run QApplication because of problem with loading plug-in:

https://codereview.qt-project.org/c/qt/qtbase/+/253905

I need to run install 
```
libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
```
on ubuntu to get test not fail with sigabort (on github actions and Azure pipelines).

**Comment by jni** [comment] 2020-06-14 06:55
I'll also point to @tlambert03's bug report on PySide here:

https://bugreports.qt.io/browse/PYSIDE-1317

it appears things will be fixed in 5.15.1! 🤞

**Comment by tlambert03** [comment] 2020-06-14 11:06
I don’t think the qsocketnotifyer fix in 5.15.1 is going to help us with buttons here. Since I can’t reproduce the bug with a minimal example (above) I think the button thing is a more complicated napari-specific problem

**Comment by tlambert03** [comment] 2020-07-11 01:28
This is also a potentially fun sprint challenge to debug for someone with a lot of experience in Qt (but _not_ a good challenge for Qt beginners!).  to see the problem pip install napari the usual way, then `pip install 'pyqt5>=5.15.0'`... then try to add a new layer using the add layer buttons:

<img width="140" alt="Screen Shot 2020-07-10 at 9 27 03 PM" src="https://user-images.githubusercontent.com/1609449/87213609-1cd8cb00-c2f4-11ea-87a7-d41ebd5f6e7b.png">

in 5.15, they are not currently firing the signals we need to add a new layer.
the buttons are instantiated in [`napari/_qt/qt_viewer_buttons.py`](https://github.com/napari/napari/blob/master/napari/_qt/qt_viewer_buttons.py)

**Comment by joshuawillman** [comment] 2020-08-30 02:18
I know this is mostly related to PySide, but today I upgraded PyQt5 to version 5.15.0 and found that the widgets I tested worked, except for QPushButtons. I just wanted to know if anyone else experienced this.

**Comment by tlambert03** [comment] 2020-08-30 03:24
Yep, it's both pyside and pyqt 5.15... we need to figure out what's going on with buttons in both cases

**Comment by Czaki** [comment] 2020-10-15 12:40
I would like to try to debug this problem but cannot reproduce it. Could Person who meet this problem check on master branch if it stills occurs and then provide detailed information about environment? 
System,
Python version (with information about installation type pure cPython, Anaconda, etc)
Libraries version? 

Try on clean python environment. 

I test on cPython on Ubuntu and Macos.

**Comment by sofroniewn** [comment] 2020-10-15 15:22
> I would like to try to debug this problem but cannot reproduce it. Could Person who meet this problem check on master branch if it stills occurs and then provide detailed information about environment?

@Czaki are you testing on `5.15.1` looks like it contains 400 bug fixes relative to `5.15.0` [according to the Qt docs](https://www.qt.io/blog/qt-5.15.1-released) and came out mid september, which is after the last comment in this thread.

Maybe we just need to skip `5.15.0` and then we'll be ok? It looks like @jni was able to reproduce some of the original problems, so maybe he can check again!

**Comment by tlambert03** [comment] 2020-10-15 18:13
yep, it's fixed on 5.15.1...
see:
https://bugreports.qt.io/browse/QTBUG-85487
https://bugreports.qt.io/browse/QTBUG-84852
https://bugreports.qt.io/browse/QTBUG-84493
https://bugreports.qt.io/browse/QTBUG-84879

**Comment by Czaki** [comment] 2020-10-15 18:40
hm. So maybe there should be check of Qt version and report problem on 5.15.0  during napari start?

**Comment by Czaki** [comment] 2020-10-16 01:18
I do not know if it could produce problem in napari but in PyQt 5.15.1signals are not hashable.

**Closed as completed** 2020-11-01 00:06 UTC
Labels: bug, priority:high
