### ISSUE TITLE
User configurable plugins names and order of appearance in Plugins menu

### ISSUE THREAD

**Issue by SebastienTs** [napari/napari#6410] opened 2023-11-03 15:31 UTC
## 🚀 Feature
User configurable plugins names and order of appearance in Plugins menu.

## Motivation
According to me it's currently the main weakness of Napari (together with the lack of curation of Napari-hub). Having over 30 or 40 plugins with inconsistent naming and ordering is plainly unmanageable.

## Pitch
A configuration file or GUI based plugin namer / order of appearance in Plugins menu sorter (best), or at the very least having the plugins listed in alphabetical order in the Plugins menu. It would be even better if the plugins could be sorted by categories into subfolders, a bit similar to the nice Tools menu coming with napari Assistant.

## Alternatives
None.

**Comment by psobolewskiPhD** [comment] 2024-07-22 00:07
Big part of this is already addressable via NAP-6 https://github.com/napari/napari/issues/7012
However, if I'm reading correctly, this issue does suggest the idea that the end user should be able to reconfigure things, rather than the plugin devs.
@DragaDoncila flagging this for you--not sure how we'd implement letting users change plugin categories/contribution names, but it's a thought.
Otherwise, just tag this with `won't fix` and close in favor of the NAP-6 work.

**Comment by jni** [comment] 2024-07-22 01:14
I do think NAP-6 addresses most of the concerns here ("similar to the nice Tools menu"), but user configuration is still far in the horizon — we are definitely considering it though. I also think that once we have the command palette this will become less of an issue.

**Comment by DragaDoncila** [comment] 2024-07-24 01:07
> or at the very least having the plugins listed in alphabetical order in the Plugins menu.

This, at least, we should absolutely do. So I've added that as an item to #7012. 

Longer term, we do want users to be able to fully customize their app menus, and NAP-6 touches on that in the [User Configuration](https://napari.org/stable/naps/6-contributable-menus.html#user-configuration) paragraph, but I would consider this work post-NAP-6 (and therefore post everything #7012). 

We could co-opt this issue to track the concept of user configurable menus, or we could close this and I open a dedicated one to track. @psobolewskiPhD thoughts?

**Comment by psobolewskiPhD** [comment] 2024-07-24 01:23
I think that if we and plugin developers do a nice job with embracing NAP-6, then users won't want to mess with it?
I get the desire to customize everything, but as a user I find it quite exhausting.
"Customize everything" in my experience is largely a reflection of "we don't care about design and UX at all, you deal with it" 
I like it when things are nice and work out of the box. I think we should aspire to that.

**Comment by jni** [comment] 2024-07-24 02:21
Yeah look, as a longtime Mac user, I definitely appreciate this philosophy @psobolewskiPhD, but I think escape hatches are useful. For example, I *hate* that macOS no longer lets me name desktops. (This was possible in older versions.) So

![por-que-no-los-dos](https://media1.tenor.com/m/O7h_9Qm5lhwAAAAC/thank-you.gif)

**Comment by DragaDoncila** [comment] 2024-07-24 02:26
Yeah I absolutely agree "reconfigure your menu bar" shouldn't be our default answer to issues with easily accessing the tools you need in the UI. However, I think because we have this "third party" - the plugin developer, there's always going to be some edge cases where allowing the user to fully configure the UI will be helpful. I'm thinking, a plugin declares 40 contributions but you only ever use 3, so you want to disable the rest and bring those 3 to the top. Or, you very frequently use two contributions from one plugin and one contribution from another, so you want those to be quick-access at the top level. For many of these "edge-cases" you could build a launch script that idk, opens all the right widgets and puts them where you want them and so on, but that means dropping into python, which for some users may not be a great proposition.

**Comment by psobolewskiPhD** [comment] 2024-07-24 02:36
Y'all aren't wrong. Let's have it on the roadmap but further in the future, after we can evaluate what comes of the new menus.

**Comment by psobolewskiPhD** [comment] 2024-07-28 19:34
Looking a bit deeper think this can be considered a duplicate of the well-thought out: https://github.com/napari/napari/issues/5584
I'm going to close in favor of that one, but will link back to this.

**Closed as completed by psobolewskiPhD** 2024-07-28 19:34 UTC
Labels: feature
