### ISSUE TITLE
translation vector is not scaled when ndisplay changes

### ISSUE THREAD

**Issue by borchardt** [napari/napari#3336] opened 2021-09-04 02:52 UTC
## 🐛 Bug
When using both the `scale` and the `translate` parameters, toggling `ndisplay` from 3 to 2 appears to revert the scaling along the first dimension of any image layer in the viewer. `translate` values for points layers in the viewer are not rescaled in the same way. This means that points which were centered on particular voxels in the 3D view will no longer be centered on those same voxels (and in fact may not be visible at all) in the 2D view.

## To Reproduce

1. Execute the following script:
```
import napari
import numpy as np

data = np.zeros((25,25,25), dtype=bool)
data[13,13,13] = True
points = np.array([[13,13,13]])
viewer = napari.Viewer(ndisplay=3)
scale = np.array([3, 1, 1])
translate = 0.5 * scale
viewer.add_image(data, scale=scale)
viewer.add_points(points, scale=scale, symbol='ring', size=1, face_color='red', edge_color='red', translate=translate)

napari.run()
```
2. Verify that a red point ring is centered on a scaled gray voxel
3. Click the viewer button to toggle `ndisplay` from 3 to 2
4. Scroll to `Z = 13`
5. Verify that you are able to see the voxel from step 2, but not the ring
6. Verify that the ring from step 2 is not visible on any other Z plane
7. Open the viewer console
8. Execute the command `viewer.layers['points'].translate = [0,0,0]`
9. Verify that the point ring is now recentered on the voxel at `Z = 13`

## Expected behavior

When toggling `ndisplay`, a point which is centered on a particular data voxel in the 3D view should be centered on the same voxel in the 2D view.

## Environment

```
napari: 0.4.11
Platform: Linux-5.10.0-7-amd64-x86_64-with-debian-11.0
System: Debian GNU/Linux 11 (bullseye)
Python: 3.7.6 (default, Jan 8 2020, 19:59:22) [GCC 7.3.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.5
SciPy: 1.5.2
Dask: 2.22.0
VisPy: 0.6.4

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.3.4
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 3840x2160, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.11
- svg: 0.1.4
```

## Additional context

n/a

**Comment by borchardt** [comment] 2021-12-15 11:07
Hey all!

Just bumping this issue; still present for me in napari 0.4.12.

All the best!

**Comment by goanpeca** [comment] 2021-12-27 17:33
Hi @Borchardt, thanks for opening the issue. Sorry this feel under the cracks. Thanks for the ping!

---

@napari/core-devs

**Comment by sofroniewn** [comment] 2021-12-29 02:01
Thanks yeah - maybe @grlee77 can take a look at reproducing/ fixing when they get the chance. cc @jni and @andy-sweet who might be interested in this one too as it relates to transforms

**Comment by grlee77** [comment] 2022-01-03 22:07
I think this is the current expected behavior in this case and is likely not a bug. Specifically, on current `main`, you should not need to translate by `0.5 * scale` to get the point to show up as centered in a voxel. We changed the voxel extents a few monts ago so that a voxel of scale (1, 1, 1) at position (0, 0, 0) would have an extent from [-0.5, 0.5] along each axis whereas previously the extent would have been [0, 1]. 

In your case you are placing a point at translation of `0.5 * scale` which is exactly half way between the slider steps. Since the point is only size 1.0 steps in width and is exactly half way between steps, it will not be visible even if the points layer was initialized with `n_dimensional=True`. For size=1.0 and `n_dimensional=False` the `translation` values along the sliced axis will have to be an integer multiple of `scale` in order to see the point in one of the slider positions in the 2D view. Otherwise it falls between slider steps and will not be shown. Alternatively, with a translation of `0.5 * scale` as in your example, if you initialize the point with a size **greater than 1** such as 1.5 and `n_dimensional=True`,  you will see the point showing up (at a reduced size) in both nearby slices (13 and 14).

I would have thought this behavior change would have already taken effect in v0.4.12 too, but local testing seems to confirm that this is apparently not the case. I changed your example to use `translate = np.array([0, 0, 0])` and did a `git bisect` to see at what commit the point appears centered within a voxel. This new, centered behavior on the display seems to start with the following commit b5405402a4fd0af667f5e82e9b00510512d5244c by @brisvag. This is surprising to me because this was a commit removing vendored vispy code and not one of the ones where we changed the image or point layer extents! As mentioned above, the current behavior does seem correct to me, I am just a bit surprised it did not start earlier than that commit.

**Comment by brisvag** [comment] 2022-01-04 14:14
Took a look at it as well, and indeed at step `2.` I'm seeing the point *not centered*, which (as @grlee77 mentioned) is intended. Are you sure that this still happens on main for you @Borchardt ?

> This new, centered behavior on the display seems to start with the following commit b540540 by @brisvag. This is surprising to me because this was a commit removing vendored vispy code and not one of the ones where we changed the image or point layer extents!

This likely happened because with vispy 9.X we fixed some issue with the volume shader, where there was an unintended offset (see vispy/vispy#2239).


As a side note, the example code from above brought up an issue with scale and point sizes that I had forgotten about and should be fixed (ignore the weird line artifact, it's some recording issue):

https://user-images.githubusercontent.com/23482191/148071238-f55dcd12-95d9-46f0-af4e-8a33a91365de.mp4

Old issue about this: #2213.

**Comment by borchardt** [comment] 2022-01-10 12:02
Thanks for your input! I can confirm that I'm no longer seeing this issue when using current main version from GitHub. In this version, the point is not centered on the voxel unless the `translate` vector in the example code is changed from values of 0.5 to values of 0.0 , in which case it remains visible in 2D.

So I guess the issue has been resolved! Huge thanks! :)

**Comment by sofroniewn** [comment] 2022-01-11 03:12
> So I guess the issue has been resolved! Huge thanks! :)

Great!! Thanks all for weighing in, I will close this now :-)

**Closed as completed by sofroniewn** 2022-01-11 03:12 UTC
Labels: bug
