### ISSUE TITLE
Layers and canvas misalignment

### ISSUE THREAD

**Issue by PabloAu** [napari/napari#6306] opened 2023-10-06 08:18 UTC
I am using Napari to visualize particle tracking data. It used to work properly but suddenly I started experiencing a misalignment between the center of the canvas and the layers. Also, if I play the stack or scroll to see temporal evolution, the layers misaligned between themselves. 

I have Napari upgraded to the last version.

 Here I show an image of how Napari displays the layers. (Image is basically cut and half of it hides behind the black canvas background)
![image](https://github.com/napari/napari/assets/42294176/0cdf6c24-3030-4b1e-ac73-86ba5850b548)

This is the piece of code that I am using:

    if Run_Napari:
        print("Rendering annotated stack with Napari...")
        frame_loc = frames[0:Total_frames-1,:,:];
        napari_df = t1.loc[:,['particle','frame','y','x']].to_numpy();
        napari_points = t1.loc[:,['frame','y','x']].to_numpy();
        #napari.view_tracks(napari_df, name='tracklets');
        viewer = napari.Viewer();
        SCALE = (1.0, 1.0, 1.0);
        viewer.add_image(frame_loc, scale=SCALE, name='iSCAT');
        viewer.add_points(napari_points, scale=SCALE, name='localizations',symbol='disc',face_color='transparent',size=5,edge_color='red',edge_width=0.1,opacity=0.5);
        viewer.add_tracks(napari_df, scale=SCALE, name='tracks',color_by='track_id',colormap='turbo',blending='opaque',tail_length=1000,tail_width=0.5);

        if Save_Napari_stack:
            from napari_animation import Animation
            print("Saving annotated stack with Napari...")
            animation = Animation(viewer)
            for i in range(Annotated_frames-2):
                viewer.dims.set_point(0,i);
                animation.capture_keyframe();
            if napari_format_output=='.gif':
                animation.animate(folder + file_list[h][:-4] + "_Annonated_Napari"+napari_format_output,canvas_only=True,fps=fps_napari);
            else:
                animation.animate(folder + file_list[h][:-4] + "_Annonated_Napari" + napari_format_output,quality=quality_napari, canvas_only=True, fps=fps_napari);

**Comment by PabloAu** [comment] 2023-10-06 09:18
I found the origin of the problem. I was using 150% Scale in the Windows Display of my screen. When I changed it to 100%, the problem is solved. 

Is there a way to correct that from Pyhton or Napari, so that I can use the 150% scale in my screen display?

**Comment by brisvag** [comment] 2023-10-06 16:06
Hi @PabloAu, I was about to answer on your post on Imagesc asking to open an issue, but I see you were faster :p This is unfortunately I problem we've seen before, and I don't think anyone found a satisfying solution. I had exactly the same issue on linux when setting a different DPI scaling for my monitor.

I'm not sure if this problem comes from napari messing up something on the QT side, or if it's deeper (vispy canvas)...

**Comment by brisvag** [comment] 2023-10-06 16:29
I just tested on a windows laptop, and I could not reproduce... I also can't reproduce with my linux machine, but I might have forgotten the exact combination of things needed to break it :P Can you paste the output of `napari --info` ?

**Comment by psobolewskiPhD** [comment] 2023-10-06 19:39
I think this is a duplicate of:
https://github.com/napari/napari/issues/6197

But that was reported on linux...

**Comment by psobolewskiPhD** [comment] 2024-02-22 01:52
Going to close as duplicate of https://github.com/napari/napari/issues/6197 which has been observed on windows too. That issue may actually be closed too by a vispy PR...

**Closed as completed by psobolewskiPhD** 2024-02-22 01:52 UTC
Labels: bug
