### ISSUE TITLE
Memory not clean after remove layer

### ISSUE THREAD

**Issue by Czaki** [napari/napari#3124] opened 2021-08-04 10:53 UTC
## 🐛 Bug

When removing a layer from viewer its memory is not released.

## To Reproduce

1. Check memory usage
2. Load multiple heavy files
3. check napari memory usage
4. delete all layers
5. compare memory usage

## Expected behavior

There should be no memory leaks

## Environment
napari: 0.4.11.dev80+g718d50775
Platform: Linux-5.11.0-25-generic-x86_64-with-glibc2.2.5
System: Ubuntu 21.04
Python: 3.8.3 (default, Dec 6 2020, 00:47:20) [GCC 10.2.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.16.5
SciPy: 1.5.1
Dask: 2021.05.0
VisPy: 0.6.4

OpenGL:
- GL version: 4.6.0 NVIDIA 470.57.02
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0
- screen 3: resolution 1920x1080, scale 1.0

Plugins:
- animation: 0.0.2
- console: 0.0.3
- scikit-image: 0.4.11.dev80+g718d50775
- svg: 0.1.5
 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context

Manual call `gc.collect` does not help.

**Comment by tlambert03** [comment] 2021-08-04 10:59
Duplicate of #2027, some work exploring fixes done in #2155

**Comment by Czaki** [comment] 2021-08-04 11:07
I was searching for leak-related issues. Thanks for pointing proper one. If I have a time I will try to debug it.

**Comment by tlambert03** [comment] 2021-08-04 11:30
that would be great!  As shown in #2155, most of the references can be pruned with weakrefs in the proper places... the `ImageSlice`, `ImageSliceData`, and that whole chain of objects is the main problem

**Comment by Czaki** [comment] 2021-09-01 08:29
Partially fixed.

**Comment by willingc** [comment] 2024-11-15 18:23
@Czaki I'm going to close this stale memory leak bug since it is partially fixed. If not fully addressed yet, it should resurface in current memory leak checks.

**Closed as completed by willingc** 2024-11-15 18:23 UTC
Labels: bug
