### ISSUE TITLE
Axes at a fixed position

### ISSUE THREAD

**Issue by hanjinliu** [napari/napari#4089] opened 2022-02-15 07:46 UTC
## 🚀 Feature

It would be nice if I can display axes at a fixed position in a viewer.

## Motivation

In napari, axes are always displayed at the origin of coordinate system. However, it is inconvenient when I'm focusing on a small part of large 3D images. I cannot tell the image orientation unless I zoom it out all the way.

## Pitch

The 3D viewer implemented in the Protein Data Bank is a good example in this point. Its axes are always fixed at the lower-left corner so that I can know the direction at any zoom levels.

![スクリーンショット (6)](https://user-images.githubusercontent.com/40591297/154014337-61130c7c-e78e-4765-9e29-d539b14c1ae6.png)

## Alternatives

A dock widget with a small axes-like object that synchronizes with viewer's camera angle?

**Comment by psobolewskiPhD** [comment] 2022-10-23 18:22
I think this is an important feature request, but it's a duplicate of:
https://github.com/napari/napari/issues/1726
https://github.com/napari/napari/issues/1887
I'll add high-priority to the latter—can we close this?

**Comment by hanjinliu** [comment] 2022-10-23 23:16
agree.

**Closed as completed** 2024-01-02 19:02 UTC
Labels: feature
