### ISSUE TITLE
Add `make_napari_viewer` API/reference docs

### ISSUE THREAD

**Issue by dstansby** [napari/napari#5819] opened 2023-05-10 09:47 UTC
## 📚 Documentation
The `make_napari_viewer` fixture has a docstring in the code file that has some useful info (pasted below), but this doesn't show up anywhere in the `napari` docs (see this [search for make_napari_viewer](https://napari.org/stable/search.html?q=make_napari_viewer)). It would be good to put this info somewhere in the docs.

```
"""A fixture function that creates a napari viewer for use in testing.

    Use this fixture as a function in your tests:

        viewer = make_napari_viewer()

    It accepts all the same arguments as napari.Viewer, plus the following
    test-related paramaters:

    ViewerClass : Type[napari.Viewer], optional
        Override the viewer class being used.  By default, will
        use napari.viewer.Viewer
    strict_qt : bool or str, optional
        If True, a check will be performed after test cleanup to make sure that
        no top level widgets were created and *not* cleaned up during the
        test.  If the string "raise" is provided, an AssertionError will be
        raised.  Otherwise a warning is emitted.
        By default, this is False unless the test is being performed within
        the napari package.
        This can be made globally true by setting the 'NAPARI_STRICT_QT'
        environment variable.
    block_plugin_discovery : bool, optional
        Block discovery of non-builtin plugins.  Note: plugins can still be
        manually registered by using the 'napari_plugin_manager' fixture and
        the `napari_plugin_manager.register()` method. By default, True.

    Examples
    --------
    >>> def test_adding_shapes(make_napari_viewer):
    ...     viewer = make_napari_viewer()
    ...     viewer.add_shapes()
    ...     assert len(viewer.layers) == 1

    >>> def test_something_with_plugins(make_napari_viewer):
    ...     viewer = make_napari_viewer(block_plugin_discovery=False)

    >>> def test_something_with_strict_qt_tests(make_napari_viewer):
    ...     viewer = make_napari_viewer(strict_qt=True)
    """
```

**Comment by Czaki** [comment] 2023-05-10 12:12
As docstring is present and the only problem is the lack of rendering it then the proper place for the issue is the [napari/docs](https://github.com/napari/docs) repository. As a proper issue [exists](https://github.com/napari/docs/issues/150) then I close this.

**Closed as completed by Czaki** 2023-05-10 12:12 UTC
Labels: documentation
