### ISSUE TITLE
permission changed required for singularity build

### ISSUE THREAD

**Issue by truatpasteurdotfr** [napari/napari#4406] opened 2022-04-21 19:24 UTC
## 🐛 Bug
https://github.com/napari/napari/runs/6105312118?check_suite_focus=true
The default permission for the docker artefact is private, the singularity builds needs to have access to the docker image produced.

## To Reproduce

CI building.

## Expected behavior

singularity container produced.

## Additional context

You just need to toggle artefact status from private to public. :P

**Comment by jni** [comment] 2022-07-06 11:49
Yeah it seems to me this should be public, I don't see a reason why it wouldn't be. Let me see where in the settings I can find this. (If someone can point me to an exact spot that would be handy! CC @Czaki)

**Comment by jni** [comment] 2022-07-06 11:51
A quick rummage didn't turn up any relevant settings. If someone tells me *exactly* what I need to change where I will be happy to help!

**Comment by Czaki** [comment] 2022-07-06 12:19
https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility

it looks like is should be possible to be done from organizational setting.

**Comment by jni** [comment] 2022-07-07 05:58
Ok I think I've done it? It was napari org page > Packages [**not** settings] > napari/napari > "Change package visibility". I then chose public and clicked on "I understand the consequences, change package visibility" even though I understood nothing. 🤣 Please close this if the issue is resolved!

**Comment by Czaki** [comment] 2022-07-07 09:13
its Working

**Closed as completed by Czaki** 2022-07-07 09:13 UTC
Labels: bug
