### ISSUE TITLE
All benchmark tests are failing in CI

### ISSUE THREAD

**Issue by jni** [napari/napari#7037] opened 2024-06-28 02:16 UTC
## 🧰 Task

Example:

https://github.com/napari/napari/actions/runs/9700841757/job/26773717898?pr=6319#step:9:58

<details>

<summary>

```
Couldn't load asv.plugins._mamba_helpers because
No module named 'libmambapy'
```

</summary>

```
Couldn't load asv.plugins._mamba_helpers because
No module named 'libmambapy'
· Error running /usr/bin/git rev-list --first-parent main^! -- (exit status 128)
  STDOUT -------->
  
  STDERR -------->
  fatal: bad revision 'main^!'

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/bin/asv", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/asv/main.py", line 29, in main
    result = args.func(args)
             ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/asv/commands/__init__.py", line 49, in run_from_args
    return cls.run_from_conf_args(conf, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/asv/commands/run.py", line 166, in run_from_conf_args
    return cls.run(
           ^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/asv/commands/run.py", line 265, in run
    commit_hashes = repo.get_hashes_from_range(range_spec)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/asv/plugins/git.py", line 123, in get_hashes_from_range
    output = self._run_git(args, valid_return_codes=(0, 1), dots=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/asv/plugins/git.py", line 70, in _run_git
    return util.check_output([self._git] + args, env=env, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/asv/util.py", line 618, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/usr/bin/git rev-list --first-parent main^! --' returned non-zero exit status 128
```

</details>

This seems to be happening because we don't use constraints for asv in the runner:

https://github.com/napari/napari/blob/cf46f20c32564510d3e8b807ba8d1ebad01f1743/.github/workflows/test_pull_requests.yml#L229-L232

Suspiciously, a totally unrelated library called mambapy 1.0 was released yesterday:

https://pypi.org/project/mambapy/#history

But, probably a red herring, as I don't see anything pointing to it in the ASV dependency tree. I don't know what package is supposed to provide libmambapy tbh... (libmambapy doesn't exist)

**Comment by jni** [comment] 2024-06-28 02:26
Here's the issue in asv: https://github.com/airspeed-velocity/asv/issues/1412

**Comment by psobolewskiPhD** [comment] 2024-06-28 02:33
The mamba thing is a red herring I think. I think the real issue is:
```
asv.util.ProcessError: Command '/usr/bin/git rev-list --first-parent main^! --' returned non-zero exit status 128
```

**Comment by jni** [comment] 2024-06-28 02:34
wow double red-herring. A school of herrings! 😂

**Comment by jni** [comment] 2024-06-28 02:36
ok so... what could be the cause of the git fail!??

**Comment by psobolewskiPhD** [comment] 2024-06-28 02:42
You can look here, where it passes:
https://github.com/napari/napari/actions/runs/9682925847/job/26717791123#step:9:59
same libmambapy warning, but you see it build 0.4.19
But in the fail it's using `main`. So it must be related to the 0.5.0a tag

**Comment by psobolewskiPhD** [comment] 2024-06-28 02:45
So the issue is here:
https://github.com/napari/napari/blob/cf46f20c32564510d3e8b807ba8d1ebad01f1743/.github/workflows/test_pull_requests.yml#L250

in that variable used at the end. It's not resolving properly.
So this step is not returning what we want:
https://github.com/napari/napari/blob/cf46f20c32564510d3e8b807ba8d1ebad01f1743/.github/workflows/test_pull_requests.yml#L219-L227

**Comment by jni** [comment] 2024-06-28 05:24
... Which is weird because it points to a hash like any other?

https://github.com/napari/napari/releases/latest

resolves to

https://github.com/napari/napari/releases/tag/v0.5.0a4

So I think there is some GH magic happening where it's like, well if it's the same as main I'll just return main instead of a hash? But also, this is a perfectly valid operation on git? (I truncate the diffs below)

```sh
$ git show main
commit cf46f20c32564510d3e8b807ba8d1ebad01f1743 (HEAD -> main, tag: v0.5.0a4, upstream/main)
Author: Grzegorz Bokota <bokota+github@gmail.com>
Date:   Thu Jun 27 00:28:09 2024 +0200

    fix syntax bug in `make_release.yml` (#7033)

$ git show main^
commit d9ea7c4d67644dd23ee555b89abce9bd329f246d (tag: v0.5.0a3)
Author: Grzegorz Bokota <bokota+github@gmail.com>
Date:   Thu Jun 27 00:15:15 2024 +0200

    Handle also alpha and beta releases in `make_release.yml` (#7032)

$ git show main^!
commit cf46f20c32564510d3e8b807ba8d1ebad01f1743 (HEAD -> main, tag: v0.5.0a4, upstream/main)
Author: Grzegorz Bokota <bokota+github@gmail.com>
Date:   Thu Jun 27 00:28:09 2024 +0200

    fix syntax bug in `make_release.yml` (#7033)
```

So (a) I don't understand why we have `^!` which should be a no-op (and is definitely a no-op in a linear history?), and (b) I don't understand why it's failing anyway — is it because the current commit is the same as the "upstream" commit and asv doesn't like it?

**Comment by Czaki** [comment] 2024-06-28 06:34
Do not care about libmambapy warning. It existing from long time and do not crash the tests.

**Comment by jni** [comment] 2024-06-28 13:39
Yes, noted above by @psobolewskiPhD. Any idea how to fix it? 🤔

**Comment by Czaki** [comment] 2024-06-28 14:14
(From mobile) 
I think that benchmarks will be solved once commit without tag will be added to main.
Will have time at Monday to read stacktrace.

**Comment by jni** [comment] 2024-06-30 00:24
> I think that benchmarks will be solved once commit without tag will be added to main.

Hmmmm. Now they are failing in a totally different way. (Which does not seem related to our project...)

https://gist.github.com/jni/262acf6306025a3843b0a70b7268a8ff

(from https://github.com/napari/napari/actions/runs/9727664299/job/26847568152?pr=7040#step:8:354)

**Closed as completed** 2024-07-01 14:12 UTC
Labels: task
