### ISSUE TITLE
Traceback copied with copy button contains terminal color commands

### ISSUE THREAD

**Issue by Czaki** [napari/napari#3724] opened 2021-12-01 09:10 UTC
## 🐛 Bug

Traceback copied with copy button contains terminal color commands. Here button marked:

![Zrzut ekranu z 2021-12-01 10-03-16](https://user-images.githubusercontent.com/3826210/144204349-a5ea816c-2bbc-45c8-a9db-9659ea9f02e4.png)

```
======================= Errors for plugin 'cellpose-napari' =======================

  napari version: 0.4.12


ERROR #1:  Error while importing module cellpose_napari --------------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m~/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/napari_plugin_engine/manager.py[0m in [0;36m_load_and_register[0;34m(self=<napari.plugins._plugin_manager.NapariPluginManager object>, mod_name='cellpose_napari', plugin_name='cellpose-napari')[0m
[1;32m    317[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 318[0;31m             [0mmodule[0m [0;34m=[0m [0mload[0m[0;34m([0m[0mmod_name[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m        [0;36mmodule[0m [0;34m= [0;36mundefined[0m[0m[0;34m
        [0m[0;36mglobal[0m [0;36mload[0m [0;34m= <function load at 0x7f1fcde6a700>[0m[0;34m
        [0m[0;36mmod_name[0m [0;34m= 'cellpose_napari'[0m
[1;32m    319[0m             [0;32mif[0m [0mself[0m[0;34m.[0m[0mis_registered[0m[0;34m([0m[0mmodule[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/napari_plugin_engine/manager.py[0m in [0;36mload[0;34m(value='cellpose_napari')[0m
[1;32m   1041[0m         [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34mf"malformed entry point string: {value}"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1042[0;31m     [0mmodule[0m [0;34m=[0m [0mimportlib[0m[0;34m.[0m[0mimport_module[0m[0;34m([0m[0mmatch[0m[0;34m.[0m[0mgroup[0m[0;34m([0m[0;34m'module'[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m        [0;36mmodule[0m [0;34m= [0;36mundefined[0m[0m[0;34m
        [0m[0;36mglobal[0m [0;36mimportlib.import_module[0m [0;34m= <function import_module at 0x7f1fe659a040>[0m[0;34m
        [0m[0;36mmatch.group[0m [0;34m= <built-in method group of re.Match object at 0x7f1f2e52c5b0>[0m
[1;32m   1043[0m     [0mattrs[0m [0;34m=[0m [0mfilter[0m[0;34m([0m[0;32mNone[0m[0;34m,[0m [0;34m([0m[0mmatch[0m[0;34m.[0m[0mgroup[0m[0;34m([0m[0;34m'attr'[0m[0;34m)[0m [0;32mor[0m [0;34m''[0m[0;34m)[0m[0;34m.[0m[0msplit[0m[0;34m([0m[0;34m'.'[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.pyenv/versions/3.8.3/lib/python3.8/importlib/__init__.py[0m in [0;36mimport_module[0;34m(name='cellpose_napari', package=None)[0m
[1;32m    126[0m             [0mlevel[0m [0;34m+=[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 127[0;31m     [0;32mreturn[0m [0m_bootstrap[0m[0;34m.[0m[0m_gcd_import[0m[0;34m([0m[0mname[0m[0;34m[[0m[0mlevel[0m[0;34m:[0m[0;34m][0m[0;34m,[0m [0mpackage[0m[0;34m,[0m [0mlevel[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m        [0;36mglobal[0m [0;36m_bootstrap._gcd_import[0m [0;34m= <function _gcd_import at 0x7f1fe66c5430>[0m[0;34m
        [0m[0;36mname[0m [0;34m= 'cellpose_napari'[0m[0;34m
        [0m[0;36mlevel[0m [0;34m= 0[0m[0;34m
        [0m[0;36mpackage[0m [0;34m= None[0m
[1;32m    128[0m [0;34m[0m[0m

[0;32m~/.pyenv/versions/3.8.3/lib/python3.8/importlib/_bootstrap.py[0m in [0;36m_gcd_import[0;34m(name='cellpose_napari', package=None, level=0)[0m

[0;32m~/.pyenv/versions/3.8.3/lib/python3.8/importlib/_bootstrap.py[0m in [0;36m_find_and_load[0;34m(name='cellpose_napari', import_=<function _gcd_import>)[0m

[0;32m~/.pyenv/versions/3.8.3/lib/python3.8/importlib/_bootstrap.py[0m in [0;36m_find_and_load_unlocked[0;34m(name='cellpose_napari', import_=<function _gcd_import>)[0m

[0;32m~/.pyenv/versions/3.8.3/lib/python3.8/importlib/_bootstrap.py[0m in [0;36m_load_unlocked[0;34m(spec=ModuleSpec(name='cellpose_napari', loader=<_froz....8/lib/python3.8/site-packages/cellpose_napari']))[0m

[0;32m~/.pyenv/versions/3.8.3/lib/python3.8/importlib/_bootstrap_external.py[0m in [0;36mexec_module[0;34m(self=<_frozen_importlib_external.SourceFileLoader object>, module=<module 'cellpose_napari' from '/home/czaki/.pye...on3.8/site-packages/cellpose_napari/__init__.py'>)[0m

[0;32m~/.pyenv/versions/3.8.3/lib/python3.8/importlib/_bootstrap.py[0m in [0;36m_call_with_frames_removed[0;34m(f=<built-in function exec>, *args=(<code object <module> at 0x7f1f2e52c3a0, file "/...te-packages/cellpose_napari/__init__.py", line 1>, {'__builtins__': {'ArithmeticError': <class 'ArithmeticError'>, 'AssertionError': <class 'AssertionError'>, 'AttributeError': <class 'AttributeError'>, 'BaseException': <class 'BaseException'>, 'BlockingIOError': <class 'BlockingIOError'>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'BufferError': <class 'BufferError'>, 'BytesWarning': <class 'BytesWarning'>, 'ChildProcessError': <class 'ChildProcessError'>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, ...}, '__cached__': '/home/czaki/.pyenv/versions/partseg3.8/lib/pytho...llpose_napari/__pycache__/__init__.cpython-38.pyc', '__doc__': None, '__file__': '/home/czaki/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/cellpose_napari/__init__.py', '__loader__': <_frozen_importlib_external.SourceFileLoader object>, '__name__': 'cellpose_napari', '__package__': 'cellpose_napari', '__path__': ['/home/czaki/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/cellpose_napari'], '__spec__': ModuleSpec(name='cellpose_napari', loader=<_froz....8/lib/python3.8/site-packages/cellpose_napari']), '__version__': 'unknown'}), **kwds={})[0m

[0;32m~/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/cellpose_napari/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m [0;34m[0m[0m
[0;32m----> 6[0;31m [0;32mfrom[0m [0;34m.[0m[0m_dock_widget[0m [0;32mimport[0m [0mnapari_experimental_provide_dock_widget[0m[0;34m[0m[0;34m[0m[0m
[0m        [0;36mglobal[0m [0;36m_dock_widget[0m [0;34m= [0;36mundefined[0m[0m[0;34m
        [0m[0;36mglobal[0m [0;36mnapari_experimental_provide_dock_widget[0m [0;34m= [0;36mundefined[0m[0m
[1;32m      7[0m [0;32mfrom[0m [0;34m.[0m[0m_sample_data[0m [0;32mimport[0m [0mnapari_provide_sample_data[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/cellpose_napari/_dock_widget.py[0m in [0;36m<module>[0;34m[0m
[1;32m     18[0m [0;34m[0m[0m
[0;32m---> 19[0;31m [0;32mfrom[0m [0mcellpose[0m [0;32mimport[0m [0mmodels[0m[0;34m[0m[0;34m[0m[0m
[0m        [0;36mglobal[0m [0;36mcellpose[0m [0;34m= [0;36mundefined[0m[0m[0;34m
        [0m[0;36mglobal[0m [0;36mmodels[0m [0;34m= [0;36mundefined[0m[0m
[1;32m     20[0m [0;32mfrom[0m [0mcellpose[0m[0;34m.[0m[0mutils[0m [0;32mimport[0m [0mmasks_to_outlines[0m[0;34m,[0m [0mfill_holes_and_remove_small_masks[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/cellpose/__init__.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0;34m.[0m[0mio[0m [0;32mimport[0m [0mlogger_setup[0m[0;34m[0m[0;34m[0m[0m
[0m        [0;36mglobal[0m [0;36mio[0m [0;34m= [0;36mundefined[0m[0m[0;34m
        [0m[0;36mglobal[0m [0;36mlogger_setup[0m [0;34m= [0;36mundefined[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mlogger[0m[0;34m,[0m [0mlog_file[0m [0;34m=[0m [0mlogger_setup[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/cellpose/io.py[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0;34m[0m[0m
[0;32m----> 8[0;31m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mutils[0m[0;34m,[0m [0mplot[0m[0;34m,[0m [0mtransforms[0m[0;34m[0m[0;34m[0m[0m
[0m        [0;36mglobal[0m [0;36mutils[0m [0;34m= [0;36mundefined[0m[0m[0;34m
        [0m[0;36mglobal[0m [0;36mplot[0m [0;34m= [0;36mundefined[0m[0m[0;34m
        [0m[0;36mglobal[0m [0;36mtransforms[0m [0;34m= [0;36mundefined[0m[0m
[1;32m      9[0m [0;34m[0m[0m

[0;32m~/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/cellpose/utils.py[0m in [0;36m<module>[0;34m[0m
[1;32m     11[0m [0;34m[0m[0m
[0;32m---> 12[0;31m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mmetrics[0m[0;34m[0m[0;34m[0m[0m
[0m        [0;36mglobal[0m [0;36mmetrics[0m [0;34m= [0;36mundefined[0m[0m
[1;32m     13[0m [0;34m[0m[0m

[0;32m~/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/cellpose/metrics.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mutils[0m[0;34m,[0m [0mdynamics[0m[0;34m[0m[0;34m[0m[0m
[0m        [0;36mglobal[0m [0;36mutils[0m [0;34m= [0;36mundefined[0m[0m[0;34m
        [0m[0;36mglobal[0m [0;36mdynamics[0m [0;34m= [0;36mundefined[0m[0m
[1;32m      3[0m [0;32mfrom[0m [0mnumba[0m [0;32mimport[0m [0mjit[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/cellpose/dynamics.py[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;32mfrom[0m [0mtqdm[0m [0;32mimport[0m [0mtrange[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 7[0;31m [0;32mfrom[0m [0mnumba[0m [0;32mimport[0m [0mnjit[0m[0;34m,[0m [0mfloat32[0m[0;34m,[0m [0mint32[0m[0;34m,[0m [0mvectorize[0m[0;34m[0m[0;34m[0m[0m
[0m        [0;36mglobal[0m [0;36mnumba[0m [0;34m= [0;36mundefined[0m[0m[0;34m
        [0m[0;36mglobal[0m [0;36mnjit[0m [0;34m= [0;36mundefined[0m[0m[0;34m
        [0m[0;36mglobal[0m [0;36mfloat32[0m [0;34m= [0;36mundefined[0m[0m[0;34m
        [0m[0;36mglobal[0m [0;36mint32[0m [0;34m= [0;36mundefined[0m[0m[0;34m
        [0m[0;36mglobal[0m [0;36mvectorize[0m [0;34m= [0;36mundefined[0m[0m
[1;32m      8[0m [0;34m[0m[0m

[0;32m~/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/numba/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m    197[0m [0m_ensure_llvm[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 198[0;31m [0m_ensure_critical_deps[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m        [0;36mglobal[0m [0;36m_ensure_critical_deps[0m [0;34m= <function _ensure_critical_deps at 0x7f1f24085d30>[0m
[1;32m    199[0m [0;34m[0m[0m

[0;32m~/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/numba/__init__.py[0m in [0;36m_ensure_critical_deps[0;34m()[0m
[1;32m    137[0m     [0;32melif[0m [0mnumpy_version[0m [0;34m>[0m [0;34m([0m[0;36m1[0m[0;34m,[0m [0;36m20[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 138[0;31m         [0;32mraise[0m [0mImportError[0m[0;34m([0m[0;34m"Numba needs NumPy 1.20 or less"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m        [0;36mglobal[0m [0;36mImportError[0m [0;34m= [0;36mundefined[0m[0m
[1;32m    139[0m [0;34m[0m[0m

[0;31mImportError[0m: Numba needs NumPy 1.20 or less

The above exception was the direct cause of the following exception:

[0;31mPluginImportError[0m                         Traceback (most recent call last)
[0;32m~/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/napari_plugin_engine/manager.py[0m in [0;36mdiscover[0;34m(self=<napari.plugins._plugin_manager.NapariPluginManager object>, path=None, entry_point=None, prefix=None, ignore_errors=True)[0m
[1;32m    262[0m [0;34m[0m[0m
[1;32m    263[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 264[0;31m                 [0;32mif[0m [0mself[0m[0;34m.[0m[0m_load_and_register[0m[0;34m([0m[0mmod_name[0m[0;34m,[0m [0mname[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m        [0;36mself._load_and_register[0m [0;34m= <bound method PluginManager._load_and_register of <napari.plugins._plugin_manager.NapariPluginManager object at 0x7f1f9c1ba460>>[0m[0;34m
        [0m[0;36mmod_name[0m [0;34m= 'napari_console'[0m[0;34m
        [0m[0;36mname[0m [0;34m= 'console'[0m
[1;32m    265[0m                     [0mcount[0m [0;34m+=[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[1;32m    266[0m                     [0mself[0m[0;34m.[0m[0m_id_counts[0m[0;34m[[0m[0mname[0m[0;34m][0m [0;34m=[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.pyenv/versions/partseg3.8/lib/python3.8/site-packages/napari_plugin_engine/manager.py[0m in [0;36m_load_and_register[0;34m(self=<napari.plugins._plugin_manager.NapariPluginManager object>, mod_name='cellpose_napari', plugin_name='cellpose-napari')[0m
[1;32m    320[0m                 [0;32mreturn[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[1;32m    321[0m         [0;32mexcept[0m [0mException[0m [0;32mas[0m [0mexc[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 322[0;31m             raise PluginImportError(
[0m        [0;36mglobal[0m [0;36mPluginImportError[0m [0;34m= <class 'napari_plugin_engine.exceptions.PluginImportError'>[0m[0;34m
        [0m[0;36mplugin_name[0m [0;34m= 'cellpose-napari'[0m[0;34m
        [0m[0;36mglobal[0m [0;36mcause[0m [0;34m= [0;36mundefined[0m[0m[0;34m
        [0m[0;36mexc[0m [0;34m= [0;36mundefined[0m[0m
[1;32m    323[0m                 [0;34mf'Error while importing module {mod_name}'[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    324[0m                 [0mplugin_name[0m[0;34m=[0m[0mplugin_name[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;31mPluginImportError[0m: Error while importing module cellpose_napari
================================================================================
```

## To Reproduce

1. Generate traceback
2. Open Plugins > Plugin error.., select plugin 
3. click copy button
4. paste to text editor

## Expected behavior

Clean traceback

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:
 ```
napari: 0.4.12
Platform: Linux-5.11.0-41-generic-x86_64-with-glibc2.2.5
System: Ubuntu 21.04
Python: 3.8.3 (default, Sep 3 2021, 01:19:46) [GCC 10.3.0]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.3
SciPy: 1.7.1
Dask: 2021.09.1
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 NVIDIA 470.86
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0
- screen 3: resolution 1920x1080, scale 1.0

Plugins:
- PartSeg Analysis project reader: 0.13.14.dev3+g1e700a12
- PartSeg Image reader: 0.13.14.dev3+g1e700a12
- PartSeg Image tiff writer: 0.13.14.dev3+g1e700a12
- PartSeg Mask project reader: 0.13.14.dev3+g1e700a12
- PartSeg Mask project writer: 0.13.14.dev3+g1e700a12
- PartSeg Masked Tiff reader: 0.13.14.dev3+g1e700a12
- PartSeg widgets: 0.13.14.dev3+g1e700a12
- console: 0.0.4
- svg: 0.1.5
```
## Additional context

It was found during showing  #3700 on meeting.

**Comment by psobolewskiPhD** [comment] 2023-10-07 04:54
Can't reproduce this.
I assume it was fixed by: https://github.com/napari/napari/pull/4414

**Closed as completed** 2023-10-07 04:54 UTC
Labels: bug
