### ISSUE TITLE
Min/max values of Iso threshold slider does not match the range of image data

### ISSUE THREAD

**Issue by hanjinliu** [napari/napari#3969] opened 2022-01-18 04:35 UTC
## 🐛 Bug

3D float image (probably when image contains negative values) does not disappear at `iso_surface=1.0` in `v0.4.13`.

![image](https://user-images.githubusercontent.com/40591297/149871574-b95ecf9b-f7b4-41da-b160-4df2bc8002e4.png)

## To Reproduce

Run following code.

```python
import napari

viewer=napari.view_image(np.random.normal(size=(32, 32, 32)))
viewer.layers[0].iso_threshold = 1.0
viewer.layers[0].rendering="iso"
viewer.dims.ndisplay = 3
```

## Expected behavior

Image should be invisible.

## Environment

```
napari: 0.4.13
Platform: Windows-10-10.0.22000-SP0
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.5
SciPy: 1.7.3
Dask: 2021.11.1
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.9621
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1368x912, scale 2.0

Plugins:
- animation: 0.0.2
- console: 0.0.4
- napari-multitask: 0.0.2
- napari-roi: 0.1.0
- scikit-image: 0.4.13
- svg: 0.1.5
```

**Comment by alisterburt** [comment] 2022-01-18 17:38
Hi @hanjinliu 

I'm not sure I follow exactly - why should the image be invisible?

```python
a = np.random.normal(size=(32, 32, 32))
np.min(a), np.max(a)
```
```python
Out[14]: (-4.351089600630622, 4.007020063515334)
```

Setting the iso threshold above the max value in the array gives me an invisible volume

Does this solve your issue?

**Comment by hanjinliu** [comment] 2022-01-19 02:54
Sorry @alisterburt, I was getting wrong about the parameter...
The true problem is the maximum value of iso threshold slider does not match the maximum intensity of image.

After running

```python
import napari
viewer=napari.view_image(np.random.normal(size=(32, 32, 32)))
```

and manually set viewer to 3D mode/iso-surface rendering, the maximum value of `iso_threshold` is 1.0.

**Comment by jni** [comment] 2022-01-19 22:37
Ok so the problem is a UI/UX question. Perhaps we should rename this issue or create a new one? "Iso threshold does not correspond to full range of data"? An "easy" solution would be for the endpoints of the iso-threshold to correspond to the contrast_limits_range? Or just the contrast limits?

**Comment by hanjinliu** [comment] 2022-01-20 10:33
Thanks @jni, I've changed the title.
As far as I tested, the problem did not happen in `0.4.12` so it could be due to some changes in `0.4.13`.

In my opinion. linking `iso_threshold` to one of those contrast limit variables could be confusing. Let's say I moved the lower bound from 0 to 10 and back to 0, then the surface will look different if iso_threshold=5. But I also understand adjusting `iso_threshold` in a low-contrast images will be difficult...

**Comment by psobolewskiPhD** [comment] 2024-11-09 19:50
I just tested this in napari 0.5.5dev.
Using
```
import napari
viewer=napari.view_image(np.random.normal(size=(32, 32, 32)))
```
and setting to 3D mode, iso rendering, the slider goes from -3.58 to 4.31, which corresponds to min/max:
```
viewer.layers[0].data.max()
Out[42]: np.float64(4.30674314120739)

viewer.layers[0].data.min()
Out[43]: np.float64(-3.580640089851631)
``` 
Looks like it was fixed by https://github.com/napari/napari/pull/5215

**Closed as completed by psobolewskiPhD** 2024-11-09 19:50 UTC
Labels: bug
