### ISSUE TITLE
Painting into zarr arrays doesn't update the display

### ISSUE THREAD

**Issue by jni** [napari/napari#6079] opened 2023-07-21 22:53 UTC
## 🐛 Bug

It looks like #5732 broke labels painting into zarr arrays: the painting happens but the display doesn't update.

## To Reproduce

```python
import numpy as np
import napari
import zarr


fn = 'labels.zarr'
image = np.random.random((512, 512))
labels_arr = zarr.open(
        fn, shape=image.shape, dtype=np.uint32, chunks=(256, 256)
        )

viewer = napari.Viewer()
viewer.add_image(image)
lbllyr = viewer.add_labels(labels_arr)
lbllyr.mode = 'paint'
lbllyr.brush_size = 30

napari.run()
```

then start painting. The labels display doesn't update, but the zarr file is getting updated. Toggling visibility of the layer off and on after painting shows the labels correctly.

## Expected behavior

Labels display should update as we are painting. aff5c9429 behaves normally, but from 3868f5c8c6f4cbd5704b35ed0fa9bccd19be3435 (#5732) the display doesn't update. Probably the cache must be invalidated somewhere where it isn't.

CC @ksofiyuk

**Comment by andy-sweet** [comment] 2023-07-24 16:53
I was able to reproduce the issue using the example above. I wondered if async slicing could be an explanation here, but reproduced it with that turned off, so there's at least something else going wrong here.

> Any ideas about where `self._slice.image.raw` could be getting updated correctly in one case but not the other?

Not yet. Since `ImageSliceResponse` and `ImageView` are frozen dataclasses, setting `_slice.image` or `_slice.image.raw` (or `view`) should at least error at runtime. `raw` and `view` are just numpy arrays, so they can be mutated in place though.

I took a quick poke through the code base and I was surprised to find that the partial update does not mutate those in place (or reassign `_slice`) and [instead only passes data through to vispy through the event](https://github.com/napari/napari/blob/a593ff73832d7beb2f428d84be8f6974e79b54e2/napari/layers/labels/labels.py#L856). So it seems like the vispy node and the slice data may be getting out of sync. Not sure if that's a cause here, but it sounds problematic.

However, I'm not too familiar with the partial update code path, so I'm not stating the above with much confidence though. Given that code path is fairly complex (compared to images), adding some debug logging could help here and in the future.

Also, I remember that [labels painting has some special behavior for non-numpy arrays](https://github.com/napari/napari/blob/a593ff73832d7beb2f428d84be8f6974e79b54e2/napari/layers/labels/labels.py#L1443), so that may be another place to look.

**Comment by jni** [comment] 2023-07-24 23:14
Thanks for the pointers, @andy-sweet!

> raw and view are just regular numpy arrays though, so they can be mutated in place though.

This is useful and I suspect that some version of this is what's happening. Since there's no actual slicing going on, `raw` might just point to the exact same memory as the .data array? So it would get "naturally" updated, whereas the same array for the zarr version doesn't actually point to the zarr memory.

Note that the zarr is getting edited totally fine — we just can't see it. I think it's because the partial update looks at the `_slice`, finds no change, so sends nothing to VisPy. I think it needs to look at the data instead, maybe? Or should painting update the _slice? 🤔 That sounds expensive given the immutability thing...

> Also, I remember that [labels painting has some special behavior for non-numpy arrays](https://github.com/napari/napari/blob/a593ff73832d7beb2f428d84be8f6974e79b54e2/napari/layers/labels/labels.py#L1443), so that may be another place to look.

I walked through that bit, I don't think anything fishy is going on there — the zarr array gets written to normally, and the right values go into the undo stack.

**Comment by andy-sweet** [comment] 2023-07-24 23:37
> This is useful and I suspect that some version of this is what's happening. Since there's no actual slicing going on, `raw` might just point to the exact same memory as the .data array? So it would get "naturally" updated, whereas the same array for the zarr version doesn't actually point to the zarr memory.
> 
> Note that the zarr is getting edited totally fine — we just can't see it. I think it's because the partial update looks at the `_slice`, finds no change, so sends nothing to VisPy. I think it needs to look at the data instead, maybe? Or should painting update the _slice? 🤔 That sounds expensive given the immutability thing...

This summary sounds right.

`Labels._slice` should hold the raw and displayed versions of the numpy arrays that are passed through to vispy for visualization. But the partial update never updates `_slice`. Before the partial update stuff, I think we just modified `data` then sliced that - slow, but simple.

I think the update to slice should happen in `data_setitem` (oof, did that really need to be public), but we'll have to work out to use `indices` in the slice space.

Updating `_slice` shouldn't be expensive. We don't actually need to reallocate memory in the partial update case, and we can probably just update `view` and `raw` in-place. If we need to create a new `ImageView` (or even an `ImageSliceResponse`), that should also be very cheap compared to everything else going on here.

**Comment by jni** [comment] 2023-07-24 23:46
> Labels.data_setitem (oof, did that really need to be public?),

Yes, the context is that we wanted a way for plugins to update data that wouldn't bypass the undo stack. Alternative suggestions are certainly welcome! 😊 The more magical version proposed in #3155 was too controversial. 😅 But we could add something like that in 0.5 or 0.6 if we move to a more elaborate .data object (putting the original input in .data_raw, for example).

Anyway, thanks, I'll have a look at updating the _slice contents in-place! Having your permission to do this is emotionally valuable to me. 😂

**Comment by andy-sweet** [comment] 2023-07-25 00:05
Permission granted!

One other thing to consider is our friend the thumbnail, which is typically updated as part of slicing. Not as crucial to fix as the canvas, but worth a little thought maybe?

**Comment by jni** [comment] 2023-07-25 10:32
I'm working on a test but in case people are running into this issue and want to get their local install working, this is sufficient to fix:

```diff
diff --git a/napari/layers/labels/labels.py b/napari/layers/labels/labels.py
index aa9aca0f0..d37d6dd46 100644
--- a/napari/layers/labels/labels.py
+++ b/napari/layers/labels/labels.py
@@ -1454,6 +1454,11 @@ class Labels(_ImageBase):
         # tensorstore and xarray do not return their indices in
         # np.ndarray format, so they need to be converted explicitly
         if not isinstance(self.data, np.ndarray):
+            # In the absence of slicing, the current slice becomes
+            # invalidated by data_setitem; only in the special case of a NumPy
+            # array is the slice a view and therefore updated automatically.
+            # For other types, we update it manually here.
+            self._slice.image.raw[indices] = value
             indices = [np.array(x).flatten() for x in indices]

         updated_slice = tuple(
```

**Closed as completed** 2023-08-25 09:48 UTC
Labels: bug, priority:high
