### ISSUE TITLE
Gui Locked and unstopable notification error stream

### ISSUE THREAD

**Issue by Carreau** [napari/napari#2313] opened 2021-02-25 19:04 UTC
## 🐛 Bug

![crsh](https://user-images.githubusercontent.com/335567/109203242-c4f2b580-7758-11eb-9144-d38c96a9bcbc.gif)

## To Reproduce

- Open napari; 
- Toggle number of displayed dimension (Ctrl-Y), 
- Add new layer shape.
- Napari is now locked and keep popping notification, and must be killed.

## Expected behavior

- Show an single notification
- don't block the UI.

## Environment

commit 3d8f315a74ce53d2e6a784f246b5d405d3951667 , latest master.

**Comment by sofroniewn** [comment] 2021-02-26 17:10
This doesn't look good! Thanks for flagging!!

**Comment by andy-sweet** [comment] 2022-06-06 21:53
@Carreau : I could reproduce this at 3d8f315a74ce53d2e6a784f246b5d405d3951667, but I can't reproduce on `main` now at 5c10022337601f350ad64ce56eddf6664306e40e.

If you also find that, can you close this specific bug?

Or do you think there's another way to reach the undesirable state here? If so, can you add new steps to reproduce.

**Comment by dalthviz** [comment] 2023-01-12 00:57
Hi, just in case, I was unable to reproduce this using main (e8c0f37b02) on Windows

**Comment by psobolewskiPhD** [comment] 2023-01-12 13:35
I can't reproduce on macOS 13.1 `main` (ed26f412892c1e5fdb4d39cb4ebc749e56573403)

**Comment by psobolewskiPhD** [comment] 2023-05-02 20:26
I'm going to close. If someone can reproduce this with 0.4.17 or current main, please reopen or make a new issue!

**Closed as completed by psobolewskiPhD** 2023-05-02 20:26 UTC
Labels: bug
