### ISSUE TITLE
conda update napari breaks napari

### ISSUE THREAD

**Issue by dgmccart** [napari/napari#4881] opened 2022-07-29 00:19 UTC
## 🐛 Bug

conda update napari breaks napari. I had napari 0.14.0 installed, and after trying to update to the latest version with conda, napari is no longer able to open. An error message about dask requirements results, but following the instructions to install dask with conda does not fix the issue (same error message appears). 

## To Reproduce

1. install napari 0.14.0 using conda (this the default version that was installed on my machine in early July even though 0.16.0 was already released)
2. run conda update napari -y 
3. run napari
4. error message about dask requirements appeared (see below)

## Terminal messages from updating napari

https://gist.github.com/dgmccart/32b35d9dcf233da4967797b6c5fe1779

## Error message when trying to open napari

https://gist.github.com/dgmccart/09411508f3c0db10af2d84e89840dc01

## Installed packages 

https://gist.github.com/dgmccart/6d381c959a82c468dd5085a509a27ce0

## Expected behavior

napari to be updated to the latest version

## Environment

 - Environment from before I tried to update napari: 

napari: 0.4.14
Platform: macOS-12.4-arm64-arm-64bit
System: MacOS 12.4
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33) [Clang 13.0.1 ]
Qt: 5.15.4
PyQt5: 5.15.7
NumPy: 1.23.1
SciPy: 1.8.1
Dask: 2022.7.0
VisPy: 0.11.0

OpenGL:
GL version: 2.1 Metal - 76.3
MAX_TEXTURE_SIZE: 16384

Screens:
screen 1: resolution 1512x982, scale 2.0

Plugins:
console: 0.0.4
scikit-image: 0.4.14
svg: 0.1.6

**Comment by tlambert03** [comment] 2022-07-29 18:26
I'm afraid the only answer here is probably going to be that something went wrong in your environment.  I tried reproducing by creating a new environment with 0.4.14, then updating to 0.4.16, and it worked fine.


```sh
conda create -n test napari==0.4.14
conda activate test
napari # fine
conda install napari==0.4.16
napari # fine
```

From the looks of your error message:
```pytb
Traceback (most recent call last):
  File "/opt/miniconda3/envs/napari-audit/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/opt/miniconda3/envs/napari-audit/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/opt/miniconda3/envs/napari-audit/lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/opt/miniconda3/envs/napari-audit/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libcblas.3.dylib
  Referenced from: /opt/miniconda3/envs/napari-audit/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so
  Reason: tried: '/opt/miniconda3/envs/napari-audit/lib/python3.9/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/opt/miniconda3/envs/napari-audit/lib/python3.9/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/opt/miniconda3/envs/napari-audit/bin/../lib/libcblas.3.dylib' (no such file), '/opt/miniconda3/envs/napari-audit/bin/../lib/libcblas.3.dylib' (no such file), '/usr/local/lib/libcblas.3.dylib' (no such file), '/usr/lib/libcblas.3.dylib' (no such file)

```

it looks like you've ended up with a binary incompatibility... this likely means that at some point before updating napari, you used pip to either install numpy, or another package that in turn installed numpy, this can very often lead to the error you're seeing.  Usually at that point the best thing is just to create a new environment.

Hope that helps.  Since I'm not sure there's anything we can do on our end, i'll close this issue. but feel free to ask for more help

**Closed as completed by tlambert03** 2022-07-29 18:26 UTC
Labels: bug
