### ISSUE TITLE
WX error toggling between slice and volumetric view

### ISSUE THREAD

**Issue by derekthirstrup** [napari/napari#3010] opened 2021-07-09 19:34 UTC
## To Reproduce

1. Click on button to toggle slice and 3d volume view.  The button intermittently doesn't work but the ctrl-y shortcut still functions.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by dalthviz** [comment] 2023-05-12 18:56
Hi, just in case, I was not able to reproduce this. Checked on Windows and macOS with the `Cell (3D+2Ch)`. however, I noticed a little bit of lag when toggling the view on Windows (maybe due to my machine specs?):

![view](https://github.com/napari/napari/assets/16781833/4f27bc37-fec5-4ef2-b0cd-e97ce9bd8eae)

**Comment by psobolewskiPhD** [comment] 2023-05-12 19:47
Thanks for looking into this @dalthviz 
Wonder why the button is slower than the keybind on windows—is the same behavior on `main`? (I can't see any difference on my M1 macOS 13.3.1

I think in the absence of other data we can close this, but @derekthirstrup feel free to re-open if this still occurs for you!

**Closed as completed** 2023-05-12 19:52 UTC
Labels: bug

**Comment by dalthviz** [comment] 2023-05-12 19:55
> is the same behavior on main? (I can't see any difference on my M1 macOS 13.3.1

The check I did was using `main`, but yes! not totally sure why the toggling shows such a slow response on Windows (at least on my Windows machine) :thinking:
