### ISSUE TITLE
Screenshot test failing on main (due to vispy 0.10?)

### ISSUE THREAD

**Issue by jni** [napari/napari#4399] opened 2022-04-19 06:42 UTC
## 🐛 Bug

The test `napari/_tests/test_with_screenshot.py:test_z_order_image_points_after_ndisplay` is failing on main:

https://github.com/napari/napari/runs/6069251907?check_suite_focus=true#step:7:294

I suspect that this is due to the VisPy 0.10 release, which happened in the last 24h or so.

**Comment by psobolewskiPhD** [comment] 2022-04-19 09:04
I can confirm the change in behavior locally with vispy 0.10.
When entering 3D mode, the point "disappears". Going back to 2D brings it back.

**Comment by jni** [comment] 2022-04-20 06:30
Well, that's no good! LOL CC @brisvag

**Comment by brisvag** [comment] 2022-04-20 07:00
Took a very quick look: the behaviour is intended, and our test is wrong :P It happens because now `Volume` sets its depth correctly, and in napari even 2D images become volumes of thickness `1 px` when moving to 3D.

**Closed as completed** 2022-04-20 10:07 UTC
Labels: bug
