### ISSUE TITLE
Activating matplotlib widget in jupyter lab causes subsequent use of napari to crash the kernel

### ISSUE THREAD

**Issue by s-m-e** [napari/napari#734] opened 2019-11-25 22:08 UTC
**Update from maintainers**: You can see the full thread below but it seems one workaround for napari 0.4.4 is to *first* activate matplotlib widgets and *then* use the `%gui qt` magic for napari.

## 🐛 Bug

Activating the matplotlib widget in Jupyter lab through the `%matplotlib widget` magic causes every subsequent call of `napari.view_image` to crash the kernel.

## To Reproduce

```python
%gui qt
import napari
import numpy as np
data = np.arange(1, 17, dtype = 'int32').reshape(4, 4)
viewer = napari.view_image(data) # does work
%matplotlib widget # root cause of crash
# import matplotlib.pyplot as plt # does not matter
viewer = napari.view_image(data) # triggers crash
```

No traceback or similar is provided (neither in the console nor in the notebook).

## Expected behavior

matplotlib and napari should work side by side.

## Environment

- i7-3740QM & 32 GB RAM
- NVidia K1000M (2GB)
- Linux 4.12 x86_64 (SUSE Leap 15.1)
- Proprietary NVidia driver G04 418.67
- FireFox 68
- Python 3.7.4 (GCC 7)
- **napari 0.2.5**
- PyOpenGL 3.1.0
- zarr 2.3.2
- numcodecs 0.6.3
- numpy 1.17.0
- matplotlib 3.1.1
- ipython 7.7.0
- ipykernel 5.1.1
- jupyter-client 5.3.1
- jupyter-core 4.5.0
- jupyterlab 1.0.4
- jupyterlab-server 1.0.0
- node 12.7.0

## Additional context

None.

**Comment by s-m-e** [comment] 2019-11-25 22:15
There is a variation to the above bug / example: 

```python
%gui qt
%matplotlib widget
import napari
# import matplotlib.pyplot as plt
import numpy as np
data = np.arange(1, 17, dtype = 'int32').reshape(4, 4)
viewer = napari.view_image(data) # FIRST USE OF NAPARI
```

If I activate `matplotlib widget` **before** I actually use `napari`, I do get a traceback in Jupyter lab ...

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-d7b17dc32d77> in <module>
      5 import numpy as np
      6 data = np.arange(1, 17, dtype = 'int32').reshape(4, 4)
----> 7 viewer = napari.view_image(data)

/lib/python3.7/site-packages/napari/view_layers.py in view_image(data, channel_axis, rgb, is_pyramid, colormap, contrast_limits, gamma, interpolation, rendering, name, metadata, scale, translate, opacity, blending, visible, path, title, ndisplay, order)
    100         The newly-created viewer.
    101     """
--> 102     viewer = Viewer(title=title, ndisplay=ndisplay, order=order)
    103     viewer.add_image(
    104         data=data,

/lib/python3.7/site-packages/napari/viewer.py in __init__(self, title, ndisplay, order)
     38                 " Then, restart IPython."
     39             )
---> 40             raise RuntimeError(message)
     41         super().__init__(title=title, ndisplay=ndisplay, order=order)
     42         qt_viewer = QtViewer(self)

RuntimeError: napari requires a Qt event loop to run. To create one, try one of the following: 
  - use the `napari.gui_qt()` context manager. See https://github.com/napari/napari/tree/master/examples for usage examples.
  - In IPython or a local Jupyter instance, use the `%gui qt` magic command.
  - Launch IPython with the option `--gui=qt`.
  - (recommended) in your IPython configuration file, add or uncomment the line `c.TerminalIPythonApp.gui = 'qt'`. Then, restart IPython.
```

... and in the console: 

```python
[LabApp] Adapting from protocol version 5.1 (kernel 2ad155e5-e053-4417-9903-065dbd33d065) to 5.3 (client).
ERROR:tornado.application:Exception in callback functools.partial(<function Kernel.enter_eventloop.<locals>.advance_eventloop at 0x7f9fac53acb0>)
Traceback (most recent call last):
  File "/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 314, in advance_eventloop
    eventloop(self)
TypeError: 'NoneType' object is not callable
```

`napari` fails to launch but at least does not crash the kernel.

**Comment by sofroniewn** [comment] 2019-11-25 22:44
This might be related to #687

**Comment by sofroniewn** [comment] 2020-03-21 03:38
Console loading has now been made lazy by default with #1055 so the console imports will not happen unless someone clicks the console button. Does this satisfy peoples needs here? (in which case i will close the issue). Otherwise we could additionally provide a way to hide the open console button too so that it could never be accidentally opened.

**Comment by ianhi** [comment] 2021-02-09 18:57
I think this is more than just the console. For me on:
- JupyterLab: 3.0.7
- ipywidgets: 7.6.3
- ipympl: 0.6.3

napari: 0.4.4
Platform: Linux-5.8.0-7630-generic-x86_64-with-glibc2.10
System: Pop!_OS 20.04 LTS
Python: 3.8.5 (default, Sep 4 2020, 07:30:14) [GCC 7.3.0]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.19.5
SciPy: 1.6.0
Dask: 2021.02.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen #1: resolution 1920x1080, scale 1.0
- screen #2: resolution 1920x1200, scale 1.0

Plugins:
- svg: 0.1.4



the example code above pops up a blank window for me:
![image](https://user-images.githubusercontent.com/10111092/107413075-5669f280-6ade-11eb-8065-8563b36721a6.png)

after clicking the x on the window many times I eventually I get an option to force quit napari:
![image](https://user-images.githubusercontent.com/10111092/107413026-43572280-6ade-11eb-9961-13e36c3c4354.png)

and then the kernel crashes:
![image](https://user-images.githubusercontent.com/10111092/107413147-684b9580-6ade-11eb-972e-2faa9a5aef29.png)

**Comment by ianhi** [comment] 2021-02-09 20:15
> If I activate matplotlib widget before I actually use napari, I do get a traceback in Jupyter lab ...

Something must have changed in the last year becuase now when I activate matplotlib first I can open napari without an issue.

**Comment by ianhi** [comment] 2021-02-09 20:16
Actually, even more surprisingly the qt console in napari integrates with jupyter. It even gets the execution count correct:
![image](https://user-images.githubusercontent.com/10111092/107422968-c336ba00-6ae9-11eb-956d-efb74ba88e71.png)

**Comment by sofroniewn** [comment] 2021-02-09 21:59
> Something must have changed in the last year becuase now when I activate matplotlib first I can open napari without an issue.

We made some of the console imports lazy, so that might be helping, but it sounds like there might be more stuff going on. It's been a while since I looked at this, but can check it out again. It would be really nice to have all the matplotlib widget integration stuff working smoothly

**Comment by ianhi** [comment] 2021-02-09 22:22
> but can check it out again.

I'm pretty happy with the workaround of just reversing the order of the magics. As far as I can tell if I do that then everythings totally fine

**Comment by jni** [comment] 2021-02-10 00:58
I suspect that this has less to do with the console and more to do with `%matplotlib ipympl` somehow clobbering the Qt eventloop in IPython (based on the "RuntimeError: napari requires a Qt event loop to run" traceback above).

Either way, I hope everyone has been able to get on with their work here... 😬

**Comment by ianhi** [comment] 2021-02-10 01:10
Maybe @s-m-e could edit the first post to reflect the workaround so a future person doesn't find this issue and immediately despair?

**Comment by jni** [comment] 2021-02-10 01:30
@ianhi I updated it. 😊

**Comment by dstansby** [comment] 2022-06-05 12:22
With `matplotlib` 3.5.2 and the current main branch of `napari` I can't reproduce this - perhaps it's all fixed now?

**Comment by sofroniewn** [comment] 2022-06-05 23:07
maybe this can be closed - if someone else finds this issue then we can reopen. thanks for letting us know!!

**Closed as completed by sofroniewn** 2022-06-05 23:07 UTC
Labels: bug, topic:jupyter
