### ISSUE TITLE
3D Multiresolution Image Error under Certain Axis Order

### ISSUE THREAD

**Issue by tathey1** [napari/napari#5106] opened 2022-09-19 20:25 UTC
## To Reproduce

I am trying to work with multiscale 3D images and found an unexpected issue when I am working with "toy" data of arrays of all ones. It seems like only certain axis orders execute without error.
```
import napari
import numpy as np
```

1. The following code gives me an OpenGL error (error trace further below):
```
ims = [np.ones((int(100/2**i),int(100/2**i), 1)) for i in range(2)]
order = (2,0,1)
napari.view_image(ims, multiscale=True, order=order)
```

This error is unexpected because the following two code blocks both work:

2. Different axis order:

```
order = (0,1,2)
ims = [np.ones((int(100/2**i),int(100/2**i), 1)) for i in range(2)]
napari.view_image(ims, multiscale=True)
```

3. 2D version:

```
ims = [np.ones((int(100/2**i),int(100/2**i))) for i in range(2)]
napari.view_image(ims, multiscale=True)
```

The error I get from code block 1 is:

```
WARNING: Error drawing visual <Image at 0x176966c10>
Traceback (most recent call last):
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/visuals/visual.py", line 451, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/gloo/glir.py", line 582, in flush
    self._shared.flush(parser)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/gloo/glir.py", line 504, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/gloo/glir.py", line 822, in parse
    self._parse(command)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/gloo/glir.py", line 784, in _parse
    ob.draw(*args)
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/gloo/glir.py", line 1321, in draw
    gl.check_error('Check before draw')
  File "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/gloo/gl/__init__.py", line 204, in check_error
    raise err
RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_OPERATION
```

## Expected behavior

I did not expect this error because napari successfully loads the same data when the axes are in a different order or when these toy images are "squeezed" into 2D.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.16
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 12.5.1
Python: 3.8.10 (default, May 4 2021, 03:05:50) [Clang 12.0.0 (clang-1200.0.32.29)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.23.2
SciPy: 1.9.1
Dask: 2021.06.2
VisPy: 0.10.0

OpenGL:
- GL version: 2.1 ATI-4.8.101
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0
- screen 2: resolution 2560x1440, scale 2.0

Plugins:
- animation: 0.0.2
- brainlit: 0.3.3
- cellfinder: 0.0.18
- console: 0.0.4
- napari-bil-data-viewer: 0.1.2
- napari-ome-zarr: 0.5.2
- napari-roi: 0.1.7
- ndtiffs: 0.1.2
- scikit-image: 0.4.16
- svg: 0.1.5
```

 - Any other relevant information:

I got the same error on a computer with Ubuntu 18.04, and can provide more info about the napari environment on that computer if needed.

## Additional context

It seems like an OpenGL issue, but not sure if there is something I can do on the napari side to fix this.

Thanks for any help!

**Comment by andy-sweet** [comment] 2023-05-18 17:36
@brisvag : I'm taking a look at this now since it's related to an issue found in #5816

**Comment by andy-sweet** [comment] 2023-05-18 18:22
I can reproduce with v0.4.17, but not on main (at 0dfb37b474490b4d9829c4fa93cb3d648b4b186d). Seems like https://github.com/napari/napari/pull/5003 fixed this, but I can't explain why yet - will look for an explanation before closing this issue and see if there's any other way to reproduce similar issues that might need more general fixes.

@tathey1 : unfortunately, we haven't had a release since `v0.4.17` so the fix isn't available in a stable form yet. If you're comfortable using `main` and also find this is no longer as issue, please report. Otherwise, I'll try to update this when a fix is a ready in a release.

**Comment by psobolewskiPhD** [comment] 2023-05-18 19:13
I'm on macOS arm64 and likewise cannot reproduce, so it does appear fixed on `main`.

BTW If this is key to your work and you are using conda, you can try the conda nightly build using conda-forge (I recommend `mamba`):
`conda create -n napari-main -c "napari/label/nightly" -c conda-forge napari python=3.10`

**Comment by tathey1** [comment] 2023-05-18 20:31
Thank you! I have been able to bypass this issue so it is not really urgent for me, but I really appreciate your solution.

**Comment by psobolewskiPhD** [comment] 2023-08-30 00:38
I can't reproduce this on release 0.4.18, so going to close.
If it re-occurs, please let us know!

**Closed as completed by psobolewskiPhD** 2023-08-30 00:38 UTC
Labels: bug
