### ISSUE TITLE
Layer selection 'blue rectangle' is buggy when expanding layer properties

### ISSUE THREAD

**Issue by royerloic** [napari/napari#131] opened 2019-03-01 10:08 UTC
## 🐛 Bug

When trying example 'add_images.py', I noticed that the blue rectangle that indicates selection
is not always shown when one layer is expanded to show its properties.

## To Reproduce

1. run 'add_images.py'
2. expand properties for first layer
3. blue rectangle that indicates selected layer disappears
4. selecting one or the other layer is not always indicated by blue rectangle,
    multiple clicks are needed to bring back the blue rectangle.

Here is how it looks like when the one layer is selected but the corresponding
blue rectangle is not shown:
![image](https://user-images.githubusercontent.com/1870994/53630821-dcc4ec80-3bc5-11e9-9f81-2b5edbdab4e3.png)

Here is a video:

https://drive.google.com/file/d/1Y-sqypEKHh0c0nlRvKZ7_y8DnSdabExi/view?usp=sharing

## Expected behavior

At least one blue rectangle should always be displayed.

## Environment

 - napari-gui Version (e.g., 1.0): master 
 - OS (e.g., Linux): problem exists on OSX 10.14.1, but seems to work on linux
 - Python version: 3.7
 - Any other relevant information: None

## Additional context

None

**Comment by sofroniewn** [comment] 2019-03-01 17:59
Just to make sure I understand 

1. is the app behaving as if the layer were selected (i.e. you can see the corresponding clims highlighted / get hover information from the layer but the blue rectangle is not there)?
2. or are you simply noting that it is possible to unselect all the layers (even if one is expanded)
3. or finally are you noting that adjusting the sliders / text etc. or a non-selected layer doesn't cause it to become selected?

I think you're really describing 3. and the fact that it is possible to have "no layers selected". Having no layers selected to me is fine (and matches photoshop). If you click in the space between the layers (or below them) they will all unselect. I think the problem (as described in #124 is that you can interact with the layer property widgets (sliders / buttons / text etc.) without selecting the layer. I think the solution may be to make the first click select the layer, regardless of where it is and then allow for followup clicks to manipulate the widgets

**Comment by jni** [comment] 2019-03-01 23:11
Hey @sofroniewn! It is in fact (1), but I just saw that I can't reproduce on my machine. @royerloic is preparing a video. =)

**Comment by sofroniewn** [comment] 2019-03-03 23:23
I think it is only affecting the markes layer - just reproduced on mine, will look into fixing

**Comment by sofroniewn** [comment] 2019-03-04 02:45
ah could reproduce some funky behavior on images too

**Comment by sofroniewn** [comment] 2019-03-04 02:53
some of it seems to be around PyQt refreshes :-(

Here are my steps to reproduce

1. run 'add_images.py' (both layers should be selected with blue around them)
2. double click the `Image 0` layer to expand its properties (now just it should be selected with blue around)
3. click on the `Image 1` layer. Now unfortunately neither layer appear selected, but the clims bar on the left still appears and the hover information still appears - and these actually do correspond to the `Image 1` layer indicating that at least some of the app thinks the layer has been selected.
4. If at this point though you simply change to another application and then change back to Napari when you return the little blue line will appear again around the `Image 1` layer (even though you didn't do anymore clicking / selecting within Napari)

This suggests to me that the bug has to do with the refreshing of the PyQt. Maybe we can throw an extra `refresh` or `update` call in there and it will be ok. Or maybe we will solve when we fix all the stylings - see #13

**Comment by sofroniewn** [comment] 2019-04-30 05:44
We have now improved our stylings with #236 and I have not observed this behaviour since then so I am closing this issue

**Closed as completed by sofroniewn** 2019-04-30 05:44 UTC
Labels: bug
