### ISSUE TITLE
Run a function on napari close

### ISSUE THREAD

**Issue by averypennington** [napari/napari#5945] opened 2023-06-16 15:06 UTC
## 🚀 Feature

The ability to run a function on napari close, e.g. for cleanup. Helpful for plugins that have started another process which should be stopped when napari closes.

## Motivation

A plugin for Napari, SuRVoS2, starts a server process for backend processing and while there is a button for stopping the server, it would be better to automatically shut it down when closing napari.

## Pitch

A simple way to have a function run at close would simplify the operation of certain types of plugins.

## Alternatives

There may be a built-in way to do this using a close event in PyQT but it wasn't obvious to me.

**Comment by Czaki** [comment] 2023-06-16 15:09
It looks like a duplicate of #5687. Could you read the linked issue and told if there is a proper response to your issue?

**Comment by penningavery** [comment] 2023-06-16 15:37
Thank you, yes, it's a duplicate and I think that discussion there has solved my problem.

**Comment by psobolewskiPhD** [comment] 2023-06-16 16:49
Awesome! Glad your problem is resolved!
Thanks @Czaki 
@penningavery I'm going to close, but feel free to comment in #5687

**Closed as completed by psobolewskiPhD** 2023-06-16 16:49 UTC
Labels: feature
