### ISSUE TITLE
Color cleanup?

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1491] opened 2020-07-20 19:32 UTC
## 🚀 Feature
I haven't worked too much with color data in napari, so I don't know all the complexities, but I'd like to hear some discussion about it.  At quick glance, we seem to have lots of different transformation functions, and a lot of vendored code, but the API for how we're supposed to be using colors internally is a little unclear.

I ran into this when hashing an object that had a color as an `np.ndarray`, (it was an issue since the `__eq__`  method wasn't using `np.all( == )`), so I went looking for a "to_hex" ... which I did find, but in a seemingly unrelated place to the `transform_color` function I had previously used.  I know we opted for a 1x4 np.ndarray internal representation before, but at times I wish we were just using some color object from an external library, that had centralized convenience methods, and without all the vendoring...  

Is that possible?  or too many edge cases?  thoughts?

**Comment by sofroniewn** [comment] 2020-07-20 21:34
> but at times I wish we were just using some color object from an external library, that had centralized convenience methods, and without all the vendoring

yeah, I mean there are definitely tradeoffs here, particularly if you are most often dealing with a single color or an array of colors. VisPy has both, but I'd prefer not to use the VisPy color objects in our model code and want things that can easily be serialized and unambiguously reproduced and shared.

If there is a small package that only does color handling then maybe we would to do add that dependency, or maybe we want to create a small package `napari/coloring` that we can depend on that only does colors and colormaps. Note I'd really like to have a generic colormap representation in #862 too, as right now writer plugins like `napari-svg` are either broken for colormaps or have to depend on vispy, which is a really intense dependency for something that just wants to write an svg.

Note that I think this conversation is mostly separate from #1356, but I'll put a link there just in case.

I guess my vote if things are becoming unwieldy is to look for and if non-existing make a tiny, well-tested and stable package `napari/color` that only does all the color and colormap conversions exactly the way we want them.

Curious what @jni and @kevinyamauchi, who has spent the most time with this lately, feel?

**Comment by tlambert03** [comment] 2020-07-20 21:37
> If there is a small package that only does color handling then maybe we would to do add that dependency,

@GenevieveBuckley  pointed me to this recently: https://github.com/vaab/colour

**Comment by jni** [comment] 2020-07-21 09:33
Yep, I definitely see the need for a color module. As I've mentioned repeatedly over the past few weeks, I'd rather *not* pick up a new dependency in the project — we are on a dependency diet. =P I would also like to leave it within napari proper for now because the multi-package stuff was painful when it comes to conda-forge.

So, my suggestion for the moment is to have our own thing in a folder/subpackage. Happy at this point to diverge from the vendored mpl/vispy code we've been using, as long as we end up somewhere simple and lightweight.

**Comment by kevinyamauchi** [comment] 2020-07-21 16:07
Thanks for making this issue, @tlambert03 ! Given the emerging dataclasses, I agree it's a good time to review how we represent color.

Pulling in [the discussion from the zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/color.20transforms), it sounds like the primary points are:

- the function to standardize colors are spread around and thus difficult to discover/follow
- determining if colors are equal is not as straightforward as it could be
- single colors should be 1D arrays and groups of colors should be 2D arrays

Does that sound right?

I definitely agree with all of those points, especially the one about the organization of the color standardization functions. I also forget what to use sometimes. To me, It seems like we could make a decent dent in addressing those points by organizing the color standardization code it its own folder/module, as suggested by @jni . We can also modify the functions related to standardized colors to return a 1D array for single colors. I'd vote for a module of standardization functions over a color object for now. If we find we haven't addressed, we can convert to a color class. I am happy to take a shot at this.

**Comment by tlambert03** [comment] 2020-07-21 16:27
yeah, sounds great to me.  `napari.colors` or `napari.utils.colors` ... perhaps even as a first stab, just for the sake of organization, one could just with that module importing from other places around the package and creating a centralized collection with the "API" that someone would be using internally.

I'm not set on a color class either ... but it _would_ be super nice if you could check for equality of colors using `==` (which we can't do with an array) ...

**Comment by sofroniewn** [comment] 2020-07-21 23:00
> yeah, sounds great to me. napari.colors or napari.utils.colors ... perhaps even as a first stab, just for the sake of organization, one could just with that module importing from other places around the package and creating a centralized collection with the "API" that someone would be using internally.

I'd like the idea of this too - I'd also put our colormap stuff in there too!!

**Comment by sofroniewn** [comment] 2020-07-23 03:15
@kevinyamauchi sorry we ran out of time before discussing this today.

>  It seems like we could make a decent dent in addressing those points by organizing the color standardization code it its own folder/module

Do you have a clear enough idea of this to take a first pass. I think things like #1356 and a #1475 style `ColorManager` can come later, but first would just be to have some organization. I lean towards `napari.colors` imports.

**Comment by kevinyamauchi** [comment] 2020-07-23 20:18
> @kevinyamauchi sorry we ran out of time before discussing this today.

No worries! Lots of good discussion.

> Do you have a clear enough idea of this to take a first pass.

I think we can do the following in this first pass. Thoughts?
- consolidate the functions related to standardizing colors and colormaps under `napari.colors` (or `napari.color`?)
- change the color standardization functions such that they return a 1D RGBA array when returning a single color (to eliminate all of the (`transfor_color()[0]` patterns sprinkled around the code base)

I agree that the `ColorManager` can come later, after we've solidified the dataclass usage, etc..

**Comment by sofroniewn** [comment] 2021-09-02 22:31
Closing now as was a discussion at the time, but @andy-sweet might want to read through this just to keep in mind as you go forward with properties stuff. If anything important we can open dedicated issues for pieces, thanks!!

**Closed as completed by sofroniewn** 2021-09-02 22:31 UTC
Labels: question
