### ISSUE TITLE
Convert an Image layer to Labels reset the scale to [1,1,1] on a 3d image

### ISSUE THREAD

**Issue by bpavie** [napari/napari#6981] opened 2024-06-12 09:53 UTC
### 🐛 Bug Report

When a layer is converted from an _Image_ to _Labels_, the scale of the image is not preserved and is reset to [1,1,1]

### 💡 Steps to Reproduce

1. Start Napari
2. Open the sample "Cells (3d+2Ch)" `File>Open Sample>Napari>Cells (3d+2Ch)`
3. Check the scale of the channel "nuclei": 
```
viewer.layers['nuclei'].scale
Out[1]: array([1., 1., 1.])`
```
4. Modify the sale:
```
viewer.layers['nuclei'].scale = [0.5,0.5,0.5]
```
4. Convert the label "nuclei" to _Labels_ (right click on the nuclei layer > `Convert to labels`)
6. Check now the scale on the same layer which is now a labels:
```
viewer.layers['nuclei'].scale
Out[3]: array([1., 1., 1.])
```
As we can see, the scale has been rest to `[1,1,1]`

### 💡 Expected Behavior

The scale of the layer should be preserved after a conversion from one type to another (e.g. from image to layer).
That will allow user to load labels in e.g. ome.tiff format using the `napari-aicsimageio plugin` which preserve the scale by simple drag and drop, then the user will convert it to labels and the original scale would be then preserved . Right now, user has to use the command line to check the scale and set it manually after conversion from image to labels.

### 🌎 Environment

napari --info
napari: 0.4.15
Platform: Windows-10-10.0.22631-SP0
Python: 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:38:46) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.24.4
SciPy: 1.9.1
Dask: 2024.5.2
VisPy: 0.14.2

OpenGL:
  - GL version:  4.6.0 - Build 31.0.101.5186
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1920x1080, scale 1.0

Plugins:
  - bfio: 2.3.0
  - scikit-image: 0.4.15
  - svg: 0.1.10

### 💡 Additional Context

Napari has been installed using pip on windows

```bash
conda create -n napari python=3.9
conda activate napari
pip install napari
```

**Comment by psobolewskiPhD** [comment] 2024-06-12 12:35
Hi! Thanks for opening the issue.
napari 0.4.15 is pretty old and I cannot reproduce this in the most recent napari, napari 0.4.19
Looking into it a bit more, it looks like this was fixed here: https://github.com/napari/napari/pull/4272
Which means it should have been released in napari 0.4.16

Please try a newer napari version. 
I'm going to close this issue, because it's fixed in current napari and we can't fix old versions.
But if you have some questions or comments, feel free to post here and we will do our best to address them.

**Closed as completed by psobolewskiPhD** 2024-06-12 12:35 UTC
Labels: bug
