### ISSUE TITLE
Strange misbehaving of labels screenshots

### ISSUE THREAD

**Issue by jni** [napari/napari#1237] opened 2020-05-11 08:36 UTC
## 🐛 Bug

Side note, I discovered this while employing a neat workaround to the fact that notebooks using napari don't show the state of the napari viewer at the time that you move to the next cell. So now, when I want embed a record of the viewer in the notebook, I type:

```python
plt.imshow(viewer.screenshot(with_viewer=True))
```
into a cell and now viewers can see the viewer at that particular point. It's pretty nice! Currently it shows axis ticks around the screenshot but that can be tweaked.

Anyway, in this particular case, it totally misrepresented *some* of the labels. Compare the system screenshot with the napari `screenshot` method.

- macOS screenshot:

<img width="1200" alt="Screen Shot 2020-05-11 at 6 06 56 pm" src="https://user-images.githubusercontent.com/492549/81541080-ef37da00-93b5-11ea-889d-af7233adea3e.png">

- napari screenshot:

<img width="382" alt="Unknown" src="https://user-images.githubusercontent.com/492549/81541129-ffe85000-93b5-11ea-82e8-af8a2100149d.png">

Notice the weird colour fringes for the coins at coin-coordinates (row, column) (0, 1) and (1, 2). 

## To Reproduce

This is taken from the "watershed" section in this notebook:

https://github.com/jni/skimage-tutorials/blob/monash-df2020-05-completed/lectures/4_segmentation.ipynb

It involves a bit of manual clicking so I don't know how easy it will be to reproduce.

**Comment by GenevieveBuckley** [comment] 2020-05-22 04:57
Could this be something to do with how matplotlib is down-sampling the plot display?

* I wonder what happens if you increase the matplotlib figure size?
* I also wonder what happens if you save the screenshot array with `io.imsave('test.png', viewer.screenshot(with_viewer=True))` and then look at that?

**Comment by GenevieveBuckley** [comment] 2020-05-22 05:47
I think I can kind of reproduce this on Windows.

See:
* First row, third coin across - marker point looks blue on screen but dark green-ish in some screenshots and has a dark green-ish ring around part of the coin edge.
* Second row, third coin across - both point and coin appear yellow on screen, but 
* Using `with_viewer=False` also changes the quality of the colours displayed (for the worse, in my opinion). Everything looks a bit more saturated/lighter.
## Windows built-in snipping tool
<img width="954" alt="windows-snip" src="https://user-images.githubusercontent.com/30920819/82633834-8e26c680-9c3f-11ea-97e5-7ccd20bc1b7b.PNG">

## napari screenshot saved to file
```
io.imsave('filename1.png', viewer.screenshot(with_viewer=True))
```
![napari-screenshot-withviewerTrue](https://user-images.githubusercontent.com/30920819/82633901-c1695580-9c3f-11ea-8b14-dc81152bcdb9.png)

## napari screenshot saved to file
```
io.imsave('filename1.png', viewer.screenshot(with_viewer=False))
```
![napari-screenshot-withviewerFalse](https://user-images.githubusercontent.com/30920819/82633932-d2b26200-9c3f-11ea-9195-289fcdedc2ce.png)

## matplotlib in the jupyter notebook (`with_viewer=True`)
![matplotlib-jupyter-withviewerTrue](https://user-images.githubusercontent.com/30920819/82633952-e2ca4180-9c3f-11ea-9aba-6c3a825f28b9.png)

## matplotlib in the jupyter notebook (`with_viewer=False`)
![matplotlib-jupyter-withviewerFalse](https://user-images.githubusercontent.com/30920819/82634001-0ab9a500-9c40-11ea-884a-b6cb3388b69e.png)



It's not too surprising that there might be a difference between screenshots with `with_viewer=True` vs `with_viewer=False`, since they are actually generated in different ways.

* `with_viewer=True`
    Uses `Window()` class in `qt_main_window.py`
    Screenshot method uses `self._qt_window.grab().toImage()` and puts that in `QImg2array()`
* `with_viewer=False`
    Uses `QtViewer()` class in `qt_viewer.py`
    Screenshot method uses `self.canvas.native.grabFramebuffer()` and puts that in `QImg2array()`

**Comment by kne42** [comment] 2020-09-08 18:28
I was able to reproduce this using specific colors with shapes in [this notebook](https://gist.github.com/kne42/ceb41bca2b68f85a350349b7da523d8c).

<img width="1200" alt="Screen Shot 2020-09-08 at 10 52 52 AM" src="https://user-images.githubusercontent.com/29165011/92513687-8f1b3e00-f1c5-11ea-9096-0e6f5d39202f.png">

![ex2](https://user-images.githubusercontent.com/29165011/92513676-8b87b700-f1c5-11ea-8a92-3862cc24bc22.png)

All of these colors exhibiting weird screenshot behavior have an r, g, or b value at its extreme (e.g. [255, 0, 0]). It appears that when they blend with a white square, the rgb values get inversed: e.g. a color like [255, 0, 255] becomes a color similar to [0, 255, 0].

My working theory for the infidelity of the colors when taking a screenshot of the canvas is due to them being partially transparent and blending in with the background color that whatever tool you open it with chooses (see #1566).

**Comment by psobolewskiPhD** [comment] 2024-02-04 19:17
The notebook from the OP isn't accessible anymore, but I used the notebook from Kira posted here:
https://github.com/napari/napari/issues/1237#issuecomment-689056808

Using `main` I cannot reproduce this, everything looks fine:
<img width="1198" alt="image" src="https://github.com/napari/napari/assets/76622105/a8ac7841-9b84-4d23-b5ba-bb0e1d1957cf">

Looks like this was fixed by https://github.com/vispy/vispy/pull/2090
So going to close. If there's a new reproducer, please make a new issue!

**Closed as completed by psobolewskiPhD** 2024-02-04 19:17 UTC
Labels: bug, priority:high, topic:vispy
