### ISSUE TITLE
[main] TypeError when adding points by GUI

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5801] opened 2023-05-03 08:52 UTC
## 🐛 Bug

When adding new points via GUI, about every 2nd or 3rd results in an Error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/Dev/miniforge3/envs/napari-dev/lib/python3.10/site-packages/superqt/utils/_throttler.py:369, in _make_decorator.<locals>.deco.<locals>.inner.<locals>.<lambda>()
    366     future.cancel()
    368 future = Future()
--> 369 last_f = lambda: future.set_result(func(*args, **kwargs))  # noqa
        future = <Future at 0x28e9ff7f0 state=pending>
        func = <bound method VispyCanvas._on_mouse_move of <napari._vispy.canvas.VispyCanvas object at 0x169785750>>
        args = (<MouseEvent blocked=False button=1 buttons=[1] delta=[0. 0.] handled=False is_dragging=True last_event=MouseEvent modifiers=() native=<PyQt5.QtGui.QMouseEvent object at 0x28ece4ee0> pos=[233 728] press_event=MouseEvent source=<NapariSceneCanvas (PyQt5) at 0x16978e800> sources=[<NapariSceneCanvas (PyQt5) at 0x16978e800>] time=1683103404.228812 type=mouse_move>,)
        kwargs = {}
    370 throttle.triggered.connect(last_f)
    371 throttle.throttle()

File ~/Dev/napari/napari/_vispy/canvas.py:424, in VispyCanvas._on_mouse_move(self=<napari._vispy.canvas.VispyCanvas object>, event=<MouseEvent blocked=False button=1 buttons=[1] d...978e800>] time=1683103404.228812 type=mouse_move>)
    412 def _on_mouse_move(self, event: MouseEvent) -> None:
    413     """Called whenever mouse moves over canvas.
    414 
    415     Parameters
   (...)
    422     None
    423     """
--> 424     self._process_mouse_event(mouse_move_callbacks, event)
        event = <MouseEvent blocked=False button=1 buttons=[1] delta=[0. 0.] handled=False is_dragging=True last_event=MouseEvent modifiers=() native=<PyQt5.QtGui.QMouseEvent object at 0x28ece4ee0> pos=[233 728] press_event=MouseEvent source=<NapariSceneCanvas (PyQt5) at 0x16978e800> sources=[<NapariSceneCanvas (PyQt5) at 0x16978e800>] time=1683103404.228812 type=mouse_move>
        self = <napari._vispy.canvas.VispyCanvas object at 0x169785750>

File ~/Dev/napari/napari/_vispy/canvas.py:385, in VispyCanvas._process_mouse_event(self=<napari._vispy.canvas.VispyCanvas object>, mouse_callbacks=<function mouse_move_callbacks>, event=<ReadOnlyWrapper at 0x29178c800 for MouseEvent>)
    383 layer = self.viewer.layers.selection.active
    384 if layer is not None:
--> 385     mouse_callbacks(layer, event)
        event = <ReadOnlyWrapper at 0x29178c800 for MouseEvent at 0x16d7550f0>
        layer = <Points layer 'Points' at 0x16d700280>
        mouse_callbacks = <function mouse_move_callbacks at 0x14f1909d0>

File ~/Dev/napari/napari/utils/interactions.py:178, in mouse_move_callbacks(obj=<Points layer 'Points'>, event=<ReadOnlyWrapper at 0x29178c800 for MouseEvent>)
    175 obj._persisted_mouse_event[gen].__wrapped__ = event
    176 try:
    177     # try to advance the generator
--> 178     next(gen)
        gen = <generator object add at 0x16d495d20>
    179 except StopIteration:
    180     # If done deleted the generator and stored event
    181     del obj._mouse_drag_gen[func]

File ~/Dev/napari/napari/layers/points/_points_mouse_bindings.py:122, in add(layer=<Points layer 'Points'>, event=<ReadOnlyWrapper at 0x29161d200 for ReadOnlyWrapper>)
    119     dist = np.linalg.norm(start_pos - event.pos)
    120     if dist < DRAG_DIST_THRESHOLD:
    121         # prevent vispy from moving the canvas if we're below threshold
--> 122         event.handled = True
        event = <ReadOnlyWrapper at 0x29161d200 for ReadOnlyWrapper at 0x29178c800>
    123     yield
    125 # in some weird cases you might have press and release without move,
    126 # so we just make 100% sure dist is correct

File ~/Dev/napari/napari/utils/_proxies.py:29, in ReadOnlyWrapper.__setattr__(self=<ReadOnlyWrapper at 0x29161d200 for ReadOnlyWrapper>, name='handled', val=True)
     24 def __setattr__(self, name, val):
     25     if (
     26         name not in ('__wrapped__', '_self_exceptions')
     27         and name not in self._self_exceptions
     28     ):
---> 29         raise TypeError(
        trans = <napari.utils.translations.TranslationBundle object at 0x138facfa0>
        name = 'handled'
     30             trans._(
     31                 'cannot set attribute {name}',
     32                 deferred=True,
     33                 name=name,
     34             )
     35         )
     37     super().__setattr__(name, val)

TypeError: cannot set attribute handled
```

Introduced in https://github.com/napari/napari/pull/5742
cc: @brisvag 

## To Reproduce

1. install napari from main after https://github.com/napari/napari/pull/5742
2. run napari
3. add new points layer using GUI
4. start adding new points randomly

## Expected behavior

No error.

## Environment

```
napari: 0.5.0a2.dev109+gd91f4ee5
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:12:31) [Clang 14.0.6 ]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.3
SciPy: 1.10.1
Dask: 2023.4.1
VisPy: 0.12.2
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Settings path:
  - /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml
Plugins:
  - napari: 0.5.0a2.dev109+gd91f4ee5 (77 contributions)
  - napari-console: 0.0.8 (0 contributions)
  - napari-svg: 0.1.6 (2 contributions)
```

## Additional context

Sorry I didn't test that PR 😢

**Comment by Czaki** [comment] 2023-05-03 09:17
@psobolewskiPhD did this PR solves your issue #5797

**Comment by brisvag** [comment] 2023-05-03 09:38
Yup, this was not introduced in #5742; it was broken in #5432 and is fixed by #5797.

**Comment by brisvag** [comment] 2023-05-03 09:39
I just merged that; main should be fine now.

**Closed as completed by brisvag** 2023-05-03 09:39 UTC
Labels: bug

**Comment by psobolewskiPhD** [comment] 2023-05-03 09:41
yes #5797 fixes it!
I was testing with `fb7da0a1` checked out and was getting the issue, so 🤷‍♂️ 
and now it's fixed on main, so GG.

**Comment by psobolewskiPhD** [comment] 2023-05-03 09:45
Note: the history of those PRs is odd, here's what I see for main:
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/76622105/235883433-b7f1b9aa-6489-4cd4-8cb8-b0f5432fc7e9.png">

#5432 was merged before #5742

**Comment by brisvag** [comment] 2023-05-03 09:51
Yeah, by that I just meant that the cause if the issue was not the pr itself (i.e: no need to revert), but that it was the refactor/merge combination. But yeah, I messed up that merge :P

**Comment by psobolewskiPhD** [comment] 2023-05-03 13:13
Thanks for clarifying! I'm just trying to maintain sanity and better get what was going on!
