### ISSUE TITLE
label export generates incompatible files

### ISSUE THREAD

**Issue by ghost** [napari/napari#6044] opened 2023-07-06 19:49 UTC
## label export generates incompatible files

Label (uint32) export as .tif generates incompatible files ( for common python tiff libaries) **_when using stacks_**

## To Reproduce
1. import an image stack into napari
2. do some kine of segmentation
3. export that label layer (uint32) as tif file
4. try to load it into python (tested with skimage, tifffile, PIL, pylibtiff, matplotlib)

Example repo: https://git.mpi-cbg.de/pstark/napari-tiff-compatibility-issues
Also look here: https://forum.image.sc/t/napari-tiff-compatibility-and-label-export/83303

## Expected behavior
Succesful import as numpy array

## Additional tests and problems
1. The exported files are ok: reimport to napari or opening in gimp works 
2. after conversion with gimp to LZW or pack bits compression pylibtiff can import the label image stack correctly.
3. I also wanted to test layers with type uint8 but I am unable to export due to this error: "Unable to allocate 6.71 GiB for an array with shape (200, 3000, 3000) and data type uint32". I have 16GB of RAM and the layertype is defnitly uint8, so I don't know what whats goint on there. I also never had this error when exporting the original label layer, or other for stacks smaller than 200 layers @ 3000x3000, which actually use uint32. Larger stacks throw the same error (with different values for shape and size ofcourse).
4. Interestingly napari is also unable to read any resaved tiffile 

## Environment
napari: 0.4.17
Platform: Windows-10-10.0.22621-SP0
Python: 3.9.16 | packaged by conda-forge | (main, Feb 1 2023, 21:28:38) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.22.0
SciPy: 1.10.1
Dask: 2023.5.1
VisPy: 0.11.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
- GL version: 4.6.0 NVIDIA 535.98
- MAX_TEXTURE_SIZE: 32768

**Comment by T3chbug** [comment] 2023-07-06 19:56
> This issue has been mentioned on **Image.sc Forum**. There might be relevant details there:
> 
> https://forum.image.sc/t/napari-tiff-compatibility-and-label-export/83303/3

That's the one I already linked in the post, very clever bot /s

**Comment by cgohlke** [comment] 2023-07-07 00:41
> try to load it into python (tested with skimage, tifffile, PIL, pylibtiff, matplotlib)

> The exported files are ok: reimport to napari or opening in gimp works

? I'm not sure I understand the issue. 

The file `label_napari.tif` was written by tifffile with deflate compression. It is valid TIFF and can be read by tifffile, Fiji, napari, and imagecodecs for example. Pillow converts to int32.

The file `label_uncompressed.tif` is not a valid TIFF. It was written and corrupted/truncated by unknown software. The un-corrupted pages can still be read by Fiji, tifffile low level API, or imagecodecs.

The files `label_LZW.tif` and `label_pack_bits.tif` were written by unknown software, adding an image to the content. Fiji and imagecodecs can still read the stack. The issue for tifffile is that a preview image was added as a second page, such that the file content is out of sync with the tifffile metadata in the file. Omitting the second page works:
```python
pages = list(range(201))
del pages[1]
a = tifffile.imread('label_LZW.tif', key=pages)
```

It is risky to edit/rewrite TIFF files containing tifffile, ImageJ, or OME metadata with software that is not aware of those formats. The metadata and file content might get out of sync.

**Comment by T3chbug** [comment] 2023-07-07 06:00
> The file `label_napari.tif` was written by tifffile with deflate compression. It is valid TIFF and can be read by tifffile, Fiji, napari, and imagecodecs for example. Pillow converts to int32.

The issue is that importing with tifffile does NOT work (libdeflate_zlib_decompress returned LIBDEFLATE_BAD_DATA), which is the reason I tried these conversions (using gimp) in the first place. That napari can't open them was just another curios observation, I now also tested resaves with Fiji (LZW and uncompressed), both are readable by napari (But as I said, that wasn't really the issue here).

**Comment by jni** [comment] 2023-07-07 06:09
> The issue is that importing with tifffile does NOT work

Can you elaborate with some code, your tifffile and Python versions, and a full traceback? As @cgohlke has experienced, I can open this fine locally:

```python
In [1]: import tifffile
In [2]: labels = tifffile.imread('label_napari.tif')
In [3]: labels.shape
Out[3]: (200, 3000, 3000)
In [4]: labels.dtype
Out[4]: dtype('uint32')
In [5]: np.max(labels)
Out[5]: 100392
In [6]: tifffile.__version__
Out[6]: '2022.4.8'
```

There might be some error in your Python installation?

**Comment by T3chbug** [comment] 2023-07-07 06:15
tifffileversion: 2021.7.2

## Full Traceback:
```
DeflateError                              Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_20504\2171558388.py in <cell line: 1>()
----> 1 img = tifffile.imread("label_napari.tif")

~\anaconda3\envs\nc1\lib\site-packages\tifffile\tifffile.py in imread(files, aszarr, **kwargs)
    817                 if aszarr:
    818                     return tif.aszarr(**kwargs)
--> 819                 return tif.asarray(**kwargs)
    820 
    821     with TiffSequence(files, **kwargs_seq) as imseq:

~\anaconda3\envs\nc1\lib\site-packages\tifffile\tifffile.py in asarray(self, key, series, level, squeeze, out, maxworkers)
   3230             result = pages[0].asarray(out=out, maxworkers=maxworkers)
   3231         else:
-> 3232             result = stack_pages(pages, out=out, maxworkers=maxworkers)
   3233 
   3234         if result is None:

~\anaconda3\envs\nc1\lib\site-packages\tifffile\tifffile.py in stack_pages(pages, out, maxworkers, **kwargs)
  15674         page0.decode  # init TiffPage.decode function
  15675         with ThreadPoolExecutor(maxworkers) as executor:
> 15676             for _ in executor.map(func, pages, range(npages)):
  15677                 pass
  15678 

~\anaconda3\envs\nc1\lib\concurrent\futures\_base.py in result_iterator()
    619                     # Careful not to keep a reference to the popped future
    620                     if timeout is None:
--> 621                         yield _result_or_cancel(fs.pop())
    622                     else:
    623                         yield _result_or_cancel(fs.pop(), end_time - time.monotonic())

~\anaconda3\envs\nc1\lib\concurrent\futures\_base.py in _result_or_cancel(***failed resolving arguments***)
    317     try:
    318         try:
--> 319             return fut.result(timeout)
    320         finally:
    321             fut.cancel()

~\anaconda3\envs\nc1\lib\concurrent\futures\_base.py in result(self, timeout)
    449                     raise CancelledError()
    450                 elif self._state == FINISHED:
--> 451                     return self.__get_result()
    452 
    453                 self._condition.wait(timeout)

~\anaconda3\envs\nc1\lib\concurrent\futures\_base.py in __get_result(self)
    401         if self._exception:
    402             try:
--> 403                 raise self._exception
    404             finally:
    405                 # Break a reference cycle with the exception in self._exception

~\anaconda3\envs\nc1\lib\concurrent\futures\thread.py in run(self)
     56 
     57         try:
---> 58             result = self.fn(*self.args, **self.kwargs)
     59         except BaseException as exc:
     60             self.future.set_exception(exc)

~\anaconda3\envs\nc1\lib\site-packages\tifffile\tifffile.py in func(page, index, out, filecache, kwargs)
  15665         if page is not None:
  15666             filecache.open(page.parent.filehandle)
> 15667             page.asarray(lock=filecache.lock, out=out[index], **kwargs)
  15668             filecache.close(page.parent.filehandle)
  15669 

~\anaconda3\envs\nc1\lib\site-packages\tifffile\tifffile.py in asarray(self, out, squeeze, lock, maxworkers)
   6496                 #     pass  # corrupted files e.g. with too many strips
   6497 
-> 6498             for _ in self.segments(
   6499                 func=func,
   6500                 lock=lock,

~\anaconda3\envs\nc1\lib\site-packages\tifffile\tifffile.py in segments(self, lock, maxworkers, func, sort, _fullsize)
   6349                 flat=True,
   6350             ):
-> 6351                 yield decode(segment)
   6352         else:
   6353             # reduce memory overhead by processing chunks of up to

~\anaconda3\envs\nc1\lib\site-packages\tifffile\tifffile.py in decode(args, decodeargs, keyframe, func)
   6337                 args, decodeargs=decodeargs, keyframe=keyframe, func=func
   6338             ):
-> 6339                 return func(keyframe.decode(*args, **decodeargs))
   6340 
   6341         if maxworkers is None or maxworkers < 1:

~\anaconda3\envs\nc1\lib\site-packages\tifffile\tifffile.py in decode(data, segmentindex, jpegtables, _fullsize)
   6295                 # TODO: calculate correct size for packed integers
   6296                 size = shape[0] * shape[1] * shape[2] * shape[3]
-> 6297                 data = decompress(data, out=size * dtype.itemsize)
   6298             data = unpack(data)
   6299             data = reshape(data, index, shape)

imagecodecs\_deflate.pyx in imagecodecs._deflate.deflate_decode()

DeflateError: libdeflate_zlib_decompress returned LIBDEFLATE_BAD_DATA
```

**Comment by jni** [comment] 2023-07-07 06:21
@cgohlke should be able to comment more intelligently, but in the meantime I would try updating to newer versions of tifffile and imagecodecs to see if that fixes your problem...

**Comment by cgohlke** [comment] 2023-07-07 06:25
> The issue is that importing with tifffile does NOT work (libdeflate_zlib_decompress returned LIBDEFLATE_BAD_DATA),

Thanks for clarifying. It looks like a flawed build/version of `libdeflate`. Can you try to upgrade `tifffile` and `imagecodecs` to more recent versions, or manually remove the `imagecodecs/_deflate` extension, or temporarily uninstall the `imagecodecs` package?

**Comment by T3chbug** [comment] 2023-07-07 06:35
I just created a new environmet with a fresh python 3.9.17 and tifffile 2021.7.2, _conda update_ couldn't find newer versions. Still the same problem importing the original napari tif, and still working for some of the converted images. 
Update: after manually removing __deflate.cp39-win_amd64.pyd_ it works ?!
What kind of bug is that? Thank you for the fix, but is there a more elegant method than manually deleting package files?

**Comment by cgohlke** [comment] 2023-07-07 14:54
Could you please post the output of `python -c"import imagecodecs;print(imagecodecs.version())"`

**Comment by T3chbug** [comment] 2023-07-07 18:44
imagecodecs-2021.8.26, cython-0.29.33, numpy-1.24.3, numpy_abi-0x1000009.14, imcd-2021.8.26, avif-n/a, bitshuffle-0.3.5, blosc2-n/a, brotli-1.0.9, brunsli-n/a, c-blosc-1.21.3, cfitsio-3.47, charls-2.2.0, deflate-n/a, giflib-5.2.1, gzip-n/a, imcd-2021.8.26, jpeg12-n/a, jpegsof3-2020.12.22, jpegxl-n/a, jxrlib-1.1, lerc-3.0.0, libaec-1.0.5, libbzip2-1.0.8, libjpeg-9.5, liblj92-2014, liblzf-1.5, liblzma-5.2.10, libpng-1.6.37, libtiff-4.5.0, libwebp-1.2.4, lz4-1.9.4, openjpeg-2.4.0, pg_lzcompress-13.2, snappy-1.1.7, zfp-0.5.5, zlib-1.2.13, zlibng-n/a, zopfli-1.0.3, zstd-1.5.2

**Comment by cgohlke** [comment] 2023-07-07 19:14
> deflate-n/a

That means the deflate extension is not available or failed to import. Something is off with the build or environment.

**Comment by T3chbug** [comment] 2023-07-07 19:48
imagecodecs-2021.8.26, cython-0.29.33, numpy-1.25.0, numpy_abi-0x1000009.13, imcd-2021.8.26, avif-n/a, bitshuffle-0.3.5, blosc2-n/a, brotli-1.0.9, brunsli-n/a, c-blosc-1.21.3, cfitsio-3.47, charls-2.2.0, giflib-5.2.1, imcd-2021.8.26, jpeg12-n/a, jpegsof3-2020.12.22, jpegxl-n/a, jxrlib-1.1, lerc-3.0.0, libaec-1.0.5, libbzip2-1.0.8, libdeflate-1.17, libjpeg-9.5, liblj92-2014, liblzf-1.5, liblzma-5.2.10, libpng-1.6.37, libtiff-4.5.0, libwebp-1.2.4, lz4-1.9.4, openjpeg-2.4.0, pg_lzcompress-13.2, snappy-1.1.7, zfp-0.5.5, zlib-1.2.13, zlibng-n/a, zopfli-1.0.3, zstd-1.5.2

**Comment by Czaki** [comment] 2023-07-07 20:19
Did I correctly understand that you install imagecodecs (napari) using `conda install`?

**Comment by T3chbug** [comment] 2023-07-07 20:28
for these tests I created a new conda env with python=3.9 and installed tifffile via conda (imagecodecs is installed alongside it, so I did not explicitly install it)

**Comment by Czaki** [comment] 2023-07-07 20:38
Could you try with a new environment and install tifffile and imagecodecs using pip? If It will work from `pip`, then we need to move this. issue to https://github.com/conda-forge/imagecodecs-feedstock as in such a situation it is a bug in the build process of imagecodecs for conda.

**Comment by T3chbug** [comment] 2023-07-07 21:57
Observation A)
- new env with py3.9 + pip install tifffile --> file import works, but imagecodecs is not installed
- +pip install imagecodecs -->file import still works and imagecodecs.version() outputs:
`imagecodecs-2023.7.4, cython-0.29.36, numpy-1.25.0, numpy_abi-0x1000009.13, imcd-2022.12.22, bcdec-026acf9, bitshuffle-0.4.0, brotli-1.0.9, brunsli-0.1, c-blosc-1.21.4, c-blosc2-2.10.0, charls-2.4.2, giflib-5.2.1, heif-n/a, imcd-2022.12.22, jetraw-n/a, jpegsof3-2023.1.23, jxrlib-1.1, lcms2-2.15.0, lerc-4.0.0, libaec-1.0.x, libavif-0.11.1, libbzip2-1.0.8, libdeflate-1.18, libjpeg_turbo-3.0.0/8.0, libjxl-0.8.2, liblj92-2023.1.23, liblzf-1.5, liblzma-5.4.3, libpng-1.6.39, libpng_apng-1.6.39, libspng-0.7.4, libtiff-4.5.1, libwebp-1.3.1, lz4-1.9.4, lzfse-1.0, lzham-10.8.1, mozjpeg-4.1.1/8.0, openjpeg-2.5.0, pg_lzcompress-13.2, qoi-36190eb, rgbe-2022.12.22, ricecomp-2023.7.4, snappy-1.1.x, zfp-1.0.0, zlib-1.2.13, zlib_ng-2.1.3, zopfli-1.0.x, zstd-1.5.5`

**Comment by Czaki** [comment] 2023-07-07 22:01
Could you open the proper issue in the pointed repository with the synthesis of information from this issue, or should I do this?

**Comment by jni** [comment] 2023-07-07 22:03
@T3chbug are you using conda from anaconda (defaults channel) or conda forge? I just created a new environment with conda-forge with:

```
mamba create -c conda-forge -n ic python=3.9 imagecodecs tifffile
```

and this pulled down imagecodecs 2023.1.23 and tifffile 2023.7.4. So it might be an *Anaconda* build issue? (Update: looking at your packages paths it does look like the full Anaconda distribution — I suggest using conda-forge.)

**Comment by jni** [comment] 2023-07-07 22:10
... And even if I download the conda-forge version of that imagecodecs version, it still works:

```
$ python -c "import tifffile; print(tifffile.imread('label_napari.tif').shape)"
(200, 3000, 3000)
```

<details>

<summary>

imagecodecs 2021.8.26 conda-forge py3.9 details

</summary>

```
$ python -c "import imagecodecs; print(imagecodecs.version())"
imagecodecs-2021.8.26, cython-0.29.24, numpy-1.25.0, numpy_abi-0x1000009.13, imcd-2021.8.26, avif-n/a, bitshuffle-0.3.5, blosc2-n/a, brotli-1.0.9, brunsli-0.1, c-blosc-1.21.0, cfitsio-4.0, charls-2.2.0, giflib-5.2.1, imcd-2021.8.26, jpeg12-n/a, jpegsof3-2020.12.22, jpegxl-n/a, jxrlib-1.1, lerc-3.0.0, libaec-1.0.5, libbzip2-1.0.8, libdeflate-1.8, libjpeg-9.4, liblj92-2014, liblzf-1.5, liblzma-5.2.5, libpng-1.6.37, libtiff-4.3.0, libwebp-1.3.1, lz4-1.9.3, openjpeg-2.5.0, pg_lzcompress-13.2, snappy-1.1.7, zfp-0.5.5, zlib-1.2.13, zlibng-n/a, zopfli-1.0.3, zstd-1.5.0

$ conda list | grep imagecodecs
imagecodecs               2021.8.26        py39hcb02aed_2    conda-forge
```

<details>

Having said that it could be a windows-specific compilation issue (I'm on mac). But nevertheless I would try conda-forge before creating an issue on the feedstock. I don't know the way to report bugs to Anaconda.

**Comment by jni** [comment] 2023-07-07 22:12
I will close this issue since it's not a napari issue, but it's ok to keep the conversation going here until your problem is resolved @T3chbug. But it looks like you have at least *one* workaround which is nice. 😊

**Closed as completed by jni** 2023-07-07 22:12 UTC
Labels: bug

**Comment by Czaki** [comment] 2023-07-07 22:19
Ah. Lovely anacond have own copy of package but not updating it https://anaconda.org/anaconda/imagecodecs

But napari is not present on the main channels so it is not possible to install it without conda-forge?

@jni this imagecodecs dependency is compiled one. So having it working on one system (I expect macOS in your case) it do not need to work on another OS.

**Comment by T3chbug** [comment] 2023-07-07 23:37
> ... And even if I download the conda-forge version of that imagecodecs version, it still works:
> 
> ```
> $ python -c "import tifffile; print(tifffile.imread('label_napari.tif').shape)"
> (200, 3000, 3000)
> ```
> 
> imagecodecs 2021.8.26 conda-forge py3.9 details
> 
> Having said that it could be a windows-specific compilation issue (I'm on mac). But nevertheless I would try conda-forge before creating an issue on the feedstock. I don't know the way to report bugs to Anaconda.

I just tried a conda forge installation 
-   tifffile                    conda-forge/noarch::tifffile-2021.4.8-pyhd8ed1ab_0
-   imagecodecs        pkgs/main/win-64::imagecodecs-2021.8.26-py39h319e4f4_2

... and it does NOT work, still the same LIBDEFLATE_BAD_DATA error. But it seems that it does not fetch imagecodecs from condaforge although I used `conda install -c conda-forge tifffile imagecodecs` as installation command, so I am not so sure of what that actually means something.

**Comment by jni** [comment] 2023-07-08 01:07
Yeah conda is funny with channels. `-c conda-forge` means "use conda-forge also", not "use only conda-forge". Then it uses complex priority rules to figure out which source to use. I think you can do `--channel-priority=strict` as well to try to force conda-forge? I can't remember exactly. Just boarding flight so I can't check, but google something like "how to get conda to use only conda-forge" or "use only one channel" or similar. It would be very good to know whether the conda-forge package on windows is broken in this way or not.

**Comment by Czaki** [comment] 2023-07-08 08:40
Maybe we should bump requirements for conda package above this version?

**Comment by T3chbug** [comment] 2023-07-08 10:18
using -c conda-forge --strict-channel-priority
imagecodecs        conda-forge/win-64::imagecodecs-2023.1.23-py39hd475b99_2
tifffile                    conda-forge/noarch::tifffile-2023.7.4-pyhd8ed1ab_0
--> it works, 

=>so most probably the issue is in the package shipped by anaconda, since installations using pip and conda-forge work fine
