### ISSUE TITLE
Hope it can be visualized in jupyter interface

### ISSUE THREAD

**Issue by Breeze-Zero** [napari/napari#4349] opened 2022-04-02 15:14 UTC
Thank you for your work on GUI visualization, but in most applications we need to run programs on Linux server (command line interface), such as neural network training, and the multidimensional results of the model output we want to see on jupyter, not copy back to local GUI.

**Comment by jni** [comment] 2022-04-04 12:45
Hi @834799106! This is a longstanding issue and duplicate of napari/napari#240. I will close it and further discussion can happen there.

napari integrated into jupyter will require a lot of re-engineering that will probably not happen for at least 12 months, and maybe much longer. In the meantime, many people have been able to work around this using jupyter desktop:

https://github.com/jupyterhub/jupyter-remote-desktop-proxy

In that workflow, a virtual desktop runs on the remote server and jupyter sends GUI windows to that desktop. Could you follow the instructions on jupyter remote desktop and see if they work for you? If they do and you would like to contribute that information to our documentation, we would absolutely love to add this! See napari/docs#29.

Finally, napari/napari#886 might have links to relevant information, even though it is quite old.

Even though this issue is closed, feel free to continue commenting and asking for help here or in one of the linked issues, as appropriate.

**Closed as completed by jni** 2022-04-04 12:45 UTC
Labels: feature
