### ISSUE TITLE
Information form status bar comes from top layer instead of active layer

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1842] opened 2020-11-05 23:15 UTC
## 🐛 Bug

I expect that information presented on the status bar should comes from active layer. Currently, its goes from the top one. 

## To Reproduce

1. create two diferent layers
2. set active to second from top
3. move the above image and check values presented on the status bar

## Expected behavior

Present information about brightness (values) from active layer or all layers.

**Comment by jni** [comment] 2020-11-05 23:24
@Czaki thanks for reporting! This is a duplicate of #1836, so I'll close this one and let's keep the discussion there.

**Comment by jni** [comment] 2020-11-05 23:25
(We will definitely fix this before 0.4.1 is released!)

**Closed as completed by jni** 2020-11-05 23:24 UTC
Labels: bug
