### ISSUE TITLE
Saving layers dialog broken with ipython + MacOS

### ISSUE THREAD

**Issue by maweigert** [napari/napari#3080] opened 2021-07-23 12:36 UTC
## 🐛 Bug

When using napari from within ipython and trying to save a layer e.g. with "Save Selected Layer(s)" the corresponding FileDialog pops up and immediately closes without any user intervention. This seems to happen with all `QFileDialog` dialogs (but not `QMessageBox`).   

## To Reproduce

1. Open an empty image **within ipython**
 
```python
import numpy as np
import napari

w = napari.Viewer()
w.add_image(np.zeros((10,10)))
```

2. Try to save the image with `⌘ + S`

## Expected behavior

all the things saved 

## Environment

```
napari: 0.4.10
Platform: macOS-10.15.7-x86_64-i386-64bit
System: MacOS 10.15.7
Python: 3.8.8 (default, Feb 24 2021, 13:46:16) [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.19.5
SciPy: 1.7.0
Dask: 2021.04.1
VisPy: 0.6.6

OpenGL:
- GL version: 2.1 ATI-3.10.18
- MAX_TEXTURE_
```

**Comment by psobolewskiPhD** [comment] 2023-05-07 15:05
I can still reproduce this in current main (commit: 9da6d289735e4c7d3abbcd111f03f5c61891d7ff)

Running the snippet from ipython (8.13.1) and trying to save via keybind or file menu gives:
```
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/menus/file_menu.py", line 73, in <lambda>
    'slot': lambda: window._qt_viewer._save_layers_dialog(
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/qt_viewer.py", line 556, in _save_layers_dialog
    raise OSError(trans._("Nothing to save"))
OSError: Nothing to save
```

If i launch from terminal using `napari`, then the dialog works fine.

Probably related to https://github.com/napari/napari/issues/2571

Edit: I wonder why the fix linked here:
https://github.com/napari/napari/issues/2571#issuecomment-1148017902
(#3130) doesn't work/stopped working...

**Comment by dalthviz** [comment] 2023-05-11 18:33
Hi, I gave this a check and I was able to get the dialog and save to a `.tif` image. However, if I first unselect the layer I get the `OSError: Nothing to save` error above. Also, if I add as file extension to the filename when saving something like `.png` I get a different traceback but a file is generated:

* Preview of described behavior launching from IPython:

![save_image](https://github.com/napari/napari/assets/16781833/30f1ea47-1a3b-42de-8e04-af8c231550aa)

* Traceback when adding `.png` when saving the file:

<details>

```python-traceback
Traceback (most recent call last):
  File "/Users/dalthviz/opt/anaconda3/envs/napari-dev/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 1278, in _save
    rawmode, mode = _OUTMODES[mode]
KeyError: 'F'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dalthviz/Desktop/Napari/napari/napari/_qt/menus/file_menu.py", line 73, in <lambda>
    'slot': lambda: window._qt_viewer._save_layers_dialog(
  File "/Users/dalthviz/Desktop/Napari/napari/napari/_qt/qt_viewer.py", line 595, in _save_layers_dialog
    saved = self.viewer.layers.save(
  File "/Users/dalthviz/Desktop/Napari/napari/napari/components/layerlist.py", line 476, in save
    return save_layers(path, layers, plugin=plugin, _writer=_writer)
  File "/Users/dalthviz/Desktop/Napari/napari/napari/plugins/io.py", line 229, in save_layers
    _written, writer_name = _write_single_layer_with_plugins(
  File "/Users/dalthviz/Desktop/Napari/napari/napari/plugins/io.py", line 442, in _write_single_layer_with_plugins
    written_paths, writer_name = _npe2.write_layers(
  File "/Users/dalthviz/Desktop/Napari/napari/napari/plugins/_npe2.py", line 117, in write_layers
    res = writer.exec(args=args)
  File "/Users/dalthviz/opt/anaconda3/envs/napari-dev/lib/python3.9/site-packages/npe2/manifest/utils.py", line 65, in exec
    return self.get_callable(_registry)(*args, **kwargs)
  File "/Users/dalthviz/Desktop/Napari/napari/napari_builtins/io/_write.py", line 124, in napari_write_image
    imsave(path, data)
  File "/Users/dalthviz/Desktop/Napari/napari/napari/utils/io.py", line 28, in imsave
    imsave_png(filename, data)
  File "/Users/dalthviz/Desktop/Napari/napari/napari/utils/io.py", line 58, in imsave_png
    iio.imwrite(
  File "/Users/dalthviz/opt/anaconda3/envs/napari-dev/lib/python3.9/site-packages/imageio/v3.py", line 147, in imwrite
    encoded = img_file.write(image, **kwargs)
  File "/Users/dalthviz/opt/anaconda3/envs/napari-dev/lib/python3.9/site-packages/imageio/plugins/pillow.py", line 335, in write
    primary_image.save(self._request.get_file(), **save_args)
  File "/Users/dalthviz/opt/anaconda3/envs/napari-dev/lib/python3.9/site-packages/PIL/Image.py", line 2353, in save
    save_handler(self, fp, filename)
  File "/Users/dalthviz/opt/anaconda3/envs/napari-dev/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 1280, in _save
    raise OSError(f"cannot write mode {mode} as PNG") from e
OSError: cannot write mode F as PNG
```

</details>

Checking a launch from the terminal directly via the `napari` command I was able to get the same errors (triggered when no having a layer selected and using the `.png` extension). However, the errors were also shown with an GUI error notification (which seems like doesn't happen when launching from IPython?):

<img width="696" alt="image" src="https://github.com/napari/napari/assets/16781833/d1ab1f9d-08dd-43db-a0e8-8f274811c5e5">

Also, I think the dialog fix done is working since launching from IPython vs terminal show different dialogs. The dialog shown when saving from a napari instance launched from the terminal is different:

* Save dialog when napari is launched directly from the terminal:

<img width="840" alt="image" src="https://github.com/napari/napari/assets/16781833/291bdc7f-5cca-4b91-ac43-79cb8a0c23f9">

**Comment by psobolewskiPhD** [comment] 2023-05-28 15:47
Was playing with this again. 
I think best solution for this would be if `Save Selected layer` was just greyed out (disabled) when no layer is selected. I mean it requires a selected layer to work.
BTW: shift-command-S (Save All) works with nothing selected...so another option would be to use that when nothing is selected?

**Comment by dalthviz** [comment] 2023-06-05 08:25
> Edit: Perhaps it's best to close this and make new issue for the no-selection behavior and the filename?

That sounds good to me :+1:

**Comment by psobolewskiPhD** [comment] 2023-07-18 21:32
Just a note that I reverted https://github.com/napari/napari/pull/3130 and the show-and-disappear issue with the native dialog is still a thing.

**Comment by rubencart** [comment] 2023-09-18 21:43
Any solution for this?

**Comment by psobolewskiPhD** [comment] 2023-09-19 00:52
@rubencart 
I'm not able to reproduce with the snippet from OP on napari 0.4.18:
```
import numpy as np
import napari

w = napari.Viewer()
w.add_image(np.zeros((10,10)))
```
Are you still seeing this? can post `napari --info`?

**Comment by Czaki** [comment] 2023-09-19 11:22
> Any solution for this?

check if you are using latest qtpy version.

**Comment by dalthviz** [comment] 2023-09-19 17:34
Maybe the error @rubencart is referring to is the one related with using the save dialog, setting as file extension like `.png` and then getting a `OSError: cannot write mode F as PNG `)? Also, should a different issue be opened for that, right?

**Comment by psobolewskiPhD** [comment] 2024-02-19 01:14
>  I think best solution for this would be if `Save Selected layer` was just greyed out (disabled) when no layer is selected. 

Just retested, post https://github.com/napari/napari/pull/4865 and this is the case.

I do still get the `OSError: cannot write mode F as PNG`  traceback for trying to write a .png.
I'm going to close this and open a new issue related to that.

**Closed as completed** 2024-02-19 01:15 UTC
Labels: bug, UI/UX
