### ISSUE TITLE
pip install 'napari[all]' doesn't work on Windows 10 in some cases

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#3335] opened 2021-09-03 19:24 UTC
## 🐛 Bug

@alisterburt and I were just running a workshop and some students on Windows 10 ran into some issues with the installation. They received an error when using `pip install 'napari[all]'`, but `pip install napari[all]` (i.e., no quotes) worked I believe they were using mini forge or Anaconda, but I forgot to clarify. We may want to consider updating the readme instructions to have a special case for windows vs. mac os + zsh

## Expected behavior

The README installation instructions should work on Windows 10

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by goanpeca** [comment] 2021-09-08 21:15
>We may want to consider updating the readme instructions to have a special case for windows vs. mac os + zsh

Agreed! Would you like to open a PR @kevinyamauchi ? :)

**Comment by tlambert03** [comment] 2021-09-16 22:21
this is actually a duplicate of https://github.com/napari/napari/issues/2699
our instructions at `napari.org` actually specify double quotes `pip install "napari[all]"`, which I believe _does_ work on windows.  so we should switch our readme to match the napari.org instructions.  easy one

**Comment by goanpeca** [comment] 2021-09-17 15:02
So can we close this? or we need to update single to double quotes somehwere?

**Comment by tlambert03** [comment] 2021-09-17 16:45
> or we need to update single to double quotes somehwere?

the readme, as per @kevinyamauchi's original expectation: 

> The README installation instructions should work on Windows 10

**Comment by goanpeca** [comment] 2021-09-17 17:39
Ahhh ok

**Closed as completed** 2021-09-20 16:04 UTC
Labels: bug, contribute:good first issue, priority:high, severity:high
