### ISSUE TITLE
Toggling `viewer.dims.ndisplay` with a 3D image and multiscale image throws error

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#2488] opened 2021-03-30 01:06 UTC
## 🐛 Bug

Changing the number of displayed dimensions with a 3D layer and a multiscale layer from 3D back to 2D throws an error - the images are still rendered seemingly correctly. First identified by @uschmidt83

## To Reproduce

```python
import napari
from skimage import data
from scipy.ndimage import zoom
import numpy as np

with napari.gui_qt():
    viewer = napari.Viewer()

    img       = data.camera()
    img_multi = [zoom(img,(1/s,1/s)) for s in (1,2,4)]
    img3D     = np.tile(img[np.newaxis],(8,1,1))

    viewer.add_image(img_multi)
    viewer.add_image(img3D)

    viewer.dims.ndisplay = 3
    viewer.dims.ndisplay = 2
```

Traceback:
```python
TypeError                                 Traceback (most recent call last)
~/CZI/napari/napari/_qt/qt_event_loop.py in gui_qt(startup_logo=False, gui_exceptions=False, force=False)

~/CZI/napari/napari/utils/events/evented_model.py in __setattr__(self=Dims(ndim=3, ndisplay=2, last_used=0, range=((0....0), order=(0, 1, 2), axis_labels=('0', '1', '2')), name='ndisplay', value=2)

~/CZI/napari/napari/utils/events/event.py in __call__(self=<napari.utils.events.event.EventEmitter object>, *args=(), **kwargs={'value': 2})

~/CZI/napari/napari/utils/events/event.py in _invoke_callback(self=<napari.utils.events.event.EventEmitter object>, cb=<bound method ViewerModel._update_layers of View...use_drag_gen={}, _mouse_wheel_gen={}, keymap={})>, event=<Event blocked=False handled=False native=None source=None sources=[] type=ndisplay>)

~/CZI/napari/napari/utils/events/event.py in _invoke_callback(self=<napari.utils.events.event.EventEmitter object>, cb=<bound method ViewerModel._update_layers of View...use_drag_gen={}, _mouse_wheel_gen={}, keymap={})>, event=<Event blocked=False handled=False native=None source=None sources=[] type=ndisplay>)

~/CZI/napari/napari/components/viewer_model.py in _update_layers(self=Viewer(axes=Axes(visible=False, labels=True, col...ouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), event=<Event blocked=False handled=False native=None source=None sources=[] type=ndisplay>, layers=[<Image layer 'img_multi' at 0x7ff6b0239460>, <Image layer 'img3D' at 0x7ff6a333d220>])

~/CZI/napari/napari/layers/base/base.py in _slice_dims(self=<Image layer 'img_multi'>, point=[0.0, 0.0, 0.0], ndisplay=2, order=[0, 1])

~/CZI/napari/napari/layers/base/base.py in _update_dims(self=<Image layer 'img_multi'>, event=None)

~/CZI/napari/napari/layers/base/base.py in refresh(self=<Image layer 'img_multi'>, event=None)

~/CZI/napari/napari/layers/base/base.py in set_view_slice(self=<Image layer 'img_multi'>)

~/CZI/napari/napari/layers/image/image.py in _set_view_slice(self=<Image layer 'img_multi'>)

TypeError: slice indices must be integers or None or have an __index__ method
```
## Expected behavior

Dimensions change with no error thrown

## Environment

napari: 0.4.7.dev75+g66fe700f
Platform: Linux-5.4.0-70-generic-x86_64-with-glibc2.10
System: Ubuntu 18.04.5 LTS
Python: 3.8.8 (default, Feb 24 2021, 21:46:12) [GCC 7.3.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.2
SciPy: 1.6.2
Dask: 2021.03.1
VisPy: 0.6.6

## Additional context

I can't seem to get the error to fire when I run the code from terminal and toggle dimensions - only when I run through VSCode...

**Comment by sofroniewn** [comment] 2021-03-31 04:55
Thanks for filing!

**Comment by uschmidt83** [comment] 2021-03-31 06:47
> I can't seem to get the error to fire when I run the code from terminal and toggle dimensions - only when I run through VSCode...

FYI, I also get the error when running as script in the terminal via python/ipython.

**Comment by andy-sweet** [comment] 2022-03-25 20:46
I can't reproduce this on `main` (commit 0ff842d11c6e67c77373ffda011125ee9d7bc98b) on macOS from a terminal or from VSCode.

I do get the following warning message when toggling `ndisplay`, but everything seems to work as expected.

```
UserWarning: Multiscale rendering is only supported in 2D. In 3D, only the lowest resolution scale is displayed!
```

Here's my complete environment.

```
napari: 0.4.14.dev135+gc8a62b43.d20220314
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 11.6.2
Python: 3.9.6 (default, Jul 30 2021, 09:31:09) [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.1
Dask: 2021.07.2
VisPy: 0.9.6

OpenGL:
- GL version: 2.1 INTEL-16.5.7
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.4
- napari-layer-details-display: 0.1.2
- napari-tools-menu: 0.1.10
- scikit-image: 0.4.14.dev135+gc8a62b43.d20220314
```

If either @DragaDoncila or @uschmidt83 could try to reproduce this on `main` and also find that it is not reproducible, maybe we can close this issue?

**Comment by andy-sweet** [comment] 2022-03-25 20:55
And I could reproduce this issue at tags/v0.4.7 on the same machine (and the same conda environment), so I suspect this may be fixed.

**Comment by tlambert03** [comment] 2022-03-25 21:06
with git bisect, https://github.com/napari/napari/pull/3460 was the PR that removed this error .  (and then note that another error was revealed that later was resolved in #3519, showing the error that @andy-sweet saw above).  

so I think this can be closed?

**Comment by andy-sweet** [comment] 2022-03-25 23:21
@tlambert03 : that's convinces me. I prefer letting core-devs close issues, so why don't you do the honors here?

**Comment by tlambert03** [comment] 2022-03-25 23:27
Would be nice to get confirmation from either @DragaDoncila or @uschmidt83 that updating napari solves their issue

**Comment by uschmidt83** [comment] 2022-03-26 14:50
Seems to be fixed for me.

```
napari: 0.4.13
Platform: macOS-11.6.4-arm64-arm-64bit
System: MacOS 11.6.4
Python: 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:35:11) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.07.0
VisPy: 0.9.4

OpenGL:
- GL version: 2.1 Metal - 71.7.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0
- screen 2: resolution 3008x1269, scale 2.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.13
- svg: 0.1.5
```

**Comment by tlambert03** [comment] 2022-03-26 14:51
thanks

**Closed as completed by tlambert03** 2022-03-26 14:51 UTC
Labels: bug
