### ISSUE TITLE
Investigate and fix performance issues when drawing multiple layers

### ISSUE THREAD

**Issue by jni** [napari/napari#1885] opened 2020-11-17 00:12 UTC
@Czaki showed some profiling results [on Zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/napari.20slow.20w.20lots.20of.20layers/near/216894525) when adding "many" napari layers, specifically 100 images. It seems a lot of time is spent on computing the world extent:

![Zrzut-ekranu-z-2020-11-16-17-16-22](https://user-images.githubusercontent.com/492549/99323134-a4979d00-28c5-11eb-8067-1353177993cc.png)

![Zrzut-ekranu-z-2020-11-16-17-22-41](https://user-images.githubusercontent.com/492549/99323144-acefd800-28c5-11eb-87ec-29ba8586b4b2.png)

so that's a good low-hanging fruit.

We do have benchmarks, so adding a benchmark for adding "many" small images would be useful, too.

**Comment by jni** [comment] 2020-11-17 00:13
Many thanks to @Czaki for the investigation! 🙏

**Comment by Czaki** [comment] 2020-11-17 00:50
A short tutorial for reproducing without using PyCharm Professional.

May be need to patch `running_as_bundled_app`

```python
def running_as_bundled_app() -> bool:
    """Infer whether we are running as a briefcase bundle"""
    # https://github.com/beeware/briefcase/issues/412
    # https://github.com/beeware/briefcase/pull/425
    try:
        app_module = sys.modules['__main__'].__package__
        metadata = importlib_metadata.metadata(app_module)
        return 'Briefcase-Version' in metadata
    except Exception:
        return False
```

Profiled code in `sample_code.py`

```python
import napari
import napari.plugins.io
import sys

with napari.gui_qt():
    viewer = napari.Viewer()
    for iteration in range(0,100):
        print(iteration)
        viewer.add_image(
            napari.plugins.io.read_data_with_plugins("image.png")[0],
        )
    viewer.close()
    sys.exit()
```
Install graphviz program
Install [`gpof2dot`](https://github.com/jrfonseca/gprof2dot) package in the python environment . Then call
```bash
$ python -m cProfile -o napari.pstat sample_code.py
...
$ python -m gprof2dot -f pstats napari.pstat | dot -Tpng -o output.png
```

Here sample output (with removed nodes which total time bellow 6% because of github limitations)

![output](https://user-images.githubusercontent.com/3826210/99325587-f9f88d80-2876-11eb-8638-24d1200e5ae5.png)

**Comment by sofroniewn** [comment] 2020-11-28 18:09
Just noting that this has been dramatically improved with the merge of #1945, but we still have #1949 and #1950 in progress that could cause further improvements.

**Comment by andy-sweet** [comment] 2021-11-15 16:55
@sofroniewn: all the PRs originally associated with this issue have been merged or closed (in favor of other PRs).

I'm sure there are other layer performance improvements to come, but I think this issue has served its purpose, so I think we should close it - what do you think?

**Comment by sofroniewn** [comment] 2021-11-15 19:28
Agreed - i will close, thanks for flag!!

**Closed as completed by sofroniewn** 2021-11-15 19:28 UTC
Labels: performance
