### ISSUE TITLE
Bug: Keyboard shortcut for scrolling through dims is buggy (fix `last_used` setter)

### ISSUE THREAD

**Issue by tathey1** [napari/napari#3273] opened 2021-08-29 20:14 UTC
## 🚀 Feature
It would be great if there was a keyboard shortcut to scroll through slices of 3d images rather than having to use the mouse to drag the scroll bar or click the slide arrow.

## Motivation

Occasionally I used napari to place points along structures in 3d space and this process would be much faster if I didn't need to move my mouse between dropping points and scrolling to the next slice.

## Pitch

The ability to scroll through 3d images with the keyboard would be less tedious than using the mouse on the scroll bar. I don't think it matters which keys are used, arrow keys, WASD, +/-, anything else.

## Alternatives

I am certain that a keyboard shortcut would make my job of annotating 3d images with points quicker.

## Additional context

Additionally, a popup indicating which key scrolls through slices (like the feature [here](https://github.com/napari/napari/issues/2135)), would be even better.

**Comment by sofroniewn** [comment] 2021-08-30 00:13
For sure, this request makes a lot of sense. Thanks for making it!

I believe the left and right arrow keys work if you have clicked into the dimension slider to give the slider focus. If you're adding points in the canvas then as soon as you click there focus will go back to the canvas and so you'll lose the ability to have the left and right arrow keys work. One option would be to make the left and right arrow keys always move the dims sliders (I believe that was the case in an older version of napari), another would be to have the canvas not steal focus. Curious if @goanpeca or others have any ideas for implementation here or best practices

**Comment by tlambert03** [comment] 2021-08-30 13:05
> I believe that was the case in an older version of napari

The keybindings are actually [still there](https://github.com/napari/napari/blob/c6df8cfb4155d6314796ed4e7c5334646ed75665/napari/components/_viewer_key_bindings.py#L80-L82), and the function is still getting called regardless of dims focus.  so this is a bug.

When a layer is loaded, `self.last_used` is getting touched by too many things (including  `set_range`, `set_current_step`, `set_axis_label`, `_focus_up`, `_focus_down`, etc...).  So by the time someone uses the left/right arrow keys, "last used" has been changed to an already-visible dimension (e.g. "2" instead of "0" for a 3d layer).

We should refactor how `last-used` is set

**Comment by sofroniewn** [comment] 2021-08-30 18:34
Good digging @tlambert03!  

> We should refactor how last-used is set

Agreed! Looks to me like this was already broken in `0.4.10` in which case we can wait to fix, but we should do soon

**Comment by NBCS1** [comment] 2021-10-29 23:45
> ## Alternatives
> I am certain that a keyboard shortcut would make my job of annotating 3d images with points quicker.

I had the same issue, I needed to do rectangular selections on x frames and I had to go back to the slider all the time.
It's not especially pretty, kind of temporary but it's working like a charm. I coded two key events.
I was going to add some handling for when you reach out of the range of the image but suprisingly, it does not throw any error when you reach 0 and keep pressing or the max frames.
Hope it can help, at least as a temporary fix.
```
import napari
from skimage.io import imread
image=imread("example.tif")
viewer=napari.Viewer()
viewer.add_image(image)
@viewer.bind_key('d')
def next_step(viewer):
    current_step=viewer.dims.current_step[0]#current_step[0] refers to the frame number
    viewer.dims.set_current_step(0,current_step+1)#0 is the axis (frame) and frame to set
@viewer.bind_key('a')#Edit: it's actually not working that great with shapes layers. I changed "a" to "q" and it worked.
def previous_step(viewer):
    current_step=viewer.dims.current_step[0]
    viewer.dims.set_current_step(0,current_step-1)

```

**Comment by psobolewskiPhD** [comment] 2023-06-23 21:18
Having a hard time reproducing this on 0.4.18rc1
Using blobs (3D) and cells (3D) samples, the left-right arrows always seem to work...

....unless I roll the dimensions, then they stop working until i click in the slider--clicking one of the arrows is not sufficient.

**Comment by dalthviz** [comment] 2023-06-30 15:52
Could this be related with #2388 ?

**Comment by psobolewskiPhD** [comment] 2023-06-30 20:06
@dalthviz It might be but #6024 doesn't fix it.
What's not intuitive to me is that after rolling dims or fresh open Sample 3D blobs: 
1. clicking the end-arrows `>|` doesn't give focus to the slider so that then the keyboard arrows work.
2. Clicking the actual pill on the slider doesn't work either for me.
3. Alt-up, alt-down also don't switch to the slider.
4. I have to click the canvas—why the canvas?!?

**Comment by dalthviz** [comment] 2023-07-03 16:32
Thanks for the check @psobolewskiPhD ! You are clicking the roll dims button, right? I think that causes the focus change to the viewer buttons so pressing the left/right arrows changes the current button selected (a doted rectangle can be seen):

![focus](https://github.com/napari/napari/assets/16781833/ea4b7cc1-6c3d-429e-85e6-3f476b454393)

Regarding not being able to set the focus again to the slider by clicking different elements inside it I think that could be caused due to:

https://github.com/napari/napari/blob/de98721d2cc2a3141e3be23765c7859f078eaace/napari/_qt/widgets/qt_dims_slider.py#L150

and some missing logic to change the focus to the slider at https://github.com/napari/napari/blob/de98721d2cc2a3141e3be23765c7859f078eaace/napari/_qt/widgets/qt_dims_slider.py#L160-L161

Maybe adding a `setFocus` call at the end of

https://github.com/napari/napari/blob/de98721d2cc2a3141e3be23765c7859f078eaace/napari/_qt/widgets/qt_dims.py#L77-L84

could help 🤔

**Comment by psobolewskiPhD** [comment] 2023-07-13 00:04
@dalthviz Of course you're right, I was using the viewer button! But, that's probably not an abnormal user behavior.

**Comment by dalthviz** [comment] 2023-07-13 15:20
Thanks for the info @psobolewskiPhD ! Checking the solution I proposed above I think it would only work for the roll dims button (since it changes the `last_used` dim). However, pressing any of the viewer buttons should not cause a focus change, right? If that's the case, maybe changing the viewer buttons focus policy + setting the focus to the slider when it is pressed could help but not totally sure 😅

**Comment by dalthviz** [comment] 2023-07-18 18:10
So, after checking this for a while, if the idea is to prevent the viewer buttons to gain focus and instead be sure that pressing them puts the focus on the slider, I think one option could be to set focus to the `QtDims` instance by detecting when focus is going to any of the `QtViewerPushButton` instances via an event filter. Also, setting the focus when the `sliderPressed` signal is emitted for `QtDimSliderWidget` instances or when the slider value changes (to cover the case for the play button or the back/forward buttons being pressed) seems like helps.

Here a branch with the code changes described above to check the behavior locally: https://github.com/dalthviz/napari/commit/cde9b6e814087017247525e08e7e1b6c8895e1f9

**Comment by psobolewskiPhD** [comment] 2023-07-29 20:07
I thought about this some more. I think there are people who might want to navigate the UI with just keyboard, so then being able to change focus from viewer button to viewer button makes sense. So maybe I wouldn't mess with that. 
Let's just make sure the focus goes to the sliders and stays there when:
- click on the pill in the slider
- click on either arrow at the end.

**Comment by dalthviz** [comment] 2023-07-31 16:24
Thank you for the feedback @psobolewskiPhD ! If the idea is just to make the slider/dims widget to get focus when the pill or arrows are clicked then something like the following should work:

```python

        def slider_focused_listener():
            self.dims.last_used = self.axis
            self.qt_dims.setFocus()

        # linking focus listener to the last used and set dims widget focus.
        # Setting the focus to the dims widget enables the keyboard shortcuts:
        slider.sliderPressed.connect(slider_focused_listener)
        slider.actionTriggered.connect(slider_focused_listener)
        self.slider = slider 
```

At https://github.com/napari/napari/blob/de98721d2cc2a3141e3be23765c7859f078eaace/napari/_qt/widgets/qt_dims_slider.py#L160-L166

With that I can see locally the following behavior:

![slider_focus](https://github.com/napari/napari/assets/16781833/1a271381-84b8-414b-b93d-c77f8d05a4b8)

If that makes sense let me know and I can open a PR with the change :+1:

**Comment by psobolewskiPhD** [comment] 2024-03-09 03:09
I can't reproduce this anymore on main 27851ee92913e02b16d05b0aba19b126fa1e29e3 ...

Clicking on roll-dims or loading layers (4D) i can seemingly always use arrows L, R and alt up down for the sliders.
even if I interact with layer controls, it all still JustWorks.


Not sure if that's a PR merge or Qt change?

```
napari: 0.5.0a2.dev587+gc95f4b68a.d20240305
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:38:07) [Clang 16.0.6 ]
Qt: 6.6.1
PyQt6: 
NumPy: 1.26.3
SciPy: 1.12.0
Dask: 2024.1.1
VisPy: 0.14.1
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.4
npe2: 0.7.4

OpenGL:
- GL version: 2.1 Metal - 83.1
- MAX_TEXTURE_SIZE: 16384
- GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Optional:
- numba: 0.59.0
- triangle not installed

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml

```

**Comment by dalthviz** [comment] 2024-03-11 17:17
Hi there, I think I can confirm that on macOS this is not a problem with latest main (84b5b98) and seems like there the buttons don't get focused anymore. However, seems like the problem is still there at least on Windows 🤔. Checking on Windows, I can see that when the roll dims button is clicked, the button gets the focus (a dotted line outline) and arrow keys make the dotted outline go to other buttons still:

![sliders](https://github.com/napari/napari/assets/16781833/1fcb2e9a-0521-4031-a848-1441e63516c0)

Also, checked a little bit more the behavior trying to use keyboard navigation on Windows and seems like I'm able to make a slider regain focus partially by pressing tab + arrows a couple of times (although only to use the Right/Left arrows 🤔):

![sliders_keyboard](https://github.com/napari/napari/assets/16781833/9a04aa03-3fdd-4e15-9bdf-18246e967245)

**Comment by psobolewskiPhD** [comment] 2024-03-23 21:46
@dalthviz Hmm. On Windows:
1. When an image like Cells3D sample is opened, do the arrows work?
2. If viewer buttons are clicked, does clicking back to the canvas or the pill or slider arrows work for the focus?
3. If viewer buttons are clicked, is it enough to de-focus the buttons to make make the arrows work for the slider?
4. If you have Cells3D and make a points layer, can you add points with mouse and change slices with arrows?

I think if these 4 are "yes" then we can close this?

**Comment by dalthviz** [comment] 2024-03-25 18:24
Checked on Windows and I would say a yes for all the questions!:

![scroll_arrow_opt](https://github.com/napari/napari/assets/16781833/c59b7fa0-ff56-4c3f-a956-b8ea8bcd7c7c)

So seems like indeed this can be closed 🎉

**Comment by psobolewskiPhD** [comment] 2024-03-26 00:22
Awesome, that looks good.
So:
✅ Mac
✅ Windows
❓ Linux
Anyone have access to linux desktop? I can test via xpra, but not sure keyboard focus is maintained. I'll try though.

**Comment by dalthviz** [comment] 2024-03-27 15:58
Checked on a Linux virtual machine and seems like things are working in the same way 🎉 

![scroll_dims_linux](https://github.com/napari/napari/assets/16781833/5f561834-34df-4887-bcd8-a68fde0b21a5)

**Closed as completed** 2024-03-27 16:20 UTC
Labels: bug, priority:high, severity:medium, triage:probably solved
