### ISSUE TITLE
Function widget of plugin ignored when using magicgui

### ISSUE THREAD

**Issue by ViktorvdValk** [napari/napari#2209] opened 2021-02-04 15:04 UTC
## 🐛 Bug

`Plugin 'itk-elastix_napari' provided a non-callable type to `napari_experimental_provide_function`: <class 'magicgui.widgets._function_gui.FunctionGui'>. Function widget ignored.`

My plugin that was created with magicgui

```
@magicgui(call_button="register", transform = {"choices": ["rigid", "affine", "bspline"]})
def register(fixed: 'napari.types.ImageData', moving:'napari.types.ImageData', transform: str) -> 'napari.types.LayerDataTuple':
.... function calculations etc.
return some LayerDataTuple

@napari_hook_implementation
def napari_experimental_provide_function():
    return register
```

is ignore by napari, which says the 'FunctionGui' is not callable.
However the docs say the FunctionGui should be callable.

Did I do anything wrong or is the napari_experimental_provide_function() still under development?

**Comment by tlambert03** [comment] 2021-02-04 15:24
Hey @ViktorvdValk, sorry for the confusion (and it is currently confusing!)

That's a bad error message and should be fixed.  `FunctionGui` _is_ a callable, but we actually recently tightened down the type checking from `callable()` to `isinstance(obj, FunctionType)` (and while a magicgui object is callable, it is not, in and of itself, an actual function).

To help clarify the confusion:
- `napari_experimental_provide_function` is not intended for receiving things that are _already_ widgets.  It is a hookspec to which you would provide a pure function (and _napari_ may call `magicgui` on it to build a widget for you).
- In this case, if you're mostly trying to build a widget with magicgui that napari can use, use the `napari_experimental_provide_dock_widget` hookspec instead, and decorate with `@magic_factory`:
```python
from magicgui import magic_factory

@magic_factory(call_button="register", transform = {"choices": ["rigid", "affine", "bspline"]})
def register(fixed: 'napari.types.ImageData', moving:'napari.types.ImageData', transform: str) -> 'napari.types.LayerDataTuple':
    ...
    return some_LayerDataTuple

@napari_hook_implementation
def napari_experimental_provide_dock_widget():
    return register
```

again, apologies for the confusion, this is all very new.  the [docs have been updated](https://napari.org/docs/dev/plugins/hook_specifications.html#napari.plugins.hook_specifications.napari_experimental_provide_dock_widget) and things will gradually stabilize

**Comment by ViktorvdValk** [comment] 2021-02-05 10:57
Thanks a lot for the fast responds.
The plugin is currently loading a widget, so there's definitely progress.
Unfortunately calling the function in the widget now results in napari shutting down without any error or hint in either the napari GUI or the command line which remains frozen after this.

Loading the Napari GUI Qt from a jupyter notebook and then using the same function (this time using magicgui), does work though! This gives exactly the desired function output.

The problem seems to occur when a function from another package is called (in this case itk), see below.

```
import numpy as np
from napari_plugin_engine import napari_hook_implementation
from magicgui import magic_factory
from itk import itkElastixRegistrationMethodPython
import itk

@magic_factory(call_button="register", transform = {"choices": ["rigid", "affine", "bspline"]})
def register(fixed: 'napari.types.ImageData', moving: 'napari.types.ImageData', transform: str) -> 'napari.types.LayerDataTuple':
    parameter_object = itk.ParameterObject.New()
    return fixed, {'name':transform + ' Registration'}

@napari_hook_implementation
def napari_experimental_provide_dock_widget():
    return register
```
Uncommenting the line `parameter_object = itk.ParameterObject.New()` just returns the fixed image, so the import statements do not give any problems. And the itk-elastix library is included in the requirements.txt

What could be the problem here?

**Comment by tlambert03** [comment] 2021-02-05 11:03
trying to reproduce, but i don't seem to have installed itk properly to use the ElastixReg...
```
In [1]: from itk import itkElastixRegistrationMethodPython
---------------------------------------------------------------------------

ImportError: cannot import name 'itkElastixRegistrationMethodPython' from 'itk' (unknown location)
```

How should I install to reproduce?

**Comment by ViktorvdValk** [comment] 2021-02-05 11:04
pip install itk-elastix

**Comment by tlambert03** [comment] 2021-02-05 11:11
quick question: with this function, are you testing the "register" button without any images loaded by chance?

**Comment by ViktorvdValk** [comment] 2021-02-05 11:15
No, I load 2 images with the napari interface, select them in the widget and then click "register".
Also when I omit the itk call (`parameter_object = itk.ParameterObject.New()`), the function does work and returns the fixed image as expected.

**Comment by tlambert03** [comment] 2021-02-05 11:17
sounds good.  will try to see what that call might be doing.  As a sidenote though, you might want to add something like this as a safety:
```python
if fixed is None or moving is None:
    return
```
(since returning a tuple of (None, {}) is not valid, but may happen if one of the two images isn't loaded)

**Comment by tlambert03** [comment] 2021-02-05 11:22
I'm honestly not immediately sure.  It does actually run fine for me (returns the fixed image as expected even with that line included).  I can say that loading the parameter object takes a couple seconds on my computer... but then succeeds.  I have no familiarity with that library, so I'd need to look into it some more (it's a bit difficult to debug due to the star imports and shared library access in itk).  As for working in jupyter, that's a bit of a mystery to me as well (unless it's possible that you're running in a different environment there? that just happens to be setup differently?)

**Comment by ViktorvdValk** [comment] 2021-02-05 11:34
The environment is the same in both runs. 
Debugging itk is tricky indeed, but I suspect the problem lies within napari, considered the fact that the jupyter notebook version does work.
It's good to know that the plugin does work for you, I'll have a try with different environments maybe that helps clarify things.
Thanks a lot for the support.
And keep up the good work with Napari! I really like the ease of creating plugins with the pluggy fork!

**Comment by tlambert03** [comment] 2021-02-05 11:41
> but I suspect the problem lies within napari, considered the fact that the jupyter notebook version does work.

knowing nothing about what's happening inside of `itk.ParameterObject.New()`, the only thing I can think of here is perhaps some sort of lower level Qt conflict? or perhaps some sort of threading issue?

@thewtex ... can you possible shed some light here?  quick summary: calling `itk.ParameterObject.New()` inside of function called from within napari seems to be [crashing napari](https://github.com/napari/napari/issues/2209#issuecomment-773960384)... but it doesn't seem to happen in jupyter notebook (and @ViktorvdValk are you using the `%gui qt` magic in jupyter? or always starting the app with `napari.gui_qt`)

**Comment by ViktorvdValk** [comment] 2021-02-05 11:43
I use napari.gui_qt()

**Comment by tlambert03** [comment] 2021-09-16 22:56
@ViktorvdValk 

do you happen to know if this is still an issue?

**Comment by ViktorvdValk** [comment] 2021-09-17 09:48
I ended up using the "napari_experimental_provide_dock_widget()" for the elastix plugin instead, so I won't be able to tell you if the function widget is still an issue.

**Comment by tlambert03** [comment] 2021-09-17 09:59
Thanks!  I'm going to close this as not actionable for now.  But of course let us know if you're blocked by anything like this again

**Closed as completed by tlambert03** 2021-09-17 09:59 UTC
Labels: bug, topic:plugins
