### ISSUE TITLE
Switch to 3d error

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1905] opened 2020-11-19 17:25 UTC
## 🐛 Bug
The last RC of napari crash when switching to 3d rendering. Only PyQt affected. PySide works well. 
But when used as an embedded viewer (in PartSeg) works on PyQt.

```
WARNING: Error drawing visual <Volume at 0x7f3093a0d1c0>
18:19:45 WARNING Error drawing visual <Volume at 0x7f3093a0d1c0>
18:19:45 ERROR Unhandled exception:
Traceback (most recent call last):
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/visuals/visual.py", line 442, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/visuals/shaders/program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/glir.py", line 779, in _parse
    ob.draw(*args)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/glir.py", line 1329, in draw
    self._pre_draw()
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/glir.py", line 1289, in _pre_draw
    self._validate()
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/glir.py", line 1300, in _validate
    raise RuntimeError('Program validation error:\n%s'
RuntimeError: Program validation error:



Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

## To Reproduce

1. load 3d image
2. click to switch to 3d rendering
3.

## Environment
napari: 0.4.1rc2
Platform: Linux-5.4.0-53-generic-x86_64-with-glibc2.2.5
Python: 3.8.3 (default, Jun 26 2020, 19:57:39) [GCC 9.3.0]
Qt: 5.15.1
PyQt5: 5.15.1
NumPy: 1.19.0
SciPy: 1.5.1
Dask: 2.1.0
VisPy: 0.6.5

GL version: 4.6.0 NVIDIA 390.138
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari_plugin_engine: 0.1.8
- ome_zarr: 0.0.14
- svg: 0.1.4
 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context

@sofroniewn

**Comment by sofroniewn** [comment] 2020-11-19 17:39
Thanks for the report. Sounds like this wasn't fixed by disabling the welcome visual (or all the new axes/ scale bar visuals?) https://github.com/napari/napari/issues/1903#issuecomment-730523032.

We've been having a bunch of these pyqt5 related issues, see #1811 and #1835 for more discussion. Switching to PySide2 always fixes the problem

**Comment by sofroniewn** [comment] 2020-11-19 17:40
We've also struggled to reproduce them using vispy and pyqt5 only. Interesting to hear that it works on PartSeg with the napari viewer embedded. I really wonder what's going wrong!!

**Comment by Czaki** [comment] 2020-11-19 17:48
the problem is that ` gl.glGetProgramInfoLog(self._handle)` return empty string. So there is no information about what wrong happen.

**Comment by jni** [comment] 2020-11-20 06:50
Not only can I reproduce this on my Linux machine, but the GL texture limit introduced in #1857 seems to be returning incorrect results on my machine resulting in unnecessary resampling. I think we should revert that before 0.4.1. CC @VolkerH 

```pytb
 $ napari ~/data/ovarioles/droso-ovarioles-isotropic.tif 
/home/jni/projects/napari/napari/_vispy/vispy_image_layer.py:204: UserWarning: data shape (272, 592, 790) exceeds GL_MAX_TEXTURE_SIZE 645 in at least one axis and will be downsampled. Rendering is currently in 3D mode.
  warnings.warn(
WARNING: Error drawing visual <Volume at 0x7f4aec6e03d0>
00:46:22 WARNING Error drawing visual <Volume at 0x7f4aec6e03d0>
Segmentation fault (core dumped)
```

I'm going to run git bisect now to see where this happened... =( And also try a fresh environment.

**Comment by jni** [comment] 2020-11-20 07:26
Hmm. The problem went away for me in a fresh env. @Czaki do you see this issue in a fresh environment also?

**Comment by Czaki** [comment] 2020-11-20 08:54
> Hmm. The problem went away for me in a fresh env. @Czaki do you see this issue in a fresh environment also?

Also not shown in the fresh environment. But not see a difference in installed packages which could explain this.

**Comment by sofroniewn** [comment] 2020-11-23 03:30
We've decided to not instantiate the welcome visual for the 0.4.1 release which avoids this problem. We should probably more the welcome visual out of the vispy canvas and into a qt widget, but that can come for the 0.4.2 release

**Comment by andy-sweet** [comment] 2022-06-07 15:59
I don't think this has been an issue for a while. I think the welcome visual was made into a dedicated Qt widget in https://github.com/napari/napari/pull/2542 so we can probably close this.

@Czaki : if you agree, please close this issue. Otherwise, add more information. Thanks!

**Closed as completed** 2022-06-07 16:18 UTC
Labels: bug, topic:vispy, qt
