### ISSUE TITLE
Visual glitch when displaying tracks with missing timepoints

### ISSUE THREAD

**Issue by jules-vanaret** [napari/napari#6696] opened 2024-02-29 22:08 UTC
### 🐛 Bug Report

When displaying tracks with missing timepoints (e.g `[1,2,3,5,6]`), an anomalous track fragment (going forward into the future, even with `head_length=0`) appears at the timepoint just before the gap.

### 💡 Steps to Reproduce

The glitch can be seen with this minimal example when placing the slider at the timepoint 4/10:
```python
import napari
import numpy as np


coordinates = np.zeros((10,3))

coordinates[:,2] = np.arange(10)
coordinates[:,0] = np.arange(10)
coordinates[5:,0] += 1
coordinates[5:,2] += 1

tracks = np.ones((10, 4))
tracks[:, 1:] = coordinates

viewer = napari.Viewer()
viewer.add_tracks(tracks, tail_width=20)
viewer.add_points(tracks[:,2:], size=0.1)

napari.run()
```
or on this video:

https://github.com/napari/napari/assets/94963445/7b16260c-1758-40ba-98e1-090217d4e3fb

### 💡 Expected Behavior

The anomalous fragment should not appear.

### 🌎 Environment

napari: 0.1.dev3244+g0747da5
Platform: Linux-5.15.0-97-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.6 LTS
Python: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.26.4
SciPy: 1.12.0
Dask: 2024.2.1
VisPy: 0.14.1
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.4
npe2: 0.7.4

OpenGL:
  - GL version:  4.6 (Compatibility Profile) Mesa 21.2.6
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Settings path:
  - ~/.config/napari/napari-dev_ebc9c46b35c7ad556420cc56947aae90c9e81949/settings.yaml
Plugins:
  - napari: 0.1.dev3244+g0747da5 (81 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.1.10 (2 contributions)

### 💡 Additional Context

The function that tells Vispy how to draw the tracks is the `VERT_SHADER` in `napari/_vispy/filters/tracks.py`. Its a string of C++ code that is given to Vispy as a shader:
```python
    VERT_SHADER = """
        varying vec4 v_track_color;
        void apply_track_shading() {

            float alpha;

            if ($a_vertex_time > $current_time + $head_length) {
                // this is a hack to minimize the frag shader rendering ahead
                // of the current time point due to interpolation
                if ($a_vertex_time <= $current_time + 1){
                    alpha = -100.;
                } else {
                    alpha = 0.;
                }
            } else {
                // fade the track into the temporal distance, scaled by the
                // maximum tail and head length from the gui
                float fade = ($head_length + $current_time - $a_vertex_time) / ($tail_length + $head_length);
                alpha = clamp(1.0-fade, 0.0, 1.0);
            }

            // when use_fade is disabled, the entire track is visible
            if ($use_fade == 0) {
                alpha = 1.0;
            }

            // set the vertex alpha according to the fade
            v_track_color.a = alpha;
        }
    """
```
I am not entirely sure of how the part about setting `alpha` to `-100` works, but I have found that replacing
```c++
if ($a_vertex_time > $current_time + $head_length) {
    // this is a hack to minimize the frag shader rendering ahead
    // of the current time point due to interpolation
    if ($a_vertex_time <= $current_time + 1){
        alpha = -100.;
    } else {
        alpha = 0.;
    }
```
by
```c++
if ($a_vertex_time > $current_time + $head_length) {
    // this is a hack to minimize the frag shader rendering ahead
    // of the current time point due to interpolation
    alpha = -100.;
```
fixes the issue. I cannot affirm that it does not break some feature elsewhere.

**Comment by jni** [comment] 2024-03-08 07:22
Hey @jules-vanaret!

Thanks for the detailed issue and reproducer! The video is 👌!

Here's my understanding of what's going on:
- the whole track gets sent to the GPU/shader
- then parts of the line are made transparent based on the tail and head lengths
- the shader is set to linearly interpolate the colour and alpha between the timepoints, so that it looks nice when looking at a tail, and not choppy
- in the special case in which the head length is 0, we actually do want the track to be chopped off sharply. This is done by setting the next time point to -100 — which means that you are interpolating alpha between 1 and -100, so that after 1/101 of the distance between the points, you're fully transparent (it gets clamped to 0 just below). As the comment says, this is indeed pretty hacky! 😂 And I don't know why it's not -1000. (Indeed I would take this opportunity to change it to that.
- now, in your case, it's going 2 time points forward, and it's setting it to 0, so you get this interpolation to the next time point. I think the idea is that when your head length is nonzero and you get to the front of the head length, you want to fade gently.

You can confirm this by playing with the tracks_2d.py example, setting the head-length to some high value and tail length to 0. You can see that the track is brightest at the front, but, *when head length is nonzero*, it fades gently, whereas when it's 0 it has a hard stop.

So, imho the better way to preserve the current behaviour while fixing your issue is:

```c
if ($a_vertex_time > $current_time + $head_length) {
    // this is a hack to minimize the frag shader rendering ahead
    // of the current time point due to interpolation
    if ($head_length == 0){
        alpha = -100.;  // or -1000. maybe?
    } else {
        alpha = 0.;
    }
```

Alternatively, we could toss out the behaviour of fading the front of tracks... @quantumjot did you have a specific rationale for wanting it to behave like this? (@JoOkuma might also have thoughts here.)

What do you think @jules-vanaret?

**Comment by jules-vanaret** [comment] 2024-03-08 09:38
Thank you @jni for your answer! Ok I understand how the interpolation behaves in this special case, and why my "fix" solved it. 
To add a bit of context on my use case, I made a plugin to dynamically slice tracking data (in both space and time), and so when a track goes out of the ROI for a bit, then goes back in, its time indices in the array are discontinuous and the track displays with two annoying "artifacts": 
1. the first one is the problem stated in this issue
2. the second comes from the fact that when the track goes back in the ROI, the fading tail will appear from the last seen position of the track (before it goes out) to the new one, which leads to very long tails appearing suddenly if the two positions are relatively far from each other.
I would be very interested in a parameter (maybe of the Tracks layer) to impose one $\Delta t$ for all tracks, so that the viewer understands that any gap bigger than this $\Delta t$ in `tracks_data[:,1]` should lead to the track being cut and started again with hard stops. I understand that the current paradigm now is to allow the user to define tracks vertices at arbitrary timepoints though, so I reckon that this is not trivial to address. 

To go back on the fix you suggested for this issue, I can do the PR once we converge to an implementation that satisfies everyone. :)

**Comment by jni** [comment] 2024-03-09 00:01
> I would be very interested in a parameter (maybe of the Tracks layer) to impose one for all tracks, 

This seems hard (as you pointed out), and additionally, I am very careful about adding parameters to layers because the layer signatures have gotten so complex over time. So, I kind of like the head-length=0 hack for now, because I presume that's how most people view tracks data today? I also think that it would be uncontroversial, because it wouldn't actually break any existing display modes.

It's indeed a good idea to maybe wait for a few more comments and find consensus, but failing that (people are very busy these days 😅), I would suggest making that change, and then creating a new issue for solving the more general problem.

**Comment by JoOkuma** [comment] 2024-03-09 04:47
Hi @jules-vanaret , thanks for the detailed description.

I like @jni solution.

A lower-friction alternative to your $\Delta t$ suggestion would be to add that to your tool (napari plugin? ).
It's usually complex to add your custom vispy visual to napari, but I think in your case it could be done with a vispy filter. [This is](https://github.com/napari/napari/blob/27851ee92913e02b16d05b0aba19b126fa1e29e3/napari/_vispy/visuals/tracks.py#L18) where napari setups the filters for the tracks layer.

**Comment by jules-vanaret** [comment] 2024-03-10 15:36
Thank you very much @JoOkuma for the tip, I'll definitely do some tests to see what I can do by defining my custom vispy filter! 

After working on #6671, I realize that there is a potential last "low-friction" hack to solve the $\Delta t$ problem: in the method `build_tracks` of the `TrackManager` class, an array `track_connex` is defined ([here](https://github.com/jules-vanaret/napari/blob/27090c1c23fe91333ba6210247a1afed44d1030f/napari/layers/tracks/_track_utils.py#L287 "napari/napari/layers/tracks/_track_utils.py")) to tell Vispy how to link vertices that belong to the same track. `track_connex` is a 1D array of boolean value, in which a `False` indicates that the track ends. 
I have checked that `track_connex` values can be manually set to `False` at the positions in the array at which there is $\Delta t>1$, then calling `layer.events.rebuild_tracks()` leads to the gap-part of the line not appearing, which is perfect. This looks like:
```python
tracks_layer = ...

# indices of the vertices just before a time gap (Delta t > 1)  
indices_time_gap = np.where( np.diff(tracks_layer.data[:, 1]) >1 )[0]

tracks_layer._manager._track_connex[indices_time_gap] = False
tracks_layer.events.rebuild_tracks()
```
This three-lines solution is the simplest in my specific case.

**Comment by psobolewskiPhD** [comment] 2024-04-02 22:57
Thanks for bumping this @jules-vanaret 
Juan is on vacation, maybe @DragaDoncila has some thoughts as a tracks user?
Not sure who else from the core devs would be good to poll.

**Comment by DragaDoncila** [comment] 2024-04-03 00:23
I think Juan's suggested fix looks most natural both with and without `head_length=0` so I'd be happy to approve a PR with that change! 

I can see how the sudden very long tail is kinda weird (though in some applications I think it's desirable) and I think it's worth discussing a blessed way for users to toggle the behaviour of tracks that have long gaps across a dimension.

**Comment by jules-vanaret** [comment] 2024-04-03 09:42
Thank you both @psobolewskiPhD @DragaDoncila for your input! I'll make the PR sometime in the next days. :)

**Comment by jni** [comment] 2024-08-21 14:51
Looks like we forgot to close this 😅

**Closed as completed** 2024-08-21 14:52 UTC
Labels: bug
